### ISSUE TITLE
[APF] Individual Registration

### ISSUE THREAD

**Issue by arjunk** [avniproject/apfodishanutrition#1]
Location Hierarchy - Block >> GP >> Village/Hamlet
Subject Type - Person
Subject Name - Individual

Form requirement doc -
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=406612277

**Comment by utkarshavni** [comment]
Changed
datatype of RCH id - numeric - 12 digit validation
Marriage age validation - cannot be more than Age in completed years

**Comment by Gojo-Taqi** [comment]
Estimated time of completion:- 20 min

**Comment by Gojo-Taqi** [comment]
Completed in 13 min

**Comment by AchalaBelokar** [comment]
Tested in 15 min

**Comment by AchalaBelokar** [comment]
Marriage age validation - cannot be more than Age in completed years
It is not necessary for every 18 yr girls are married
