### ISSUE TITLE
[APF] QRT PW

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#10]
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1255247919

**Comment by kannangudalur** [comment]
@nupoorkhandelwal please add validation rule for 
"Date of referral"
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1255247919
