### ISSUE TITLE
On edit high risk decision should not get update

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#101]
Issue: We are setting high risk NO on individual registration and child enrolment and in pregnancy enrolment we are setting high risk on basis on enrolment observations, after that we are updating this values on the basis of encounters, but when someone edit the registration and enrolment then the value is getting updated and it is causing issue in consistency of high risk status in the entities.

Solution: If high risk is present then on edit high risk status should not update.

- [x] Individual registration 
- [x] Child enrolment
- [x] Pregnancy enrolment

**Comment by Dinesh2019** [comment]
Test scenario
1.Create the individual and enrol as high risk after that edit the registration the status of high risk should be remainded as yes.
2.Do the encounter as keep the high risk as yes and edit the enrol as high risk as no excepeted result high risk status should be yes 
3.Do the encounter high risk as no and edit the enrol which as the high risk status as no excepeted result high risk should be yes

**Comment by Dinesh2019** [comment]
Block for this card getting the associaiton error 10 and sync is taking too long

**Comment by BEULAHEVANJALIN** [comment]
Moved changes to production.

**Comment by Dinesh2019** [comment]
Test execution in prod :

https://drive.google.com/drive/folders/1sif0zRsqkmloMGeWbCcpDa7Jz8ZYFLaS

**Comment by sachsk** [comment]
@nupoorkhandelwal this is related to the apf fix please check it once.
