### ISSUE TITLE
[APF Support] Association errors and DATA fix

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#102]
Refer the script:https://github.com/avniproject/APF-Odisha/blob/main/high_risk.sql

Note: There are 4 subject type in this implementation and we are only dealing with individual subject so add subject_type check in all update query.

- [ ] 8185 encounter don't have the high risk status in obs
    `select *
from public.program_encounter
where observations::text not like '%be0ab05f-b0f3-43ec-b598-fdde0679104a%'
  and encounter_type_id in (
                            1653,
                            1655,
                            1656
    ) and  encounter_date_time notnull ;`

Logic to fix the data:

   
    - ANC:If delivery form filled then add High risk"" = no. otherwise If there is a non-empty array on encounter type 'ANC' for concept "High risk Conditions", then add an observation ""High risk"" = "yes". If not, add ""High risk"" = no.
    - Child followup: If for child Weight for Height Status == "SAM" or  Weight for age Status == "Severely Underweight", then add an observation "High risk" = "yes". If not, add "High risk" = no.
    - Delivery: Add ""High risk"" = no.

- [ ] 88 enrolment don't have high risk status in enrolment
   `select *
 from public.program_enrolment
 where observations::text not like '%be0ab05f-b0f3-43ec-b598-fdde0679104a%'`

 Logic to fix the data:
    

    - Pregnancy: Populate the latest (by encounter date time) value of "High risk" in program encounters of type ANC to the program enrolment.
                  if ANC is not present for enrolment then check "Red Flag (refer MCP card)" in enrolment if yes then  ""High risk"" = "yes", otherwise set "no"
    - Child: Populate the latest (by encounter date time) value of "High risk" in child Followup
                if child Followup not present for enrolment then set "no"

- [ ]  25 individuals don't have high risk present in individual_registration
  `select *
from public.individual
where observations::text not like '%be0ab05f-b0f3-43ec-b598-fdde0679104a%'
  and subject_type_id = 672;`

 Logic to fix the data:

    - Populate the latest (by enrolment date time) value of "High risk" from program enrolment into observations of registration
    - If Individual is not enrolled into program then set "no"

- [ ] Update Sync attributes(sync_concept_1_value) - Populate sync attributes of all individual, program_enrolment and program_encounter tables with the "High risk" observation present in individual.
 Entities to be fixed:

   - All individual (individual subject_type)
   - Encounters for all encounters in the child and pregnancy program
   - Program: Child and Pregnancy

- [ ]  5 Poshansathi dont have syncConcept1Values(yes & no )in their sync_settings

- Add yes and no in syncattribute of these users (from App designer)

    ``select sync_settings, *
from public.users u
         join user_group ug on u.id = ug.user_id
         join groups g on g.id = ug.group_id
where g.name = 'Poshan Sathi'
  and sync_settings::text not like
      '%"syncConcept1Values": ["8ebbf088-f292-483e-9084-7de919ce67b7", "a77bd700-1409-4d52-93bc-9fe32c0e169b"]%'
  and sync_settings::text not like
      '%"syncConcept1Values": ["a77bd700-1409-4d52-93bc-9fe32c0e169b", "8ebbf088-f292-483e-9084-7de919ce67b7"]%'
;``

**Comment by BEULAHEVANJALIN** [comment]
https://gist.github.com/BEULAHEVANJALIN/a8ecacd7adf1c5e776c76c682c1e6e3a

**Comment by Dinesh2019** [comment]
Test user for association error 
1.dineshg@apfodishauat (poshan)
2.beulah@apfodishauat(QRT user with both No and Yes)
3.AchalaB@apfodishauat(QRT user with high as yes)
4.7855067100@apfodishauat(QRT user with high risk as No)
5.dummytest@apfodishauat(poshan,administrator)
6.sachink@apfodishauat(QRT,Dev,administrator,Everyone) : getting association error :09
7.qrt@apfodishauat(Everyone,QRT,administrator) : getting association error :09

**Comment by nupoorkhandelwal** [comment]
https://github.com/avniproject/apfodishanutrition/blob/main/Data%20fix%20for%20missing%20sync%20attributes%20and%20assosciation%20errors.sql

**Comment by Dinesh2019** [comment]
Test in prod for Poshan :
9791217078@apfodisha - synced timing 7s
9777217291@apfodisha - getting association error 10 
8984704151@apfodisha - getting association error 10 
8260798458@apfodisha - synced timing 1m46s30
7978686348@apfodisha - getting error 10 
6351549187@apfodisha - getting error 10

**Comment by nupoorkhandelwal** [comment]
Even after migration, there are entities having missing sync concepts or decisions, need to fix them as well

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 as part of QA, please try syncing couple of Poshan Sathi. The output should be sync without any association error. In case the error comes please share details of the same please.

**Comment by Dinesh2019** [comment]
9337328608@apfodisha - getting error association 10

**Comment by vedfordev** [comment]
# Note:

#### User 9337328608@apfodisha

**Error:**
Error: ProgramEncounter{uuid='f7b43a99-5c09-4755-80ba-7df240d1c93d'} is unable to find ProgramEnrolment{uuid='9912bf28-6543-4040-99de-e9ac1f3ef41d'}

**Analysis:**
Checked address_id, sync_concept_1_value for individual, enrolment, encounter. They have same value


#### User 8260603307@apfodisha

**Error:**
Error: GroupSubject{uuid='d49e6f1c-bdc8-4a60-9e84-981b57c70cae'} is unable to find Individual{uuid='b13dade2-f6ad-4e71-890c-9c0e98e5b164'}

**Analysis:**
for ind ('b13dade2-f6ad-4e71-890c-9c0e98e5b164') sync_concept_1_value is missing


#### User 8117029236@apfodisha

**Error:**
Error: GroupSubject{uuid='15c540d8-4f93-4f2b-8e76-a654625ae73d'} is unable to find Individual{uuid='d6b88e00-d8ec-482a-a5f6-f6880ba2e9a6'}

**Analysis:**
for ind ('d6b88e00-d8ec-482a-a5f6-f6880ba2e9a6') sync_concept_1_value is missing

**Comment by nupoorkhandelwal** [comment]
Will move this card to QA ready once 5.0.1 is available on prod.
