### ISSUE TITLE
[APF Support] Fix decision rule to not update other entities on edit

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#104]
## Context
Currently, in APF on editing an older encounter, updates the decision for all the three entities (registration, enrolment & encounter) with current encounter details which is not right and can cause serious data inconsistency issues.

## Acceptance Criteria
1. Editing any older encounter should update that particular encounters decision only and not update the other entities decision values.
2. These changes should be made in all the encounters wherever decisions are getting added.

## Tech Tasks
1. Update rules in all the encounter decision rules to not add the decisions to enrolment and registration if it is not the latest encounter else, just update that encounter's decision only.
2. Make these changes in UAT, and get QAed
3. Move the changes to prod once verified on UAT.

**Comment by nupoorkhandelwal** [comment]
Child Followup -

'use strict';
({params, imports}) => {
    const programEncounter = params.entity;
    const decisions = params.decisions;
    const complicationsBuilderForWFA = new imports.rulesConfig.complicationsBuilder({
            programEncounter: programEncounter,
            complicationsConcept: "Weight for age z-score"
        },
        {
            programEnrolment: programEncounter,
            complicationsConcept: "High risk condition"
        });

    const height = programEncounter.getObservationValue("Height");
    const weight = programEncounter.getObservationValue("Weight");
    const asOnDate = programEncounter.encounterDateTime;
    const individual = programEncounter.programEnrolment.individual;
    const age = programEncounter.programEnrolment.individual.getAgeInMonths();

    const addIfRequired = (decisions, name, value) => {
        if (value === -0) value = 0;
        if (value !== undefined) decisions.push({name: name, value: value});
    };

    const getGradeforZscore = (zScore) => {
        let grade;
        if (zScore <= -3) {
            grade = 3;
        } else if (zScore > -3 && zScore < -2) {
            grade = 2;
        } else if (zScore >= -2) {
            grade = 1;
        }
        return grade;
    };

    const zScoresForChild = ruleServiceLibraryInterfaceForSharingModules.common.getZScore(individual, asOnDate, weight, height);

    const zScoreGradeStatusMappingWeightForAge = {
        '1': 'Normal',
        '2': 'Moderately Underweight',
        '3': 'Severely Underweight'
    };

    const zScoreGradeStatusMappingHeightForAge = {
        '1': 'Normal',
        '2': 'Stunted',
        '3': 'Severely stunted'
    };

    const zScoreGradeStatusMappingWeightForHeight = [
        ["SAM", -3],
        ["MAM", -2],
        ["Normal", 1],
        ["Normal", 2],
        ["Normal", 3],
        ["Normal", Infinity],
    ];

    const weightForHeightStatus = function (zScore) {
        let found = _.find(zScoreGradeStatusMappingWeightForHeight, function (currentStatus) {
            return zScore <= currentStatus[1];
        });
        return found && found[0];
    };


    const wfaGrade = getGradeforZscore(zScoresForChild.wfa);
    const wfaStatus = zScoreGradeStatusMappingWeightForAge[wfaGrade];
    const wfaZScore= zScoresForChild.wfa;



    const wfhStatus = weightForHeightStatus(zScoresForChild.wfh);
    const wfhGrade = getGradeforZscore(zScoresForChild.wfh)

    const hfaGrade = getGradeforZscore(zScoresForChild.hfa);
    const hfaZScore = zScoresForChild.hfa;
    const hfaStatus = zScoreGradeStatusMappingHeightForAge[hfaGrade];

    addIfRequired(decisions.encounterDecisions, "Weight for age z-score", zScoresForChild.wfa);
    addIfRequired(decisions.encounterDecisions, "Weight for age Grade", wfaGrade);
    addIfRequired(decisions.encounterDecisions, "Weight for age Status", wfaStatus ? [wfaStatus] : []);

    addIfRequired(decisions.encounterDecisions, "Height for age z-score", zScoresForChild.hfa);
    addIfRequired(decisions.encounterDecisions, "Height for age Grade", hfaGrade);
    addIfRequired(decisions.encounterDecisions, "Height for age Status", hfaStatus ? [hfaStatus] : []);


    addIfRequired(decisions.encounterDecisions, "Weight for height z-score", zScoresForChild.wfh);
    addIfRequired(decisions.encounterDecisions, "Weight for Height Status", wfhStatus ? [wfhStatus] : []);

    const encounterTypeName = programEncounter.encounterType.name;
    const latest = programEncounter.programEnrolment.lastFulfilledEncounter(encounterTypeName);

    if(programEncounter.uuid === latest.uuid){

        if(wfhStatus == "SAM" || wfaStatus == "Severely Underweight"){
            decisions.registrationDecisions.push({name : "High risk", value : "Yes"});
            decisions.enrolmentDecisions.push({name : "High risk", value : "Yes"});
            decisions.encounterDecisions.push({name : "High risk", value : "Yes"});
        }else {
            decisions.registrationDecisions.push({name : "High risk", value : "No"});
            decisions.enrolmentDecisions.push({name : "High risk", value : "No"});
            decisions.encounterDecisions.push({name : "High risk", value : "No"});
        }
    }else {
        if(wfhStatus == "SAM" || wfaStatus == "Severely Underweight"){
            decisions.encounterDecisions.push({name : "High risk", value : "Yes"});
        }else {
            decisions.encounterDecisions.push({name : "High risk", value : "No"});
        }
    }
    return decisions;
};

**Comment by vedfordev** [comment]
@nupoorkhandelwal 
Moved to prod
