### ISSUE TITLE
[APF Odisha] Fix rule failure error - Cannot read property 'getReadableValue' of undefined

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#105]
## Context
Currently, in APF getting a rule failure with error message - Cannot read property 'getReadableValue' of undefined
[Link](https://reporting.avniproject.org/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo1LCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOiJjYXJkX181NDIiLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLCJydWxlX3V1aWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJhZDFjNDlhYS02Mjk3LTRlNDItOTlmMS1lZGUwNThjYzI4NzIiXSxbIj0iLFsiZmllbGQiLCJvcmdhbmlzYXRpb24iLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJBUEYgT2Rpc2hhIl1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZmllbGQiLCJvcmdhbmlzYXRpb24iLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJydWxlX3V1aWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwiY29sdW1ucyI6W10sInZhbHVlcyI6W1siYWdncmVnYXRpb24iLDBdXX0sInBpdm90X3RhYmxlLmNvbGxhcHNlZF9yb3dzIjp7InZhbHVlIjpbIltcIklITVBcIl0iLCJbXCJHREdTR09NXCJdIiwiW1wiQXNod2luaVwiXSJdLCJyb3dzIjpbWyJmaWVsZCIsIm9yZ2FuaXNhdGlvbiIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsInJ1bGVfdXVpZCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dfX0sIm9yaWdpbmFsX2NhcmRfaWQiOjI3MjN9)

## Acceptance Criteria
1. Investigate the rule failure and fix the rule if it is relevant to the implementation rule
2. Mark all such entries as is_closed = true once the rule is fixed.

## Tech Tasks
1. Try to reproduce the error with the individual and rule uuid, get to the root cause
2. In case its a data issue then inform accordinly else update the rule in case rule has the problem
3. Get this tested on UAT and then move the change to prod

**Comment by vedfordev** [comment]
## Developer Note:

#### for rule ad1c49aa-6297-4e42-99f1-ede058cc2872

added condition that if **Date of Discharge** avialable then only schedule.


#### for rule 7fc029bc-9fd9-44d9-a176-5022dc7829fd

added condition in pnc eligiblity criteria that if **Date of delivery** is present.

**Comment by vedfordev** [comment]
@nupoorkhandelwal  moved to prod.
