### ISSUE TITLE
[APF Support] Fix Child Followup report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#107]
Support ticket - https://avni.freshdesk.com/a/tickets/3205

- [x] There should be only one row for a child in a selected duration of time. Currently we are getting more than one row for individuals where child followup was done more than once in that duration.

Sample sheet is added in the ticket as well, and one sample name that i found is coming twice is - Subasa  Juanga for the last month.

**Comment by nupoorkhandelwal** [comment]
set role apfodisha;
SELECT "Name" AS "Name",
       "Father's Name" AS "Father's Name",
       "Mother's name" AS "Mother's name",
       dob AS dob,
       "Severely Underweight" AS "Severely Underweight",
       "Moderately Underweight" AS "Moderately Underweight",
       "SAM" AS "SAM",
       "MAM" AS "MAM",
       "Stunted" AS "Stunted",
       "Severely Stunted" AS "Severely Stunted",
       "Height" AS "Height",
       "Weight" AS "Weight",
       "Number of day attended AWC (last month)" AS "Number of day attended AWC (last month)",
       "Is the child receiving egg from AWC" AS "Is the child receiving egg from AWC",
       "Did the child attended VHND last month" AS "Did the child attended VHND last month",
       "Is the child receiving THR from AWC" AS "Is the child receiving THR from AWC",
       "Block" AS "Block",
       "GP" AS "GP",
       "Village/Hamlet" AS "Village/Hamlet"
FROM
    (with encounters as
              (select ipa.individual_id "ind_id",
                      row_number() over (partition by ipa.individual_id
                          order by ipa.encounter_date_time desc nulls last) as latest_encounter,
                      ipa.encounter_date_time as encounter_date_time,
                      ipa."Weight for age Status" as "Weight for age Status",
                      ipa."Weight for height z-score" as "Weight for height z-score",
                      ipa."Height for age Status",
                      ipa."Weight for Height Status",
                      ipa."Height" as "Height",
                      ipa."Weight" as "Weight",
                      ipa."Number of day attended AWC (last month)" as "Number of day attended AWC (last month)",
                      ipa."Is the child receiving THR from AWC" as "Is the child receiving THR from AWC",
                      ipa."Is the child receiving egg from AWC" as "Is the child receiving egg from AWC",
                      ipa."Did the child attended VHND last month" as "Did the child attended VHND last month"
               from apfodisha.individual_child_child_followup ipa
               where ipa.is_voided = false
                 and encounter_date_time is not null
                 and (ipa.encounter_date_time > '2023-10-01T00:00:00'
                   AND ipa.encounter_date_time < '2023-10-31T00:00:00'
                   AND true) ) select concat(ind.first_name, ' ', ind.last_name) AS "Name",
                                      ind."Father/Husband's name" AS "Father's Name",
                                      m.first_name AS "Mother's name",
                                      ind.date_of_birth AS dob,
                                      case
                                          when enc."Weight for age Status" = 'Severely Underweight' then '☑️'
                                          else ''
                                          end AS "Severely Underweight",
                                      case
                                          when enc."Weight for age Status" = 'Moderately Underweight' then '☑️'
                                          else ''
                                          end AS "Moderately Underweight",
                                      case
                                          when enc."Weight for Height Status" = 'SAM' then '☑️'
                                          else ''
                                          end AS "SAM",
                                      case
                                          when enc."Weight for Height Status" = 'MAM' then '☑️'
                                          else ''
                                          end AS "MAM",
                                      case
                                          when enc."Height for age Status" = 'Stunted' then '☑️'
                                          else ''
                                          end AS "Stunted",
                                      case
                                          when enc."Height for age Status" = 'Severely stunted' then '☑️'
                                          else ''
                                          end AS "Severely Stunted",
                                      enc."Height" AS "Height",
                                      enc."Weight" AS "Weight",
                                      enc."Number of day attended AWC (last month)" AS "Number of day attended AWC (last month)",
                                      enc."Is the child receiving THR from AWC" AS "Is the child receiving THR from AWC",
                                      enc."Is the child receiving egg from AWC" AS "Is the child receiving egg from AWC",
                                      enc."Did the child attended VHND last month" AS "Did the child attended VHND last month",
                                      a."Block" AS "Block",
                                      a."GP" AS "GP",
                                      a."Village/Hamlet" AS "Village/Hamlet"
     from encounters enc
              join apfodisha.individual ind on ind.id = enc.ind_id
              left join individual_relationship ir on ind.id = ir.individual_b_id
              left join apfodisha.individual m on m.id = ir.individual_a_id
         and m.is_voided = false
              left join individual_relationship_type irt on irt.id = ir.relationship_type_id
         and irt.name in ('Mother-Son',
                          'Mother-Daughter')
              left join apfodisha.address a on ind.address_id = a.id
     where enc.latest_encounter = 1
       and ind.is_voided = false
       and a.is_voided = false) AS virtual_table
WHERE "Village/Hamlet" IN ('Budhakhaman') and "Name" = 'Subasa  Juanga'
LIMIT 1000;

**Comment by vedfordev** [comment]
added void check in query for relationship

**Comment by vedfordev** [comment]
@nupoorkhandelwal check once and close the ticket
