### ISSUE TITLE
[APF Support] Verify QRT usecase

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#110]
## Reference Support Ticket
- [x] https://avni.freshdesk.com/a/tickets/3118
- [x] https://avni.freshdesk.com/a/tickets/2954
- [x] https://avni.freshdesk.com/a/tickets/2941

## Tech Tasks
- [x] Write a script to get count of all High risk enrolments in a particular user's catchment
- [x] Once the count is available from DB, sync the user's catchment and cross check the counts on the dashboard
- [x] In case there are 2 QRT users having same catchment then cross check the count is same across both the devices
- [ ] Share the sync errors if any immediately

Pick the users from the tickets itself.

**Comment by Gojo-Taqi** [comment]
Query to get the number of individuals should get synced based on the users catchment and "High risk" as 'Yes'.
`select count(*)
from individual i
where i.address_id in (
select village.id
from users u
inner join catchment_address_mapping cam on cam.catchment_id = u.catchment_id 
inner join address_level pro_block on pro_block.id = cam.addresslevel_id 
inner join address_level gp on gp.parent_id = pro_block.id 
inner join address_level village on village.parent_id = gp.id 
where u.username = '7846951001@apfodisha' )
and i.subject_type_id = 672
and i.is_voided is false
and (i.observations ->>'be0ab05f-b0f3-43ec-b598-fdde0679104a' = '["8ebbf088-f292-483e-9084-7de919ce67b7"]' )
;

--["a77bd700-1409-4d52-93bc-9fe32c0e169b"] -- No
--["8ebbf088-f292-483e-9084-7de919ce67b7"] -- Yes`

**Comment by Gojo-Taqi** [comment]
-- List of users who completed sync
 1. 7846951001@apfodisha - no_subjects -> 856, Matches count from db and in app
 2. 7077280370@apfodisha - no_subjects -> 856, Matches count from db and in app
 3. 7847977769@apfodisha - no_subjects -> 1156, Matches count from db and in app
 4. 9337728714@apfodisha - no_subjects -> 1156, Matches count from db and in app
 5. 6371024901@apfodisha - no_subjects -> 1818, Matches count from db and in app
 6. 8327789523@apfodisha - no_subjects ->	1818, Matches count from db and in app
 7. 9583312618@apfodisha - no_subjects -> 2292, Matches count from db and in app
 8. 9438291983@apfodisha - no_subjects -> 2292, Matches count from db and in app
 9. 9777835235@apfodisha - no_subjects -> 1122, Matches count from db and in app
10. 9668632365@apfodisha - no_subjects -> 1122, Matches count from db and in app

**Comment by Gojo-Taqi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9sQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b716e09888a5b1c459482bcc5845193585fb0079/Screenshot%20from%202023-11-17%2012-45-32.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3bfd9786d6c890830b39ac76c037622200acb6a/1700215295488.JPEG)

------------------------------------

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--416258c7d26fbf0ac449ad45e289b59acd19e9d7/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b8c4d5f4ceebeff6fa3b4da0331094efb34551e/1700215567622.JPEG)

**Comment by Dinesh2019** [comment]
for this individual 9583312618@apfodisha we have counted a match of one individual

database:

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9752f814ad9e7d4eb2e1ec924eae181f2179f071/Screenshot%202023-11-18%20at%2010.00.24%E2%80%AFAM.png

Screenshot :

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0RwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f56be089cc63d47625726e2f5c6d37da0aca9994/Screenshot%202023-11-18%20at%2010.01.22%E2%80%AFAM.png

**Comment by Dinesh2019** [comment]
When have the high risk and No then value is not matched 

Database:

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGJwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--389eee38d2d6698194ea19fadd225f9085900c0e/Screenshot%202023-11-18%20at%207.45.05%E2%80%AFPM.png


Screenshot

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd841abc9af5b486fa376fe6bce1aa8ec3fff782/Screenshot%202023-11-18%20at%207.46.53%E2%80%AFPM.png

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019  from user maha_nayak@apfodisha please use following query-

```
set role apfodisha;
select count(*)
from individual i
where i.address_id in (
    select addresslevel_id
    from users u
             inner join catchment_address_mapping cam on cam.catchment_id = u.catchment_id
--              inner join address_level pro_block on pro_block.id = cam.addresslevel_id
--              inner join address_level gp on gp.parent_id = pro_block.id
--              inner join address_level village on village.parent_id = gp.id
    where u.id = 9585
--         u.username = 'maha_nayak@apfodisha'
    )
  and i.subject_type_id = 672
  and i.is_voided is false
  and
       i.observations ->>'be0ab05f-b0f3-43ec-b598-fdde0679104a' = '["a77bd700-1409-4d52-93bc-9fe32c0e169b"]'
;
```
