### ISSUE TITLE
Remove all the unnecessary offline report cards for QRT users 

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/apfodishanutrition#111]
Reference to the support ticket- https://avni.freshdesk.com/a/tickets/3275

### A QRT user must be able to see only 3 dashboards.

- [x] On the first one, the user must be able to see only "High-risk pregnancies" under the Pregnancy section and "SAM children", "MAM children" under the Child section

- [x] On the second dashboard, the user must be able to see QRT PW follow-up both due and overdue, along with QRT PW due and overdue.

- [x] On the third dashboard, the user must be able to see QRT child follow-up, QRT SAM child, and NRC, both due and overdue for all 3 sections.

**Comment by Gojo-Taqi** [comment]
Time taken to complete development- 2.5 hours

**Comment by Dinesh2019** [comment]
Getting the association error when we have a high risk as No 

user : dineshg@apfodishauat

<img width="397" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFUyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b9bb1256c3a98603df4a0be61ef52bf5cb0cde2/Screenshot%202023-12-06%20at%208.58.53%E2%80%AFAM.png" alt="Screenshot 2023-12-06 at 8.58.53 AM.png" />

Web app :

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGMyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5793bfdb46aad1cad09a780ceab13b46b4f838cf/Screenshot%202023-12-06%20at%208.59.43%E2%80%AFAM.png" alt="Screenshot 2023-12-06 at 8.59.43 AM.png" />

**Comment by Dinesh2019** [comment]
Note : If we change the user level sync attribute for High risk yes or No we have to do the fresh sync 

Test execution :


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c446d9de3483b6179a8cf51af27a6cfd4a32cf7/Screen%20Recording%202023-12-12%20at%2011.23.23%E2%80%AFAM.mov
