### ISSUE TITLE
Create a report for children who are not added in a household

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/apfodishanutrition#112]
Link to the ticket:- https://avni.freshdesk.com/a/tickets/3274

### Create an alert report which gives you the list of individual children who are not added in a household.

The report should have the following columns:-
- Name
- DOB
- Block
- GP
- Village

Constraints:-
- Individual should be enrolled in child program
- Individual should not be marked as voided

Send an alert to Ramesh.

**Comment by Gojo-Taqi** [comment]
Link to the code- https://gist.github.com/Gojo-Taqi/a1496ac5c3472caf4fe711aae336f561

**Comment by Gojo-Taqi** [comment]
Time taken to move to code review ready - 40 mins

**Comment by Gojo-Taqi** [comment]
Link to the report- https://reporting.avniproject.org/question/2861-children-who-have-not-been-added-to-a-household-under-testing

**Comment by nupoorkhandelwal** [comment]
@Gojo-Taqi please replace group_subject table with apfodisha.household_individual, so that report runs faster

**Comment by Gojo-Taqi** [comment]
Done @nupoorkhandelwal

**Comment by nupoorkhandelwal** [comment]
@Gojo-Taqi alert is not yet setup.

**Comment by Dinesh2019** [comment]
query which i used for testing
