### ISSUE TITLE
Offline report for users which should show child followup visits not completed for that month

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/apfodishanutrition#113]
Link to the support ticket- https://avni.freshdesk.com/a/tickets/3277

### Motivation
The AWCs and the government of Odisha force the centers to track the height and weight in child follow-up encounters of the beneficiaries on or before the 10th of each month.

The issue with the users right now is, that they have no way to find out which children they need to do their followups, and which all they have done for the month.
The due visits report card helps only if the visits status is marked as due.

### Solution
Create an offline report, which should return the list of the children whose child follow-up is not done for that month.

Constraints:-
- Individual must not be voided
- Age should be less than 6 years
- Should be enrolled in a child program
- Should have not exited the program
- Child follow-up encounter should be scheduled for that month

By doing this, the users will complete all the follow-ups for the children listed on this card.

**Comment by nupoorkhandelwal** [comment]
@Gojo-Taqi  What is the name of the card that you created? how should i check the code?

**Comment by Gojo-Taqi** [comment]
@nupoorkhandelwal the name of the card is "Child followup due"

**Comment by Dinesh2019** [comment]
Getting association error : 

User : Taqi@apfodishauat,dineshg@apfodishauat,maha@apfodishauat

<img width="353" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--223b44fab19beeb15d0b1cb5483d7c8ba030d0b9/Screenshot%202023-12-13%20at%2012.56.07%E2%80%AFPM.png" alt="Screenshot 2023-12-13 at 12.56.07 PM.png" />

**Comment by Gojo-Taqi** [comment]
# Analysis done

- Checked if the entities have sync concept values and they did have sync_values
- Checked if the entities had the same address_id's and they were same
- Checked if the address_id was in the catchment of the user and they were present in the catchment.

Will need someone to pair on this issue.

**Comment by Gojo-Taqi** [comment]
For now the catchment has been changed, moving the card to QA ready

**Comment by Dinesh2019** [comment]
Test execution video :

https://drive.google.com/drive/folders/1EO4qd80z8LUCoQU-YMhUQJCaJLkZpEVp
