### ISSUE TITLE
Add a new option/answer in NRC name concept in NRC form

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/apfodishanutrition#114]
Link to the ticket- https://avni.freshdesk.com/a/tickets/3284

These are the options right now for the question NRC name- 
- Koenjhar NRC
- Harichandrapur NRC
- Badbil NRC
- Banspal NRC
- Nabrangpur (Umerkote & Nabrangpur)
- Rayagada (Rayagada & Gunpur)
- Sundergarh (Bonai, Rourkela & Sundergarh)
- Mayurbhanj (Karanjia, Betanoti, Kaptipada & Baripada)
---------------------------

- [x] And these are the options that should be available- 
    - Keonjhar (Harichandanapur, Badbil, Banspal & Keonjhar)
    - Nabrangpur (Umerkote & Nabrangpur)
    - Rayagada (Rayagada & Gunpur)
    - Sundergarh (Bonai, Rourkela & Sundergarh)
    - Mayurbhanj (Karanjia, Betanoti, Kaptipada & Baripada)
    
- [x] For all those encounters who have selected either of the following options -> "Koenjhar NRC", "Harichandrapur NRC", "Badbil NRC" and "Banspal NRC", migrate them to "Keonjhar (Harichandanapur, Badbil, Banspal & Keonjhar)".

**Comment by Gojo-Taqi** [comment]
Link to the query- https://gist.github.com/Gojo-Taqi/5198de7cc763447522a550385b8ba201

**Comment by Gojo-Taqi** [comment]
Time taken to move card to code review ready- 40 mins

**Comment by Gojo-Taqi** [comment]
@nupoorkhandelwal here is the link to the concept- https://app.avniproject.org/#/appDesigner/concept/93307180-fab8-43f7-8a79-596e7973b9b9/show

**Comment by nupoorkhandelwal** [comment]
@Gojo-Taqi why are u making these changes on production directly?

**Comment by Gojo-Taqi** [comment]
Ohhh, I think by mistake I put in the script for prod.

**Comment by Gojo-Taqi** [comment]
@nupoorkhandelwal Updated the queires. Added both the UAT and prod queries

**Comment by nupoorkhandelwal** [comment]
@Gojo-Taqi you can run this on UAT, and get the count of those individuals (before and after). Also, check the ind in the app as well when this migration is done.
