### ISSUE TITLE
Delivery encounter is getting scheduled even though it was already completed

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/apfodishanutrition#117]
Link to the ticket- https://avni.freshdesk.com/a/tickets/3332

The delivery encounter was already completed, and on canceling one of the scheduled ANC encounters, the Delivery encounter got scheduled again.
On looking into the visit scheduling rule of cancellation of ANC encounter, it is not checked if the Delivery encounter is already completed or not.

- [x] Add check on ANC encounter saying, that if a Delivery encounter is already present, then do not schedule.
- [x] Add a check in the cancellation of ANC saying, that if a Delivery encounter is already present, then do not schedule. 
- [x] Schedule delivery encounter on enrolment with 270 days as the earliest from LMP and 275 as the max date from LMP.

**Comment by Dinesh2019** [comment]
- [ ] If we do the unplanned visit then we can able to do the ANC visit taqi is looking into it
