### ISSUE TITLE
Void all subject that are registered against "Baujadi", "Dimbrisahi", and "Goilkana" address_level.

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/apfodishanutrition#118]
Link to the ticket- https://avni.freshdesk.com/a/tickets/3345 

Right now this village is not required, hence we request you to void all the subjects and remove this address from all the catchments as well.

Following is the address where all the subject types need to be voided.
`select * from address_level al where title = 'Baujadi';`
`select * from address_level al where title = 'Dimbrisahi';`
`select * from address_level al where title = 'Goilkana';`

- [ ] Void all the subject types, program_enrollments, and program_encounters against these addresses.
- [ ] Remove this address from all the catchments that have this village.
- [ ] Check if the users are able to sync without any issues.

**Comment by petmongrels** [comment]
@mahalakshme @Gojo-Taqi @nupoorkhandelwal Instead of doing the subject update directly in the database, we should add a bulk API for it which can be invoked via postman. We had earlier added one API for subject migration like this - we can start maintaining a page for this.

Item 2 & 3 can be done via current UI.

**Comment by mahalakshme** [comment]
since the requirement is delete of location - and hence all related things need to be deleted. Is this kind of requirement a pattern? If so, we can add a feature to do it via UI. cc: @petmongrels @nupoorkhandelwal

**Comment by mahalakshme** [comment]
product card to prevent touching the db: https://github.com/avniproject/avni-server/issues/677 will be released as part of 6.1.0 or 6.1.1

**Comment by mahalakshme** [comment]
@Gojo-Taqi @nupoorkhandelwal the referred product card will be released as part of 7.0 since some urgent tickets have come up and testing on existing things for 6.0 itself ve not got completed.
