### ISSUE TITLE
[Presales]APF Phase 2

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#119]

**Comment by pkundu** [comment]
@Parth7223 move the associated tickets also to New status. Right now they are in next up
2. Is there any other requirement list? Add the link here

**Comment by Parth7223** [comment]
APF had shared requirement list on google sheets long back, which is inaccessible. Salil has asked APF to reshare the requirement list. I will attach it here once received.

**Comment by pkundu** [comment]
@Parth7223 this is APF Phase 2. Have renamed it
