### ISSUE TITLE
[APF Support] Void all data under some locations

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#120]
## Support ticket 
https://avni.freshdesk.com/a/tickets/3478

## Context
All the data (ie. Subjects, Program Enrolments and respective encounters) under the villages that are shared a s part of the support ticket 

## List of villages 
1. Palamondra #331263
2. Sanagangara #331267
3. Sapagaru #331270
4. Kodaghati #331257
5. Bada Dahikhal #388460
6. Baujadi #331354
7. Laxmi Panga #331178
8. Tabapadat #331181
9. K.Kupuli #331513
10. Barikhal #331509
12. Depaguda #331510
13. Ghangarpada #331512
14. Kanadipadar #331514
15. Sikakhal #331524
16. Bada Kandulpada #373201
17. Mumikhal #331342
18. Garlagudi #331511
19. Lundrubari #331444

## Tech task

- [ ] Write a script to void all the data from the above villages (Get it reviewed & then execute)
- [ ] Check reports and alerts that the data from these villages is not coming

**Comment by Gojo-Taqi** [comment]
@nupoorkhandelwal can you review this please?
https://github.com/avniproject/APF-Odisha/blob/main/Script%20to%20void%20subjects%2C%20enrolments%2C%20encounters%20and%20address.sql

**Comment by Gojo-Taqi** [comment]
Moving this card back to support ready as the API will be released on 7.0
