### ISSUE TITLE
[APF Odisha Support] Add Individual Id to some reports

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#131]
## Support tickets
https://avni.freshdesk.com/a/tickets/3589
https://avni.freshdesk.com/a/tickets/3597

## Reports 
1. QRT SAM child report
2. PNC Report
3. ANC Report

## Tech tasks 

- [x] Add Individual Id column ie. "Beneficiary Id" in the above mentioned reports.
- [x] Add Project/Block column in the first report
- [x] Do not break any exiting logic or filter while adding

**Comment by Dinesh2019** [comment]
- [ ] QRT SAM child report we are getting a time-out error after applying the  QRT Visited filter. Reports take too much time to respond in db as well 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--785edad0fc09e88ee231a967d2fda90947462809/Screenshot%202024-03-04%20at%202.32.36%E2%80%AFPM.png" alt="Screenshot 2024-03-04 at 2.32.36 PM.png" />

**Comment by BEULAHEVANJALIN** [comment]
Seems like the query is okay. but we can still make it better!.  It took like about 6 minutes and 44 seconds to retrieve 3517 rows, which is slower than ideal :(
Also there's a client-side timeout limit in Superset hwich was set to 60 sec. And we also need to extend this time limit in the configuration files to accommodate longer queries. 60 secs is quite a short amount of time and getting a timeout errorimmidiately for 1 min shouldn't be good. 

So let's also increase the time limit (if possible) and also work on improving the query as well.



Please refer: https://www.restack.io/docs/superset-knowledge-apache-superset-query-timeout-fix

**Comment by BEULAHEVANJALIN** [comment]
Report link: https://reporting-superset.avniproject.org/superset/dashboard/30/?native_filters_key=9xvqaq1eaTzuWNnoVaGnmEeB1DLJQGLAHwK83h96oqUpxrt2c12jxJw3FSBIYFON

**Comment by BEULAHEVANJALIN** [comment]
Report link: https://reporting-superset.avniproject.org/superset/dashboard/30/?native_filters_key=9xvqaq1eaTzuWNnoVaGnmEeB1DLJQGLAHwK83h96oqUpxrt2c12jxJw3FSBIYFON

**Comment by BEULAHEVANJALIN** [comment]
Have created a new query and a new dashboard for testing

Dashboard link: https://reporting-superset.avniproject.org/superset/dashboard/89/

**Comment by Dinesh2019** [comment]
Date filter is missing in the new report

**Comment by BEULAHEVANJALIN** [comment]
I have intentionally omitted the date filter because we are analysing the entire dataset, and the aim is to avoid timeout errors (you prev QA issue). Let me know if the query runs faster and if the data retrieved match accurately without any mismatch. This report is just a draft report as we only worked on optimising the query. If everything is fine, i will replace the original one.
