### ISSUE TITLE
APF | Household registration form changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#133]
- [ ] Add following questions to the household registration form: 
       (i) Number of members in the family
       (ii) Gender of head of the family 

- [x] Changes are highlighted in green. Please refer to highlighted questions from form analysis [here](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1229007889)

**Comment by BEULAHEVANJALIN** [comment]
For the `Registration Location` field we can simply switch on location tracking at the user level settings, so this form field is not really necessary.

**Comment by BEULAHEVANJALIN** [comment]
Update query to enable location tracking.

```sql
SET ROLE apfodishauat;

SELECT *
FROM public.users
WHERE users.id = 6415;

UPDATE public.users
SET users.settings = COALESCE(users.settings, '{}'::jsonb) || '{
  "trackLocation": true
}'::jsonb
WHERE users.id = 6415;
```

**Comment by Dinesh2019** [comment]
@BEULAHEVANJALIN we can move the changes to prod
