### ISSUE TITLE
APF| ANC Form changes

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#137]
- [x] Changes to be made in UAT
- [x] **Form Name:** ANC form
- [x] **Visit schedule:** There is a change in the visit schedule logic from the existing one. Currently ANC form is scheduled on LMP+ 60, LMP+170, LMP+260 and LMP+ 270. **We need to change it to monthly**
**[Link 1]**(https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=2:2)

**[Link 2]**(https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=3:3)

- [x] **On any edit made in this form as well as the subject registration form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled**
- [x] **On cancellation made** in this form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled**
- [x] If reason of cancellation is Delivery/Abortion, Death,Migrated to other geography then no forward visit schedule.
- [x] **On Overschedule,** don't allow user to enter data.
Need to add a validation message in the 1st question and the 1st mandatory question stating
"Overdue forms cannot be filled, please cancel this form so that next due form can be scheduled"
- [x] **Form Changes:**

 Question highlighted in **Green** needs to be added to the form. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=836611880)

- [x] **Note (Just for reference. Out of scope for this card) :** High Risk: (Geographical and Clinically High Risk) both conditions should be applicable here and we need to show that in the form summary. [Geographical High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/159) [Clinically High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/158)
 
- [x] **Process Flow (Just for reference):** https://drive.google.com/drive/search?q=APF

---

**Pregancy geographically high risk** depends on | #159
**Did the ANM recommend for a medical facility internetion? (for any reason)** depends on | #158

**Comment by vedfordev** [comment]
@AnjaliBhagabati If someone cancel scheduled visit in January. it should schedule for feb?

**Comment by AnjaliBhagabati** [comment]
@vedfordev if visit for Jan is canceled it should not be schedule for Feb. For Feb, Feb month visit should be scheduled

**Comment by Dinesh2019** [comment]
Not Tested :
logic for below is not tested 
BP Systolic Previous Month
BP Systolic Current Month
BP Diastolic Previous Month
BP Diastolic - Current Month
