### ISSUE TITLE
APF| Delivery Form Changes

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#138]
- [ ] Changes to be made in UAT
- [ ] **Form Name:** Delivery Form
- [ ] Form [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1368760264)
- [ ] Question highlighted in Green needs to be added and the ones on Red are to be removed
- [ ] **Visit schedule:** 
Link: https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=8:8

- [ ] **On any edit made** in this form as well as the subject registration form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled

- [ ] Form Changes:
Question highlighted in Green needs to be added to the form. Link

- [ ] **Note:** High Risk condition (both Geographically and Clinically High Risk) are not applicable from Delivery Form onwards. We don't need to apply and show High Risk in this form
- [ ] **Process Flow (Just for reference):** https://drive.google.com/drive/search?q=APF

**Comment by nupoorkhandelwal** [comment]
@AnjaliBhagabati Delivery form's Cancel access will not be given to any user. So there will be no cancel scenario in this card. Please update it accordingly.
