### ISSUE TITLE
APF| PNC Form changes

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#139]
- [x] Changes to be made in UAT
 - [x] **Form Name:** PNC Form
 - [x] Form [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=701265360)
 - [x] Question highlighted in Green needs to be added and the ones on Red are to be removed
 - [x] **Visit schedule:**
[Link: ](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=9:9)
- [x] **On any edit made** in this form as well as the subject registration form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
- [x] **On cancellation made** in this form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
- [x] **If reason of cancellation** is Death,Migrated to other geography then no forward visit schedule.
- [x] **On Overschedule,** don't allow user to enter data.
Need to add a validation message in the 1st question and the 1st mandatory question stating
"Overdue forms cannot be filled, please cancel this form so that next due form can be scheduled"

- [x] **Note:** High Risk condition (both Geographically and Clinically High Risk) are not applicable from Delivery Form onwards. We don't need to apply and show High Risk in this form

- [x] **Process Flow (Just for reference):** https://drive.google.com/drive/search?q=APF

**Comment by nupoorkhandelwal** [comment]
@AnjaliBhagabati added a comment in the form on the Q. "How many pads are being changed in a day". Check the datatype. Rest all looks fine.

**Comment by pkundu** [comment]
@nupoorkhandelwal @AnjaliBhagabati let's take a judgement call on these kind of issues and move them forward. Not worth spending too much time on such things. In this case, since options are given it will be single select.

**Comment by nupoorkhandelwal** [comment]
@AnjaliBhagabati to update the options for "Is there any medical complications?"
