### ISSUE TITLE
[APF] NRC Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#14]
- [x] Create a program encounter under "Child" program - "NRC"
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=287957931

**Comment by kannangudalur** [comment]
@nupoorkhandelwal 
1. Date of admission in NRC
2. Date of discharge from NRC
Please add the validation rule for this.
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=287957931
