### ISSUE TITLE
APF | Growth Monitoring Form Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#140]
- [x] All changes to be done in UAT first.

- [x] **Form name** 'Child followup' to be changed to 'Growth Monitoring'. This has to be done for encounter type also
- [x] Questions highlighted in Green colour need to be added and the one in Red are to be removed [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=960251287)
- [x] The form has questions related to Nutrition status & Growth Faltering, where Nutrition status logic will remain same as earlier but Growth Faltering will depend on logic given [here.](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1331517176)
- [x] Nutrition status should be provided in the form summary (Should populate nutrition status= SAM/MAM/Normal)
- [x] Growth Faltering should be provided in the form summary (Should populate Growth faltering= GF1/GF2/None) [Logic](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1331517176)

- [ ] **Out of scope:** QRT child visit scheduling based on the nutrition status & growth faltering is not part of this card. that will covered in a separate exercise. 
- [ ] [Process Flow](https://drive.google.com/file/d/15vBrsfJZ16ggdGtlh3iaVKJkY5_O22Za/view?usp=sharing) (Just for reference)
- [ ] Note: Changing encounter type name will lead to change in existing ETL table names.
All child related reports on Superset will have to be taken care off.

**Comment by nupoorkhandelwal** [comment]
@Parth7223 @AnjaliBhagabati Changing encounter type name will lead to change in existing ETL table names. 
All child related reports on Superset will have to be taken care off.

**Comment by nupoorkhandelwal** [comment]
@Parth7223 as discussed please add both the autocalulated fields in the form ie. Nutritional Status & GF status.

**Comment by Dinesh2019** [comment]
@parth we have to change the rule for offline dashboard pervious it was using child followup instead of growth monitoring can we add this point in this card or else are we going to create the separate card
