### ISSUE TITLE
[APF Odisha Phase-2] : Go-Live: Checklist For L1 Support (Translation, Location, Users & Catchment Upload)

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#146]
- [x] Location and Users Upload in the new format

1. Download the Users and Catchment Sample from the Upload section of the Admin console, as the format has changed. 
You need to create the users and catchment list in the new format and upload

2. Currently for some existing users, they are only in the "Everyone" group and not assigned to any other group. "Everyone" user group doesn't have any permissions enabled so they will not be able to view anything. So please assign proper groups to all users. 

- [x] [Village Location and Geographically hard to reach village upload in this format](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=644314954#gid=644314954)
- [x] Transaltion

1. On Lokalise, upload the latest keys from Avni
2. Change translation for Scheduled and overdue in Odia
3. Now, upload back the Odia translated keys to the Avni org

**Comment by AnjaliBhagabati** [comment]
@nupoorkhandelwal closing this card as well as it will be done by Subhamita after we setup the production environment
