### ISSUE TITLE
APF | Individual Registration Form Changes (New)

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#150]
- [x] Changes to be done in UAT
- [x] **Form Name:** Individual Registration form
- [x] Questions highlighted in Green is to be added in the form
- [x] The one in Red should be removed from the form. 
- [x] **Form** [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=406612277)
- [x] No impact on visit scheduling

**Comment by Dinesh2019** [comment]
- [ ] Mother's Name is not added to the form 
@Parth7223 For this Martial Status the logic is updated in the card but I think we haven't updated the rule can you please highlight it in green so that developer can updated it
