### ISSUE TITLE
APF | Pregnancy Enrolment Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#151]
All changes are to be made in UAT first.
**Form Name:** Pregnancy Enrollment
**Enrolment Logic:** We need to change the Enrolment logic for this form. Currently Females with age 12 years and more are enrolled into the Pregnancy Program, we need to change it to Female with 10 years or more.
Change the age limit from Female 12years to Female 10 years.

On any edit made in this form as well as the subject registration form, no visit should be rescheduled again for the same month
On cancellation made in this form as well as the subject registration form, no monthly visit should be rescheduled again in the same month

- [x] Questions highlighted in green are to be added to the form. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=893561151)
- [x] Question highlighted in yellow needs to be removed from the form. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=893561151&range=17:17)
**Note (Just for reference. Out of scope for this card) :** **High Risk: (Geographical and Clinically High Risk)** both conditions should be applicable here and we need to show that in the form summary. [Geographical High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/159) [Clinically High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/158)
**No QRT will be scheduled** based on any High Risk condition detected in this form
**Process Flow** (Just for reference): https://drive.google.com/drive/search?q=APF

**Comment by nupoorkhandelwal** [comment]
@Parth7223 where are the conditions for High risk? Attach the req link.

**Comment by nupoorkhandelwal** [comment]
@Parth7223 where are the conditions for High risk? Attach the req link.

**Comment by Dinesh2019** [comment]
Created the bug for page refresh : https://github.com/avniproject/avni-client/issues/1354
