### ISSUE TITLE
APF | PW Home Visit Form Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#156]
- [ ] Changes to be done in UAT
- [x] **Form Name:** PW Home Visit form
- [x] This form is a replacement of the existing QRT PW followup (Edit the same QRT PW Followup form only)
- [x]  We need to replace the current QRT PW followup  with the new PW Home Visit form. The questions and the Visit Schedule logic everything will change
- [x] Questions highlighted in Green needs to be added and the Red ones to be removed. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1263394261)
- [ ] **Visit Scheduling:** This form will be scheduled for two different High Risk Scenarios. 
1. [High Risk Condition for which **QRT has been Scheduled:*](ˇ)* In this scenario this form will be **scheduled at a interval of 15 days from QRT PW  for 4 times**
2. [High Risk Condition for which **No QRT has been Scheduled:**](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=5:5): in this scenario the schedule logic will be dynamic and will be based on ANC evaluation. To be scheduled on 1st of next month from ANC and will be dynamic and based on  monthly ANC  evaluation 

- [ ] **On any edit** made in this form as well as the subject registration form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled

- [ ] **On cancellation made i**n this form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
- [ ] If reason of cancellation is Delivery/Abortion, Death, Migrated to other geography then no forward visit schedule.
- [ ] **On Overschedule,** don't allow user to enter data.
Need to add a validation message in the 1st question and the 1st mandatory question stating
"Overdue forms cannot be filled, please cancel this form so that next due form can be scheduled"
- [ ]  **Note (Just for reference. Out of scope for this card)** : High Risk: (Geographical and Clinically High Risk) both conditions should be applicable here and we need to show that in the form summary. [Geographical High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/159) [Clinically High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/158)
- [ ]  **Process Flow (Just for reference):** https://drive.google.com/drive/search?q=APF

## Tech note 

- For visit scheduling just consider (latest in entire enrolment) existing decision concept in "High risk condition".
- As mentioned changes related to "High risk condition" will be covered in a separate card.

**Comment by adamsanadi6** [comment]
@Parth7223, do I have to create a new form or do I have to edit the existing QRT PW follow-up?

**Comment by AnjaliBhagabati** [comment]
@adamsanadi6 you have to edit the existing QRT PW follow-up and remane it to PW Home Visit . Also I have updated the visit schedule logic based on our latest conversation with the client. Could you please relook at the Visit Schedule logic

**Comment by adamsanadi6** [comment]
@AnjaliBhagabati  as discussed, we are focusing solely on form changes. For visit scheduling. Since we require high-risk condition (QRT conditions) information to schedule visits, and it's currently unavailable, we're putting the visit scheduling part on hold. Only form changes have been implemented.

**Comment by Dinesh2019** [comment]
Only tested the form changes not tested visit scheduled

**Comment by Dinesh2019** [comment]
@adamsanadi6 @AnjaliBhagabati do we need to move the card back for developing the visit scheduling or we are creating the new card for the visit scheduling

**Comment by Dinesh2019** [comment]
@adamsanadi6 @AnjaliBhagabati do we need to move the card back for developing the visit scheduling or we are creating the new card for the visit scheduling

**Comment by AnjaliBhagabati** [comment]
@Dinesh2019 we have a separate card for visit schedule. You don't need to move this card back
