### ISSUE TITLE
APF | QRT PW Form Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#157]
- [ ] Changes to be done in UAT
- [x] **Form Name:** QRT PW 
- [x] Form [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1255247919)
- [ ] The condition for scheduling QRT has now changed from the earlier conditions. Now QRT will be scheduled in three condition: 
1. Geographically High Risk Condition (this is list of Hard To Reach places) 
2. Clinically High Risk Condition (ORT will be schedule only for some Clinically High Risk conditions) and
3. Both (Geographically + Clinically High Risk)
 
- [ ] **Visit Schedule:** **[Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=4:4)**
- [ ] **On any edit made** in this form as well as the subject registration form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
- [ ] **On cancellation made** in this form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
- [ ] **If reason of cancellation** is Delivery/Abortion, Death,Migrated to other geography then no forward visit schedule.
- [ ] **On Overschedule,** don't allow user to enter data.
Need to add a validation message in the 1st question and the 1st mandatory question stating 
**"Overdue forms cannot be filled, please cancel this form so that next due form can be scheduled"**

- [x] Changes highlighted in green are new questions to be added. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1255247919)
- [ ] **To be checked with Tech Lead**: If in future any data migration is required from the old data related to this form, can that be done after the changes are done from the DB? **Reply** :: Since we are making changes only on UAT, the migration script can be written later on as well.

**Out of scope for this card :** High Risk: (Geographical and Clinically High Risk) both conditions should be applicable here and we need to show that in the form summary. [Geographical High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/159) [Clinically High Risk](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/158)

**Process Flow (Just for reference):** https://drive.google.com/drive/search?q=APF

**Comment by nupoorkhandelwal** [comment]
Will have to update the logic for clinically High risk in the ANC forms first and then we can pick this card.

**Comment by pkundu** [comment]
@nupoorkhandelwal lets move this card forward based on current high risk conditions like we discussed on Friday. When the risk conditions are updated, this will need testing again
