### ISSUE TITLE
APF | Clinically High Risk Condition PW

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#158]
- [x] The logic of Clinically High Risk conditions has changed from the existing conditions. Existing 7 conditions are there. Now there are going to be 13 conditions. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=934737801)
- [x] Of the 13 Clinically High Risk conditions, for 6 conditions (the one's highlighted in green in the form) **a question will be asked "Whether a Health Facility visit is required or not?(as advised by ANM)" and if answered as " YES", QRT needs to be scheduled.** 
- [x] Or **"Is there a medical facility intervention required for treatment?'  if answered as " YES", QRT needs to be scheduled** 
- [x] Changes to be done in UAT
- [x] Clinically high risk should be part of the form summary.

## Tech tasks

- [x] Update existing rule with the new conditions in **Pregnancy Enrolment and ANC form**.
- [x] Remove the earlier conditions whichever are not applicable as per new requirements.
- [x] Program Summary : Update program summary rule to hide High risk condition once delivery form is filled

**Comment by Dinesh2019** [comment]
- [ ] Tested the high-risk condition not tested the sync logic
- [ ] @AnjaliBhagabati and @adamsanadi6 having the suggestion of Obstetric History of miscarriage, stillbirth, etc. Instead of showing the entire sentence can we have it as a selected option only for eg: if the option is selected as stillbirth then in summary we can have it as Obstetric History of Stillbirth

**Comment by AnjaliBhagabati** [comment]
@Dinesh2019 for visit schedule which is pending separate card is created

**Comment by Dinesh2019** [comment]
QA References dev and BA can ignore :

- [ ] Tested the clinical not tested with sync 
- [ ] Tested with edit and new data
