### ISSUE TITLE
APF | Geographical High Risk Condition

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#159]
Changes to be done in UAT

**Current behavior:** Currently in app, Geographical high risk is determined on the basis 'Yes' given in the 'Pregnancy geographically high risk' question in ANC form.
**Change Requested:** Geographically high risk condition should be considered if the village comes under 'Geographically hard to reach village' list in location master data file and 'Is there a medical facillity intervention required for treatment?' is 'Yes' in [ANC form](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=836611880). 

- [x] Create a location attribute form with following fields - [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1742317218)

- [x] Existing question 'Pregnancy geographical high risk' question should be changed to auto populate field instead of single select question where if village is 'Geographical hard to reach village' then Yes should be populated.

- [x] 'Is there a medical facility intervention required for treatment?' question in ANC form should be displayed only if village is a 'Geographically hard to reach village'. 

[Geographical hard to reach village list](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=644314954&range=H:H)

---
Need to change code after : avniproject/avni-models#51

**Comment by vedfordev** [comment]
@nupoorkhandelwal / @AnjaliBhagabati  I tried with one location for **Geographically hard to reach village** via uploading attached csv for location **Bujbanga**. It is working fine. Currently model's method is not available for **Addresslevel** So we need to change code after completion of avni-model's mentioned card.

**Comment by Dinesh2019** [comment]
Tested only for this Bujbanga location for high risk Geographically and also tested for non high risk location

Refrences screenshot for further reference :

<img width="478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d610fff1f8db168d269219a7ae4ddb4fe86b2785/Screenshot%202024-04-02%20at%208.39.46%E2%80%AFPM.png" alt="Screenshot 2024-04-02 at 8.39.46 PM.png" />
