### ISSUE TITLE
[APF] Misc changes 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#16]
- [x] Add highlighted fields in yellow in Household registration -
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1229007889

- [x] Add highlighted fields in yellow in Individual registration -
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=406612277

- [x] Child enrolment 
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=23097314

- [x] Program eligibility check for children to be 0 till 6 years

- [x] Update days in ANC visit scheduling -
"ANC 1 - LMP+ 60,
ANC 2 - LMP+170,
ANC 3 - LMP+260,
ANC 4 - LMP+ 270"
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1422128164&range=B15

**Comment by AchalaBelokar** [comment]
Individual Registration Beneficiary ID is missing.

**Comment by AchalaBelokar** [comment]
Child Enrolment :
when Child's age is 25 months Is the child Breast feed til 2 years this question should appear. but currently, it is not working.

**Comment by Gojo-Taqi** [comment]
There was an issue in the identifiers which has now been updated via query with the help of Nupoor.
