### ISSUE TITLE
APF | Offline dashboard | Lactating Mother card

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#165]
- [ ] A new offline dashboard card for 'Lactating mothers' needs to be added under Pregnancy
- [ ] Logic and Requirement Details available in the [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=186279590&range=11:11)

**Comment by Dinesh2019** [comment]
@vedfordev 

- [ ] From the date of delivery to 6 month but I think we can only calculating the months not with the date.
- [ ] we need exclude the still birth in the count
