### ISSUE TITLE
APF | Child Home Visit Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#168]
All changes to be done in UAT first.

- [x] Existing form 'QRT Child Followup' should be renamed to 'Child Home Visit'. This has to be done for encounter type also.
- [x] Questions provided in form link need to be added to Child Home Visit form. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1692043224)

- [ ]  [Process Flow](https://drive.google.com/file/d/15vBrsfJZ16ggdGtlh3iaVKJkY5_O22Za/view?usp=sharing) (Just for reference)

**Out of scope:** Child home visit scheduling is not part of this card. Visit scheduling card [link](url)

Note: Changing encounter type name will lead to change in existing ETL table names.
All child related reports on Superset will have to be taken care off.

**Comment by Dinesh2019** [comment]
- [ ] Weight and height should be auto-populated from the latest growth child follow-up 
- [ ] Weight and height should not be mandatory

**Comment by Dinesh2019** [comment]
- [ ] Weight and height should be auto-populated from the latest growth monitoring currently we are taking for the latest encounter for eg: if the QRT Sam is filled it is taken from sam instead of growth monitoring

**Comment by nupoorkhandelwal** [comment]
"Any other medical complication" this field is being updated from single select to multi select. Need to thoroughly test if it is breaking any existing encounters. If yes, then the existing observations will have to be taken care of.
