### ISSUE TITLE
[APF] QRT form visit scheduling

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#17]
- [x] QRT SAM Child
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1422128164&range=A6

- [x] QRT child Followup
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1422128164&range=A7:A8

- [x] NRC
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1422128164&range=A9

- [x] QRT PW
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1422128164&range=A18

- [x] QRT PW Followup
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1422128164&range=A19

**Comment by AchalaBelokar** [comment]
When we enroll a 2-year Child  Child follow-up visit is scheduling 7th sept 2020. which is wrong

**Comment by Gojo-Taqi** [comment]
There was an issue in setting earliest visit date time, which is fixed now
