### ISSUE TITLE
APF | Child:  Visit Schedule for Child Home Visit

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#174]
Changes to be done in UAT first.

Visit Schedule: [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=15:17)

Visit Schedule Changes:

- [x] Child Home visit form should be scheduled 15 days from the date of QRT Child from or Growth monitoring form submission.
- [x] in case of SAM, Child visit will be scheduled post QRT form submission at an interval of 15 days for total 4 times. (Shouldn't be scheduled 4 times immediately, only one subsequent visit should be scheduled on basis of previous child home visit submission or cancellation)
- [x] In case of MAM or GF2, child visit will be scheduled post QRT form submission at an interval of 15 days for total 4 times if taken to medical facility=yes in QRT form. if taken to medical facility= no then schedule child home visit only once.
- [x] In case of GF1, child visit will be scheduled (only 1 time) on the submission of Growth monitoring form. 

**Note:** For better understanding of condition to schedule the child home visit, please refer to the [Nutrition status & Growth Faltering condition for Child Home Visit](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=850324743)

**Comment by Dinesh2019** [comment]
- [ ] If the growth monitoring is GF1 then a home visit needs to be scheduled as per the requirement but it is not scheduling

**Comment by Dinesh2019** [comment]
@Nupoor As per the discussion with Parth, we will only schedule visits for growth monitoring if all status indicators are normal and none  No other visits should be scheduled in such cases.
