### ISSUE TITLE
APF | Pregnancy Visit Schedule for PW Home Visit

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#175]
- [x] **Visit Scheduling:** This form will be scheduled for two different High Risk Scenarios.

1. High Risk Condition for which **[QRT has been Scheduled](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=7:7)**
In this scenario, PW Home visit will be scheduled for 4 times at a frequency of 

- From the date when the QRT encounter date + 15days
- From the date when the QRT encounter date + 30days
- From the date when the QRT encounter date + 45days
- From the date when the QRT encounter date + 60days

2. High Risk Condition for which ** [No QRT has been Scheduled](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=6:6)

 In this scenario the schedule logic will be dynamic and will be based on ANC evaluation. To be scheduled on 1st of next month from ANC and will be dynamic and based on monthly ANC evaluation

- [x] **On any edit made** in this form as well as the subject registration form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
- [x] **On cancellation made** in this form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
- [x] **If reason of cancellation** is Delivery/Abortion, Death, Migrated to other geography then no forward visit schedule.
- [x] **On Overschedule,** don't allow user to enter data.
Need to add a validation message in the 1st question and the 1st mandatory question stating
"Overdue forms cannot be filled, please cancel this form so that next due form can be scheduled"

- [ ] **Note: Changing encounter type name will lead to change in existing ETL table names.
All Pregnancy related reports on Superset will have to be taken care off.**

- [ ] **Note (Just for reference. Out of scope for this card) :** High Risk: (Geographical and Clinically High Risk) both conditions should be applicable here and we need to show that in the form summary. Geographical High Risk Clinically High Risk
- [ ] **Process Flow (Just for reference):** https://drive.google.com/drive/search?q=APF

- [ ] **Form Development Card** (Just for reference):https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/156

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal if we edit the ANC when the PW home visit should not be scheduled but it is scheduled now can we fix this

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 can you check now?

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 can you check now?
