### ISSUE TITLE
APF | Pregnancy Visit Schedule for QRT PW

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#176]
- [x] Of the [13 Clinically High Risk conditions](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=934737801), for 6 conditions (the one's highlighted in green in the form) a question will be asked "Did the ANM recommend for a medical facility intervention? (for any reason)" and if answered as " YES", QRT needs to be scheduled.
- [x] **Visit Schedule: **[Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=5:5)**
 - [x] **On any edit made** in this form as well as the subject registration form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
 - [x] **On cancellation made** in this form, the same visit should not be scheduled again. The next visit in the said frequency should get scheduled
 - [x] **If reason of cancellation** is Delivery/Abortion, Death,Migrated to other geography then no forward visit schedule.
 - [x] **On Overschedule,** don't allow user to enter data.
Need to add a validation message in the 1st question and the 1st mandatory question stating
"Overdue forms cannot be filled, please cancel this form so that next due form can be scheduled"

- [ ] **Process Flow** (Just for reference): https://drive.google.com/drive/search?q=APF

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati @nupoorkhandelwal 
Do we need to include a cancel form for the cancellation process, or is it sufficient as it currently stands without one?

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 Added the cancel related fields in QRT PW cancel form, no visit will be scheduled on the cancellation
