### ISSUE TITLE
[APF] UAT Demo feedback changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#18]
- [x] z-score values not reflecting in Child program summary

- [x] Pregnancy enrolment - High Risk not getting auto selected

- [x] Review all date validations-
Date of referral/admission/discharge cannot be berfore child's dob
Date of referral shouldn't be in future
Date of admissions/ Discharge shouldn't be in future
Date of Discharge cannot be before date of admission

- [x] Offline Dashboard not reflecting count of SAM children

**Comment by AchalaBelokar** [comment]
- [ ] The date of referral/admission/discharge cannot be before the child's dob. Validation must be needed.

**Comment by Gojo-Taqi** [comment]
@AchalaBelokar where are the validations missing, the concepts are being used in multiple places, it would save both of us some time if you remember where its required

**Comment by Gojo-Taqi** [comment]
It was a small issue, which is fixed now
