### ISSUE TITLE
APF | Offline Dashboard | QRT Child Followup cards

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#181]
Changes to be done in UAT.

**- Remove the following offline dashboard cards as respective forms are removed as part pf phase-2 exercise:**
- [ ] Overdue for QRT child followup
- [ ] Due visits for QRT child followup

**Note:** as part of this card only the offline dashboard card mentioned above are to be removed, there will be no impact on the other cards due to this change.

**Comment by Dinesh2019** [comment]
QA References no need for dev and BA actions : 

<img width="372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemRRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e40a0084ecc39a39884e33440e4e7db69d8f862/Screenshot%202024-04-11%20at%2011.45.13%E2%80%AFAM.png" alt="Screenshot 2024-04-11 at 11.45.13 AM.png" />
