### ISSUE TITLE
APF | Location Attribute Form Upload For All Locations

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#182]
Changes to be done in UAT first.

- [x] As part of this card, location attribute form should be uploaded with the all the locations (covering details of PPK village, PVTG village, Sampurna Village, Geographically hard to reach village).

Refer to the location village sheet attached [here](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=644314954) with list of PPK village, PVTG village, Sampurna Village, Geographically hard to reach village.

**Comment by Dinesh2019** [comment]
When we create the individual under the location of Geographically the individual is not consider as high risk
