### ISSUE TITLE
{APF Dashboard Report} : Sector-wise distribution of women availed benefits under MAMTA

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#185]
- [x] Make the report in the pre-release.
- [x] Mamata Report is a new report to be added for the client in superset. It is being used to track the benefits availded by pregnant women under the Mamata scheme.
- [x] An aggregate report and linelist depicting the complete details of the pregnant women enrolled in Mamata should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data on the basis of the following: 
1. Gender
2. Type of Village
3. Project/Block( By Default)
4. Child Status (SAM, MAM, Normal, GF1, GF2)
5. SUW
6. High Risk Condition
7. Date Range
- [x] [ Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=1537410561)

**Comment by vedfordev** [comment]
Currently high risk condition filter not working properly. Moving card to on hold. Try to resolve with help of @petmongrels .

**Comment by vedfordev** [comment]
Link of Dashboard [Link](https://reporting-superset.avniproject.org/superset/dashboard/92/?native_filters_key=EG5MBLmrd7Z2mgqdrvQcEiyVOqz7kcqTITLILKJ6rM7eQRd76rvsT6EiwhYxOh__)

**Comment by Dinesh2019** [comment]
Refrences no need of action for dev and BA:

No of PW received 2nd installment - ignored this column
Gender - not needed 
Child Status (SAM, MAM, Normal, GF1, GF2) - not needed
SUW - not needed
Date Range - not needed

**Comment by sachsk** [comment]
@vedfordev enrolment date filter is missing

**Comment by Dinesh2019** [comment]
- [ ] We have the count mismatch between aggregrate and line list
- [ ]  We are getting the time out error when we apply the line-list filter only 
- [ ]  When we apply the high risk conditions, it displays the warning system in the aggregrate and line list.
