### ISSUE TITLE
[APF Dashboard Report] : Delivery Details

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#188]
- [x] Make the report in the pre-release.
- [x] Delivery Details Report is a new report to be added for the client in superset. It is being used to track the delivery of pregnant women.
- [x] An aggregate report and linelist depicting the complete details of the child birth and delivery outcome should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following: 
1. High Risk Condition
2. Type of mother (Normal/High Risk)
3. Type of Village 
4. Date Range
5. Project/Block(By Default)
- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=1986510818)

**Comment by adamsanadi6** [comment]
Dashboard [link](https://reporting-superset.avniproject.org/superset/dashboard/120)

**Comment by sachsk** [comment]
@adamsanadi6 

- [ ] Don't use * in the select queries as it cost more
- [ ] If you want to take only scheduled delivery enc then add the earliest_visit notnull check

**Comment by adamsanadi6** [comment]
@sachsk 
I have removed the *.
I am just using encounter_date_time because we need to display the number of women whose deliveries are complete.
