### ISSUE TITLE
{APF Dashboard Report} : Sector-wise distribution of trimester of Pregnant Women Registration 

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#189]
- [x] Make the report in the pre-release.
- [x] The pregnant women registration report is a new report to be added for the client in superset. It is being used to track the registration of a pregnant woman.
- [x] The report needs to have a count of various birth outcomes, in a bar graph.
- [x] An aggregate report and linelist depicting the complete details of the pregnant women should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following: 
1. Type of Village
2. Project/Block (By Default)
3. Age Group (Check if we can add from and to months for age group, if not, Jagdish will share categorisation.)
4. Date Range
- [x] [[Link to the analysis]](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=944201335)

**Comment by adamsanadi6** [comment]
@Dinesh2019 I'm moving this card back to 'In Progress' lane because there are some changes that need to be made:
1. Type of Village
2. Block filter

**Comment by adamsanadi6** [comment]
@Dinesh2019 and @kameshbhariya the code review has been done by Vivek. Dinesh, you can proceed with the QA on the report.

**Comment by Dinesh2019** [comment]
@kameshbhariya You have recently added the description to the requirement, which was not there at the time of the dev box. Is the description part of this card, or will you be creating a new card to add it?

**Comment by kameshbhariya** [comment]
@Dinesh2019 Yes, description will be added later, and a new card will be created for it.
