### ISSUE TITLE
Move To PROD | APF | Superset Report Changes | Pregnant Women Info 

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#190]
**Changes to be done in Pre-release**

- The following changes are to be made as part of this card in Pregnant Women Info (AWC) & (Village)
- [x] **Remove column:** 'Red Flag (Geographically)'
- [x]  Change 'Red flag (Clinically) column name to  "Clinically high risk"
- [x] The Pregnancy Women Info report should exclude women whose delivery forms have already been submitted.

## Tech Note -
1 . Decision concepts under enrolment were updated later to have the latest values of "Clinically high risk", please regenerate ETL to get these column values.
2. Since we have not done any data migration and this field is being added now, there will be little or no data. So verify it properly.

**Comment by vedfordev** [comment]
@pkundu Removing High priority as this is old report and we not moved changes to prod. So we have to work after that.

**Comment by adamsanadi6** [comment]
@Parth7223 and @Dinesh2019 
Dashboard links:
1. [[APFODISHA Prerelease] Pregnancy Women Info (Village)](https://reporting-superset.avniproject.org/superset/dashboard/97)
2. [[APFODISHA] Pregnancy Women Info (Village)](https://reporting-superset.avniproject.org/superset/dashboard/69)

**Comment by AnjaliBhagabati** [comment]
@adamsanadi6 @Dinesh2019 

- [ ] As discussed, deleting the old report 
- [ ] [old report link](https://reporting-superset.avniproject.org/superset/explore/?form_data_key=s9OUNRPybpr2GcE7114SxoLro8SPggq3__th5dKrQ1sOZeW_p-BEH3jtcFWQUiav&slice_id=195)
