### ISSUE TITLE
APF | Superset Report Changes | Remove Pregnancy Reports

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#191]
**Changes to be done in Pre-release**

- As part of this activity, the following reports need to be removed.
- [x] QRT - PW Report
- [x] QRT - PW Report (AWC wise)
- [x] QRT-PW Severe Anemic Report

**Comment by adamsanadi6** [comment]
Charts links:
1. [[APFODISHA] QRT-PW Report (AWC wise)](https://reporting-superset.avniproject.org/superset/explore/?form_data_key=YL1cyN7jEUxbiFJv0SQ4nbb-7_S8MX8kbqjL3YTI8Z-kcntnLGRWjoL4GrrbMkgK&slice_id=23)
