### ISSUE TITLE
APF | Superset Report Changes | ANC

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#192]
**Changes to be done in Pre-release.**

- The following changes are to be made as part of this card.

- [x] **Add column** 'HB value' to stamp the value provided in the ANC form. (**Data source**: question 'HB test (value)' from ANC form)
- [x] The Pregnancy Women Info report should **exclude data of lactating women,** as the delivery form has already been submitted.
- [x] **Remove the Following columns** from the report:
        1. Severe Anemic
        2. Moderately Anemic
        3. Mildly Anemic
        4. Red Flag (Geographically)

**Comment by vedfordev** [comment]
Report link of prerelease : [[APFODISHA] ANC Report (Updated) [prerelease]](https://reporting-superset.avniproject.org/superset/dashboard/99/?native_filters_key=rd6pMwezG4QxbE5wV08MZrmrdBRskHt9DbwYq7h41AHwKvgF1GEU6L2h11zGSFfL)

**Comment by Dinesh2019** [comment]
@Parth7223 @AnjaliBhagabati @adamsanadi6 @vedfordev @pkundu since ETL is failing in pre-release for apfodisha
showing unexpected error.so moving the card to on hold once it is fixed will continue the testing 

https://avni.freshdesk.com/a/tickets/3856
