### ISSUE TITLE
APF Dashboard Reports | Child Timeline

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#196]
**Changes are to be made in pre-release.**

The following reports are to be created as part of this card

- [ ] Child Timeline - Dashboard
- [ ] Child Timeline - Linelist

[Link](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=1009368543)
Note: for child mother linking check dob and delivery date max duration should be 1 month

**Comment by sachsk** [comment]
link: https://reporting-superset.avniproject.org/superset/dashboard/128/?native_filters_key=D59g5FkI4JC8dVtMxfjUDBRcwq5OvNHIb5XrV_SzThzX1LqjR9a-HHyNonJX2MlZ

**Comment by vedfordev** [comment]
## Review Comments :
@sachsk Please look into this
1. By default it shows sukruli sector. if we remove it filter it shows error.
<img width="1231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9vQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd2d16558c34449e7769d467c4999d60cd07fc81/Screenshot%202024-07-02%20at%204.27.31%20PM.png" alt="Screenshot 2024-07-02 at 4.27.31 PM.png" />
2. **Severely Underweight (Child) (Yes/No)** and **Type of village** filter is missing
3. in query unable to understand below condition
```sql
         join apfodisha.individual child
              on child.id = ir.individual_b_id and delivery."Date of delivery" - child.date_of_birth < 30 and
                 delivery."Date of delivery" - child.date_of_birth > -30 and child.is_voided = false

```

**Comment by Dinesh2019** [comment]
- [ ]  Type of village  filter is missing
- [ ] Child age range filter is missing
- [ ] Getting the error if we remove the filter 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--420037047693df1294708fd60b5ead7550688e7f/Screenshot%202024-07-15%20at%205.06.34%E2%80%AFPM.png" alt="Screenshot 2024-07-15 at 5.06.34 PM.png" />

**Comment by Dinesh2019** [comment]
As discussed with Sachin, a Child age range filter is not required.
