### ISSUE TITLE
APF Dashboard Report | Child Entitlement

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#197]
**Changes are to be made in pre-release.**

The following reports are to be created as part of this card.

- [x] Child Entitlement - Dashboard
- [x] Child Entitlement - Line list

[Link](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=897745995)

**Comment by adamsanadi6** [comment]
Dashboard link: [[APFODISHA Prerelease] Child Entitlementhttps://reporting-superset.avniproject.org/superset/dashboard/107]()

**Comment by adamsanadi6** [comment]
@Dinesh2019 and @kameshbhariya the code review has been done by Vivek. Dinesh, you can proceed with the QA on the report.
