### ISSUE TITLE
{APF Dashboard Report} : Household Entitlement

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#198]
- [x] Make the report in the pre-release.
- [x] Household Entitlement Reports are a new report to be added for the client in superset. It is being used to track the social security entitlements of households.
- [x] The report needs to have a total count of the social security entitlements of households, in a bar graph.
- [x] An aggregate report and linelist depicting the complete details of the household should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following: 1. Project/Block 2. Sector
- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=68539179)

**Comment by adamsanadi6** [comment]
@vedfordev Please do the code review
select 
	h.id as "House Id",
	h.registration_date as "Registration date",
	h.first_name as "Household name",
	h."Social security entitlements" as "Entitlements",
	unnest(string_to_array(h."Social security entitlements", ', ')) AS "Entitlement",
	h."Number of members in the family" as "Number of family members",
	awc."Sector",
	village."Block"
from 
	apfodisha.household h
left join apfodisha.address awc on
	awc.uuid = h."AWC Name" 
	and awc.is_voided = false
left join apfodisha.address village on
	village.id = h.address_id 
	and village.is_voided = false
where 
	h.is_voided = false

**Comment by vedfordev** [comment]
## Rework:
---
As discussed with @kameshbhariya Added village type filter,registration date filter and entitlement filter. And no need to create separate linelist

**Comment by Dinesh2019** [comment]
- [ ] Exit status is missing in the column 
- [ ] Type of village is missing in the line list column.

**Comment by vedfordev** [comment]
@Dinesh2019 Exit will not require as this is about subject only no program involve. @kameshbhariya remove exit status

**Comment by kameshbhariya** [comment]
@vedfordev @Dinesh2019 Removed exit status from this report.
