### ISSUE TITLE
[APF Dashboard Report] : Delivery Location

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#200]
- [x] Make the report in the pre-release.
- [x] Delivery location reports are a new report to be added for the client in superset. It is being used to track the delivery location of pregnant women.
- [x] The report needs to have a total count of the children delivered at different places, in a stacked bar graph.
- [x] An aggregate report and linelist depicting the complete details of the delivery place should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following: 
1. High Risk Condition
2. Type of mother (Normal/ High Risk)
3. Type of Village 
4. Date Range
5. Project/Block (By Default)
6. Age Group
7. Date Range
- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=228731731)

**Comment by vedfordev** [comment]
Used same dataset as #188. So filter will apply accordingly
