### ISSUE TITLE
{APF Dashboard Report} : ANC Details

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#201]
- [x] Make the report in the pre-release.
- [x] ANC Detail Report is a new report to be added for the client in superset. It is being used to track the health of pregnant women.
- [x] The report needs to have a count of all the tests made for pregnant women in a bar graph.
- [x] An aggregate report and linelist depicting the complete details of the delivery place should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following: 
1. Type of Village, Block( By Default)
2. Project/Block (By default)
3. Age group
4. High risk condition
5. Date Range 
6. Table Columns (Registered, BP Measured, Abdominal Observation, Weight, Sugar Test, HB Test)

- [x]  [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=160445132)

- [x] Add a stacked bar graph chart for Abdominal observation, Weight, Sugar test, HB test and Urine.

**Comment by vedfordev** [comment]
**Dashboard:** [Link](https://reporting-superset.avniproject.org/superset/dashboard/119/?native_filters_key=0TFKR52SIKGUk--ubihu3J5UsYWETE1kWmUJHhber5PlmhqtzNvrDK5UsLnkI01w)

**Comment by sachsk** [comment]
@vedfordev 

- [ ] Use left join for the group and household joining.

**Comment by vedfordev** [comment]
@sachsk 
As anc and sector at houshold level I provided inner join

**Comment by Dinesh2019** [comment]
[] We have the count mismatch for linelist excel downloaded and the aggregrate.

**Comment by kameshbhariya** [comment]
@vedfordev @Dinesh2019 Please check the last point added for this report.
