### ISSUE TITLE
[APF Dashboard Report] : EDD vs Actual Delivery

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#202]
- [ ] Make the report in the pre-release.
- [ ] EDD vs Actual Delivery report is a new report to be added for the client in superset. It is being used to track the number of expected and actual deliveries this month.
- [ ] An aggregate report and linelist depicting the complete details of the pregnant women should be displayed. The detailed requirements are available in the analysis link shared below.
- [ ] It will have filters for filtering the data based on the following: 
1. Type of Village
2. Project/Block (By default)
3. Age group
4. High risk condition
5. Block (By Default)
6. Type of mother (Normal/High Risk)
7. Date Range
- [ ] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=2034310207)

**Comment by nupoorkhandelwal** [comment]
Dashboard link - [here](https://reporting-superset.avniproject.org/superset/dashboard/121/?form_data_key=Z25PPnjcRNFGnZgyE-Qybv_qaRMkmnIsb8S6212YxOoxJn7zQy8zhgLu1taqFRqI&slice_id=273&native_filters_key=E0CwF_8BDj3DRVS7Zdh0Ksl0KeLQkJx6xREU5pLKNXBDlEpB20tH4TdtVyuoI7kN)

**Comment by nupoorkhandelwal** [comment]
Dashboard link - [here](https://reporting-superset.avniproject.org/superset/dashboard/121/?form_data_key=Z25PPnjcRNFGnZgyE-Qybv_qaRMkmnIsb8S6212YxOoxJn7zQy8zhgLu1taqFRqI&slice_id=273&native_filters_key=E0CwF_8BDj3DRVS7Zdh0Ksl0KeLQkJx6xREU5pLKNXBDlEpB20tH4TdtVyuoI7kN)

**Comment by sachsk** [comment]
@nupoorkhandelwal 

- [ ] there are multiple delivery forms for single enrolment is present in the DB so you have to take only schedule and latest encounter for that create CTE and take latest enc.
- [ ] use enl id for count
