### ISSUE TITLE
[APF Dashboard Report] : ANC Done by PW

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#204]
- [ ] Make the report in the pre-release.
- [ ] ANC Done by pregnant women report is a new report to be added for the client in superset. It is being used to track the ANC done by pregnant women.
- [ ] The report needs to have a count of all the tests made for pregnant women, in a bar graph.
- [ ] An aggregate report and linelist depicting the complete details of the pregnant women should be displayed. The detailed requirements are available in the analysis link shared below.
- [ ] It will have filters for filtering the data based on the following:  
1. Type of Village 
2. Project/Block (By default) 
3. Age group 
4. High Risk condition 
5. Type of mother (Normal/High Risk) 
6. Date Range
- [ ] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=1420657493)

**Comment by sachsk** [comment]
@nupoorkhandelwal 

- [ ] Dont use distinct in count
- [ ] Filter out encounters in the CTE itself which will reduce the significant cost of query

**Comment by sachsk** [comment]
@nupoorkhandelwal please add date filter in cte

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal we are adding the filter the report takes more time to load 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0c664e62b20450ea2bf22fd3a89a2eeb3f099bf/Screen%20Recording%202024-06-21%20at%207.30.51%E2%80%AFPM.mov

**Comment by Dinesh2019** [comment]
Still we are getting the perform issue report takes more than 20 minutes .

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43afd2b119ad3efa69a7b569189823171087dcb8/Screen%20Recording%202024-06-27%20at%206.06.14%E2%80%AFPM.mov

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 it takes 20-30 seconds  and not 20 minutes !!
