### ISSUE TITLE
{APF Dashboard Report} : PW Home Visit Details

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#205]
- [x] Make the report in the pre-release.
- [x] PW Home Visit Details Report is a new report to be added for the client in superset. It is being used to track the scheduled visits.
- [x] The report needs to have a count of all the visits scheduled and visits done, in a bar graph.
- [x] An aggregate report and linelist depicting the complete details of the pregnant women visits should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following:   
1. Type of Village
2. Project/Block (By default) 
3. Age group 
4. High Risk condition
5. Date Range
- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=2132065293)

**Comment by vedfordev** [comment]
Link : [Dashboard](https://reporting-superset.avniproject.org/superset/dashboard/109/?native_filters_key=JCboccs-qZgYC8O8A-NHaWierSGMnCVGt6tgQ4y8k_D0SVzF_Ont_NT2CLiZKKM_)

**Comment by Dinesh2019** [comment]
- [ ] Age we need to mention it is represented in years or months.
