### ISSUE TITLE
{APF Dashboard Report} : PNC Visit Details

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#206]
- [x] Make the report in the pre-release.
- [x] PNC Visit Details Report is a new report to be added for the client in superset. It is being used to track the scheduled PNC visits.
- [x] The report needs to have a count of all the PNC visits done in a bar graph.
- [x] An aggregate report and linelist depicting the complete details of the pregnant women's visits should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following:  
1. Type of Village 
2. Project/Block (By default) 
3. Age group 
4. High risk condition 
5. Type of mother (Normal/High Risk) 
6. Date Range
7. Add sector filter to chart only 
- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=399235472)

**Comment by vedfordev** [comment]
Link : [Dashboard](https://reporting-superset.avniproject.org/superset/dashboard/112/?native_filters_key=SzEyIQu04IRrSfRPo1EqjIKvGPa1oZVLkEEaPDe5rkPBAW1IkPwaFV2migUJAzHt)

**Comment by vedfordev** [comment]
@kameshbhariya remove **Number of PW Home Visits** as aggregate and other are related to pnc only
