### ISSUE TITLE
[APF Dashboard Report] : PW QRT

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#207]
- [x] Make the report in the pre-release.
- [x] PW QRT Details Report is a new report to be added for the client in superset. It is being used to track the scheduled QRT visits.
- [x] The report needs to have a count of all the scheduled PW QRT and visits done, in a bar graph.
- [x] An aggregate report and linelist depicting the complete details of the pregnant women's visits should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following:  
1. Type of Village 
2. Project/Block (By default) 
3. Age group  
4. High risk condition 
5. Type of mother (Normal/High Risk) 
6. Date Range
- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=414805569)

**Comment by vedfordev** [comment]
Dashboard Link : [Link](https://reporting-superset.avniproject.org/superset/dashboard/105/)
