### ISSUE TITLE
[APF] Post User training feedback 2.0

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#21]
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=2054344435

- [x] **Pregnancy enrolment** - Move Q. Bank account opened before Q. Mamata scheme amount received. And Q. Mamata scheme amount received should show only when  Q. Bank account opened = Yes.

- [x] **ANC & PNC** - Make IFA consumed and Calcium consumed fields as mandatory in both forms.

- [x] **ANC & PNC** - Replace THR to IFA in all concepts like "Did you received additional THR"

- [x] **ANC & PNC** - Add encounter eligibility check and hide these visit from unplanned visits

- [x] **QRT PW form** - make field "Referral advice" as multi select.

- [x] **Delivery form** - Add validation on "Date of delivery" to not except future dates

- [x] **Misc** - Add validation on all the dates in the form, not to except future dates.(Exclude QRT followup date field)

- [x] **Delivery form** - Ask Q. "Birth weight" only when "Birth outcome" = "Normal delivery"

- [x] **ANC** - Update visit schedule logic to have visit number in the visit visit name , eg. ANC 1, ANC 2 and so on (Similar to PNC)

- [x] **HH registration** - Household Name change to Household Head Name (Do it via translation)

- [x] **NRC Cancel form** - Update
 Cancel reason - Death, migrated to other geography, other

- [x] **Village profile**- Q. Time taken to reach nearest Maa gruha- make it non-mandatory

- [x] **Pregnancy enrolment** - Remove validations from Gravida and Alive children

- [x] **PNC** - Remove skip logic - Did you receive THR from AWC last month? and 
Did you receive egg from AWC last month?

- [x] AWC Profile - Change to "Pradhan Mantri Surakshit Matritiva Abhiyan (PMSMA)  (antenatal care, 4 times ultrasound)"

- [x] PNC - Update Calcium received (=<200) to Calcium received (=<400)

- [x] Individual registration - Q. Is the mother enrolled for PMMVY, replace  PMMVY to MAMATA

- [x] **AWC Profile** - Replace "Functional weighing Machine" to "Functional Digital Weighing Machine"

- [x] **AWC Profile** - Replace "Functional height measuring tape" to "Infantometer"

**Comment by AchalaBelokar** [comment]
HH registration - Household Name change to Household Head Name (Do it via translation) not showing

**Comment by AchalaBelokar** [comment]
HH registration - Household Name change to Household Head Name (Do it via translation) not showing.

 NRC Cancel form - Update
