### ISSUE TITLE
[APF Odisha Dashboard Report] | SAM Child

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#210]
**Changes are to be made in pre-release.**

The following reports are to be created as part of this card.

- [ ] SAM Child - Dashboard
- [ ] SAM Child - Line list

[Link](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=1250642625)

**Comment by vedfordev** [comment]
@kameshbhariya this report have same column as per card #238. only column is extra. So I added that column. Please check it and let me know. [Dashboard Link](https://reporting-superset.avniproject.org/superset/dashboard/104/?native_filters_key=oi0Ovdo_BnE-JA83qaQ2cowGAJoI0M7NAqnlK3oBwlcRsq3Gi2lGzGmBW0FcxRGP). I suggest you to merge with that report and close this card. 


 cc : @sachsk @nupoorkhandelwal

**Comment by sachsk** [comment]
putting this card on hold refer comments from https://github.com/avniproject/apfodishanutrition/issues/238

**Comment by kameshbhariya** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25CQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43567d07f0f9baef79c08461a8b6e553f3a735eb/Screenshot%202024-07-09%20at%209.31.06%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 9.31.06 AM.png" />
Therefore closing it.
