### ISSUE TITLE
[APF Odisha Dashboard Report] | Child Home Visit

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#211]
**Changes are to be made in pre-release.**

The following reports are to be created as part of this card.

- [ ] Child Visit - Dashboard
- [ ] Child Visit - Line list

[Link](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=242810889)

**Comment by nupoorkhandelwal** [comment]
As discussed, with @pkundu @petmongrels @sachsk This report cannot be generated using Superset with standard SQL, so it will be put on hold until an alternative solution is found.

**Comment by kameshbhariya** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25CQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43567d07f0f9baef79c08461a8b6e553f3a735eb/Screenshot%202024-07-09%20at%209.31.06%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 9.31.06 AM.png" />
Therefore closing it.
