### ISSUE TITLE
APF Dashboard Report | SAM Child Referral

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#212]
**Changes to be done in Pre-release.**

The following reports are to be created as part of this card.

- [x] SAM Child Referral - Dashboard
- [x] SAM Child Referral - Line list

[Link](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=908086081)

**Comment by adamsanadi6** [comment]
Dashboard link: [[APFODISHA Prerelease] SAM Child Referral](https://reporting-superset.avniproject.org/superset/dashboard/113)

**Comment by Dinesh2019** [comment]
@sachsk dont we need the code review for this cards

**Comment by Dinesh2019** [comment]
- [ ] Age is month should be 0 to 60.
