### ISSUE TITLE
MOVE TO PROD | APF Superset Report Changes | Child Followup

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#213]
**Changes to be done in Pre-release**

The following changes are to be made as part of this card.

- [x] Change the report name to 'Growth Monitoring' from 'Child Followup'
- [x] **Add column** 'Growth Faltering' in the 'Growth Monitoring' report. (**Date source:** 'Growth faltering' from the 'growth monitoring' form, **values to be populated:** GF1, GF2, None)

**Comment by adamsanadi6** [comment]
@Parth7223 As discussed, this [[APFODISHA] Child Followup](https://reporting-superset.avniproject.org/superset/dashboard/72) is an existing report currently in production.
I have created a new dashboard report on prerelease [[APFODISHA Prerelease] Growth Monitoring](https://reporting-superset.avniproject.org/superset/dashboard/95) for better QA. Once QA is completed, we can implement the necessary changes to the existing report and delete the new one.

**Comment by AnjaliBhagabati** [comment]
@adamsanadi6  @Dinesh2019 Child Follow Up old Report Deleted : https://reporting-superset.avniproject.org/superset/explore/?form_data_key=J34p6bg6uag01ABKEYLRpZpbkqfL_ittZ-w4T8-w4A9hvampUw_qAABpFH9470PV&slice_id=189
