### ISSUE TITLE
{APF Dashboard}: Superset access control

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#218]
- [ ] As part of this card, user-specific access needs to be given to APF users for all the data sets used.
- [ ] [User Access](https://docs.google.com/spreadsheets/d/10FaC3smIaDJk1UgSKlqwdHRj-tfOYQsXlua_m48A4ok/edit?gid=0#gid=0) details as provided by Client.

**Comment by vedfordev** [comment]
@nupoorkhandelwal 
I have added details in #216. This card not require.
