### ISSUE TITLE
APF | App Changes | Vinay'sFeedback

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#223]
**Changes to be done in UAT**

**Pregnancy Enrollment:**
- [ ]  2 auto-populate questions to be added in the Pregnancy enrollment form: (i) Pregnancy Clinically High Risk (Yes/No) (ii) Pregnancy Geographically High risk (Yes/No) - This should be auto-populated on the basis of geographically and clinically high-risk conditions
- [ ] 2 fields to be added in the Pregnancy enrollment form summary: (i) Clinically High Risk (Yes/No) (ii) Geographically High risk (Yes/No) (Should be marked in red if yes)

**ANC Form**
- [ ] 1 field to be added in the ANC form summary: (i) Clinically High Risk (Yes/No) (Should be marked in red if yes)
- [ ] In ANC form if 'Pregnancy geographically high risk?' is 'yes' then should be marked in red. 
- [ ] Add a question in ANC form 'Pregnancy clinically high risk?' (Yes/No) - This response should be auto-populated on the basis of clinically high risk conditions (Mark in red if 'yes')

**Comment by nupoorkhandelwal** [comment]
@Parth7223 can you check once, all of these i have already incorporated immediately after call with Vinay. In case there is something still not done then we can pick up the card.

**Comment by vedfordev** [comment]
@Parth7223 Only put yes option as abnormal. Closing this card.
