### ISSUE TITLE
APF | Offline Dashboard | CMAM

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#224]
**Changes to be done in UAT**

- [x] Create an offline dashboard card 'Total children enrolled in CMAM program' in 'Child Dashboard'. 
**Data source:**
concept: Is the child enrolled in the CMAM program?
Logic: children for whom 'Is the child enrolled in the CMAM program?' = 'Yes' should be included in this offline dashboard card.

**Comment by Dinesh2019** [comment]
QA refrences no action needed for BA and Dev:

<img width="372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1986c19430133ee19c39f396b42fd854fbc64573/Screenshot%202024-04-23%20at%2011.46.54%E2%80%AFAM.png" alt="Screenshot 2024-04-23 at 11.46.54 AM.png" />
