### ISSUE TITLE
APF Dashboard Report | All Vaccination Report

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#225]
- [x] Make the report in the pre-release.
- [x] All Vaccination Report is a new report to be added for the client in superset. It is being used to track the child's vaccination.
- [x] The report needs to have a count of all the enrolled children and vaccinated children.
- [x] An aggregate report and linelist depicting the complete details of vaccinated children should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data.
- [ ] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=763351815)

**Comment by nupoorkhandelwal** [comment]
https://reporting-superset.avniproject.org/superset/dashboard/129/

**Comment by vedfordev** [comment]
@nupoorkhandelwal Add exit status and date filter

**Comment by Dinesh2019** [comment]
- [ ] When we download the CSV file we have a count mismatch between the aggregate and line list 
- [ ] and can we add the column Children Vaccinated is missing
