### ISSUE TITLE
APF Dashboard Report | Full Vs complete vaccination - New

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#227]
- [x] Make the report in the pre-release.
- [ ] Full vs. complete vaccination report is a new report to be added for the client in superset. It is being used to track the child's vaccination.
- [ ] The report needs to have a count of all the enrolled children, both fully vaccinated and completely vaccinated.
- [ ] An aggregate report and linelist depicting the complete details of vaccinated children should be displayed. The detailed requirements are available in the analysis link shared below.
- [ ] It will have filters for filtering the data.
- [ ] [[Link to the analysis]](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=1151975182)

NOTE: 
1. The list of vaccines for the 9th/10th months has to be maintained in reports.
2. If new vaccines are added in the app, the same needs to be updated for the reports.

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab8b08e98a80d2369b9ba3e6566ff2a4bdc2b64b/WhatsApp%20Image%202024-04-22%20at%2017.21.06.jpeg" alt="WhatsApp Image 2024-04-22 at 17.21.06.jpeg" />

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9MQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc3fa8a8d8d15aa6f4a200bdf54a41d838bd0c8a/WhatsApp%20Image%202024-04-22%20at%2017.21.06%20%281%29.jpeg" alt="WhatsApp Image 2024-04-22 at 17.21.06 (1).jpeg" />

[Unit2NationalImmunizationSchedule.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFdMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--782d262ecd0c7138b0f7e4fa1d6c97889abb9c47/Unit2NationalImmunizationSchedule.pdf)

**Comment by vedfordev** [comment]
@nupoorkhandelwal date filter is not working for linelist.

**Comment by Dinesh2019** [comment]
- [ ] Date filter is not applied as expected in the DOB column of linelist

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 as per logic, following vaccines should be completed before 9 months 

`BCG
HEPB 0
IPV 1
IPV 2
IPV 3
JE1
Measles 1 (MR)
OPV 0
OPV 1
OPV 2
OPV 3
PCV 1
PCV 2
PCV Booster
Pentavalent 1
Pentavalent 2
Pentavalent 3
Rota 1
Rota 2
Rota 3
Vitamin A 1
`
