### ISSUE TITLE
APF Dashboard Report | Children Status

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#230]
- [x] Make the changes in the pre-release.
- [x] Children Status with the linelist report is a new report to be added for the client in Superset. It is being used to track the status of children, such as SAM/MAM/SUW/Stunted/GF1/GF2.
- [x] A linelist depicting the complete details of the children’s status should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following:  
1. Gender 
2. Project/Block
3. Age Group (Month range 0 to 60)
4. Type of village  
- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=550754295)

Note: Age should be in Months

**Comment by adamsanadi6** [comment]
Dashboard link : [[APFODISHA Prerelease] Children Status](https://reporting-superset.avniproject.org/superset/dashboard/108)

**Comment by Dinesh2019** [comment]
@sachsk don't we need the code review for these cards

**Comment by Dinesh2019** [comment]
- [ ] Growth monitoring is missing in the line-list.
- [ ] The exit status is missing in the line-list.

**Comment by sachsk** [comment]
we are not able to control the age filter.

**Comment by Dinesh2019** [comment]
@sachsk @adam when we are applying the filter we are getting the time out error 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fcea9c3582cd8f7910c2241bdddbd8e1c761732/Screenshot%202024-06-21%20at%2011.58.20%E2%80%AFAM.png" alt="Screenshot 2024-06-21 at 11.58.20 AM.png" />
