### ISSUE TITLE
APF Dashboard Report | Children Home Visit (After QRT)

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#231]
- [ ] Make the changes in the pre-release.
- [ ] Children Home Visit (After QRT) with the linelist report is a new report to be added for the client in Superset. It is being used to track the status of scheduled and completed home visits (after QRT).
- [ ] A linelist depicting the complete details of the children and its status should be displayed. The detailed requirements are available in the analysis link shared below.
- [ ] It will have filters for filtering the data based on the following:  1.
1. Gender 
2. Project/Block 
3. Age Group (Month range 0 to 60)
4. Type of village  

- [ ] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=571066762)

**Comment by nupoorkhandelwal** [comment]
As discussed, with @pkundu  @petmongrels @sachsk  This report cannot be generated using Superset with standard SQL, so it will be put on hold until an alternative solution is found.

**Comment by kameshbhariya** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25CQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43567d07f0f9baef79c08461a8b6e553f3a735eb/Screenshot%202024-07-09%20at%209.31.06%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 9.31.06 AM.png" />
Therefore closing it.
