### ISSUE TITLE
APF Dashboard Report | MAM Child Referral

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#234]
**Changes to be done in Pre-release.**

The following reports are to be created as part of this card.

- [x] MAM Child Referral - Dashboard
- [x] MAM Child Referral - Line list

[Report Analysis ](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=1267571414)

**Comment by adamsanadi6** [comment]
Dashboard link: [[APFODISHA Prerelease] MAM Child Referral](https://reporting-superset.avniproject.org/superset/dashboard/114)

**Comment by sachsk** [comment]
@adamsanadi6 date and exit filter is missing

**Comment by adamsanadi6** [comment]
@sachsk Added the date and exit filter.

**Comment by Dinesh2019** [comment]
We have count mismatch

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2hXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e81ddab0d74ef9e79ac2afdce38818cb33d17fd8/Screenshot%202024-06-12%20at%209.45.48%E2%80%AFAM.png" alt="Screenshot 2024-06-12 at 9.45.48 AM.png" />
