### ISSUE TITLE
APF | Vaccination | Immunization Schedule

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#235]
**Changes to be done in UAT.**

- [x] update the due date and overdue date for the following vaccination items as provided in the sheet [here.](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=903552217)
- HEPB 0
- BCG
- Pentavalent 1
- Pentavalent 2
- Pentavalent 3
- Polio 0
- Polio 1
- Polio 2
- Polio 3
- Polio Booster
- Albendazole 2
- Albendazole 3
- Albendazole 4
- Albendazole 5
- Vitamin A 2
- Vitamin A 3
- Vitamin A 4
- Vitamin A 5
- Measles 2

- [x] **Remove the 'Critical', and 'Expired' status for all the vaccines mentioned above.** 

 **Tech notes**

- [x] The changes will be implemented only on the new enrolments. Complete vaccine schedule for a child is created at the time of enrolment. In order to make a change to an already existing child's schedule, user will have to edit & save the enrolment.
- [x] As part of this change, we are not updating schedule for already enrolled children.

**Comment by Dinesh2019** [comment]
Vaccine Name.  Status
Pentavalent 3.   Vaccination is missing
Albendazole 1.   Vaccination is missing
Albendazole 2.   Vaccination is missing
Albendazole 3.   Vaccination is missing
Albendazole 4.   Vaccination is missing
PCV 2                   Vaccination is missing
