### ISSUE TITLE
Move To PROD | APF | Superset Report Changes | Pregnant Women Linelist (AWC)

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#236]
**Changes to be done in Pre-release.**

- [x] The 'Pregnant Women Linelist'  should **exclude data of lactating women**, as the delivery form has already been submitted.

**Comment by adamsanadi6** [comment]
Dashboard links:
1. [[APFODISHA Prerelease] Pregnant Women Linelist (AWC) (Updated)](https://reporting-superset.avniproject.org/superset/dashboard/102)
2. [[APFODISHA] Pregnant Women Linelist (AWC) (Updated)](https://reporting-superset.avniproject.org/superset/dashboard/76)

**Comment by AnjaliBhagabati** [comment]
@adamsanadi6 @Dinesh2019 

- [ ] As discussed, deleting the duplicate report. Here is the[ link](https://reporting-superset.avniproject.org/superset/explore/?form_data_key=919gyRb09w7y6PkQWlkY-nyEHPDccij7PlQ4Mg3o-YurEiptyaKo_fJpedNrpwGr&slice_id=204)
