### ISSUE TITLE
APF Dashboard | GF2 Child Referral

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#237]
- [x] Make the changes in the pre-release.
- [x] GF2 child referral with the linelist report is a new report to be added for the client in Superset. It is being used to track No of enrolled children, No of GF2 Children	treated at home, Referred to CHC and Any other Higher facility/DH/MC.
- [x] An aggregate and a linelist depicting the complete details of the children and its status should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following:  
1. Gender
2. Project/Block
3. Age Group (Month range 0 to 60)
4. Type of village

- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=565502635)

**Comment by adamsanadi6** [comment]
Dashboard link: [[APFODISHA Prerelease] GF2 Child Referral](https://reporting-superset.avniproject.org/superset/dashboard/112)
