### ISSUE TITLE
APF Dashboard | QRT Child Visit

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#238]
- [x] Make the changes in the pre-release.
- [x] QRT Child Visit with the linelist report is a new report to be added for the client in Superset. It is being used to track the No of enrolled children, No of SAM Children, No of children QRT visited, QRT facilitated child to a medical facility? No of MAM/GF2 Children, No of children QRT visited, QRT facilitated child to a medical facility? Total QRT visit scheduled and Total QRT visit done
- [x] An aggregate and a linelist depicting the complete details of the children and its status should be displayed. The detailed requirements are available in the analysis link shared below.
- [x] It will have filters for filtering the data based on the following:  
1. Gender
2. Project/Block
3. Age Group (Month range 0 to 60)
4. Type of village

- [x] [Link to the analysis](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit#gid=502828175)

**Comment by adamsanadi6** [comment]
Dashboard link: [[APFODISHA Prerelease] QRT Child Visit](https://reporting-superset.avniproject.org/superset/dashboard/104)

**Comment by sachsk** [comment]
@adamsanadi6 rearrange the charts in dashboard put linelist below the agg.

**Comment by adamsanadi6** [comment]
@sachsk , I have rearranged the charts accordingly.

**Comment by sachsk** [comment]
@adamsanadi6 this report will give wrong count for the total child enrol as you have added filter on encounter_date at last so remove that filter from last and filter out encounter data on cte or join

**Comment by Dinesh2019** [comment]
- [ ] Age in months 0 to 60

**Comment by Dinesh2019** [comment]
- [ ] We have a count mismatch 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHBTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2477895ac841093c2661ff24625f063ca79c888a/Screenshot%202024-06-11%20at%205.17.14%E2%80%AFPM.png" alt="Screenshot 2024-06-11 at 5.17.14 PM.png" />

**Comment by adamsanadi6** [comment]
As discussed with @nupoorkhandelwal  This report cannot be generated using Superset with standard SQL, so it will be put on hold until an alternative solution is found.

**Comment by kameshbhariya** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25CQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43567d07f0f9baef79c08461a8b6e553f3a735eb/Screenshot%202024-07-09%20at%209.31.06%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 9.31.06 AM.png" />
Therefore closing it.
