### ISSUE TITLE
[APF Odisha] Data Migration in Form | Individual Registration

### ISSUE THREAD

**Issue by adamsanadi6** [avniproject/apfodishanutrition#245]
Data Migration from one from to another: APF team will inform the PS/Field Workers to not use the app for 1 week in which we can do all the data migration work

**Detailed analysis** - https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1604108639

- [x] **Individual Registration:** Data of [two question](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=406612277&range=24:25)s needs to be migrated from this form **to Pregnancy Enrolment Form**. In case a women is enrolled multiple times into the Pregnancy Program, we need to take the latest data of the women for migration.
- [x] Change 1 - Field “Is the beneficiary registered in the AWC?” Is moved from Individual registration form ->> Pregnancy enrolment form.
- [x]  Change 2 - Field “If yes, in which trimester” is moved from Individual registration form ->> Pregnancy enrolment form

**Note**: Since we don't have the data in the UAT to test Migration Script, Run it in APF Odisha pre release org.

**Comment by adamsanadi6** [comment]
For Ref: [Freshdesk Ticket Link](https://avni.freshdesk.com/a/tickets/3918)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal Please review script.
[Script Link](https://github.com/avniproject/apfodishanutrition/blob/main/migrations/Migration%20of%20Which%20Trimester%20and%20Is%20AWC%20Registered%20from%20Individual%20Registration%20to%20Pregnancy%20Enrolment.sql)

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 what will happen when the observation is missing in the registration?

please update the query to check before adding the observation if it is not present

select *
from subject_type;
-- Individual 672

select *
from public.individual
         join program_enrolment pe on individual.id = pe.individual_id
         join "program" p on p.id = pe.program_id
where individual.observations ->
      'faa2d09f-6dd8-45ca-99ae-57fb2685abdd' is null
  and subject_type_id = 672
  and pe.program_exit_date_time is null
  and pe.is_voided = false
  and p.name = 'Pregnancy'
  and p.is_voided = false

select *
from public.individual
         join program_enrolment pe on individual.id = pe.individual_id
         join "program" p on p.id = pe.program_id
where individual.observations ->
      '8d8a4d13-515a-4f3c-ac7e-04d22fd4782a' is null
  and subject_type_id = 672
  and pe.program_exit_date_time is null
  and pe.is_voided = false
  and p.name = 'Pregnancy'
  and p.is_voided = false

**Comment by mahalakshme** [comment]
@adamsanadi6 for last_modified_by_id we have used 10917, but that user doesn't exist and hence this will cause sync issue(https://github.com/avniproject/avni-client/issues/1399), when trying to sync audit information. So kindly update it to a valid user id.

@Dinesh2019 so [this](https://github.com/avniproject/avni-client/issues/1399) card, is not a product bug.

**Comment by mahalakshme** [comment]
oh sorry now I am able to see that user

**Comment by mahalakshme** [comment]
@adamsanadi6  @Dinesh2019 actually I was right, in prerelease, userId used by adam in the script to update is not present in prerelease env. It is only present in prod. 
so [this](https://github.com/avniproject/avni-client/issues/1399) not a bug
