### ISSUE TITLE
[APF Odisha] Data Migration in Form | ANC Form

### ISSUE THREAD

**Issue by adamsanadi6** [avniproject/apfodishanutrition#247]
Data Migration from one from to another: APF team will inform the PS/Field Workers to not use the app for 1 week in which we can do all the data migration work

**Detailed analysis** - https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1604108639

- [ ] **Pregnancy Enrolment:**
- [ ] Field “Mamata Scheme Amount received” is moved from Pregnancy enrolment form ->> ANC form.

**Note**: Since we don't have the data in the UAT to test Migration Script, Run it in APF Odisha pre release org.

**Comment by nupoorkhandelwal** [comment]
https://github.com/avniproject/apfodishanutrition/blob/main/migrations/Phase%202/Move%20Mamata%20amount%20recieved%20from%20program%20enrolment%20to%207th%20month%20ANC.sql

**Comment by vedfordev** [comment]
### Code Review 
@nupoorkhandelwal  getting error in join condition and add verification script.

**Comment by nupoorkhandelwal** [comment]
@vedfordev fixed and added select query.

**Comment by sachsk** [comment]
@nupoorkhandelwal In enrolment  "Mamata scheme amount received" has 3 answers(Yes, No, Don't know) but "Have you received first installment of Mamata scheme amount?" has two(Yes, No) answers only so need to handle this scenario as well.
Also " last_modified_date_time = current_timestamp + (random()  5000  (interval '1 millisecond'))," need to fix this
