### ISSUE TITLE
[APF Odisha] Data Migration in Form | PNC Form

### ISSUE THREAD

**Issue by adamsanadi6** [avniproject/apfodishanutrition#248]
Data Migration from one from to another: APF team will inform the PS/Field Workers to not use the app for 1 week in which we can do all the data migration work

**Detailed analysis** - https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1604108639

- [x] **PNC Form**: [One question](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1368760264&range=20:20) 
- [x] Field “JSY money received?” Is moved from Delivery form to the 2nd PNC

**Note**: Since we don't have the data in the UAT to test Migration Script, Run it in APF Odisha pre release org.

**Comment by nupoorkhandelwal** [comment]
https://github.com/avniproject/apfodishanutrition/blob/main/migrations/Phase%202/%22JSY%20money%20received%22%20move%20from%20Delivery%20to%202nd%20PNC.sql

**Comment by vedfordev** [comment]
### Code Review 
@nupoorkhandelwal  getting error in join condition and add verification script.

**Comment by nupoorkhandelwal** [comment]
@vedfordev fixed the script, check now
