### ISSUE TITLE
APF | First Installment of MAMTA Incorrect Rule

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#252]
Changes to be done in UAT.

- [ ] Question 'Have you received first installment of Mamata scheme amount?' in ANC form should be populated in ANC which is going to be scheduled 180 days after LMP. e.g. LMP= 1st Jan, ANC of 1st July should populate this question.

[Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=836611880&range=24:24)

**Comment by vedfordev** [comment]
back up of old rule

```js
'use strict';
({params, imports}) => {
  const programEncounter = params.entity;
  const moment = imports.moment;
  const formElement = params.formElement;
  const _ = imports.lodash;
  let visibility = false;
  let value = null;
  let answersToSkip = [];
  let validationErrors = [];
  
  let encounterList = programEncounter.programEnrolment.encounters.filter((enc)=> enc.encounterType.name === 'ANC' && enc.voided == false && enc.cancelDateTime == null);
  
  if(encounterList.length >= 7){
     encounterList = _.orderBy(encounterList,['earliestVisitDateTime'],['asc']);
     visibility = encounterList[6].uuid == programEncounter.uuid
     console.log('7th encounter');
  }
  
  return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, value, answersToSkip, validationErrors);
};
```

**Comment by Dinesh2019** [comment]
When we register the individual with LMP as Jan 01, 2024, and if we calculate the 180 days it is June 29/2024 but the visit is due on 1-jun-2024 if we try to complete the visit it is not displaying the question as expected.
