### ISSUE TITLE
[APF Orissa- Phase 2]: UAT Feedback: Pregnancy Enrolment

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#254]
- [x] Changes to be done in APF UAT environment
 - [x] Changes to be made in the forms are highlighted in "Yellow"
 - [x] For the Gravida question, we have set the limit Limit: > 1 and < 9 but evenif you enter any other number like 999999 or 23627463767 it allows you to move to the next page. This should be restricted
 - [x] Mamata registration and its following question, we need to remove the dependency with the "Bank account opened" question. Currently the Mamta Registration and its following questions are showing if in the question "Bank account opened" "Yes" is selected. Need to remove that.
 - [x] Question "Pregnancy induced morbidity conditions" spelling mistake in the question and in the option:Gestational Diabetes
 - [x] Question "If yes, in which trimester" - Spelling mistake 
 - [ ] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=893561151)

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati For the Gravida question we have the limit and we have the How many children do you have (alive) is accepting the value greater than Gravida I think we should not allow that can you confirm and let us know if we need to fix this.

@vedfordev 
1. Weight logic needs to be updated
2. Height logic needs to be updated 
3.Birth Spacing (time between two pregnancies in months) accepting 0 and negative value which should be restricted

**Comment by AnjaliBhagabati** [comment]
@Dinesh2019 yes we can put the same limit as Gravida for this question as well. 
I have updated it in the sheet.

@vedfordev can you add that please.
