### ISSUE TITLE
[APF Orissa- Phase 2]: UAT Feedback: QRT PW, QRT Child Cancelled Overdue Visits til June 30th, 2024

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#261]
- [x] All Overdue visits of QRT PW, QRT Child to be cancelled which are overdue till June 30th, 2024 (via script)

**Tech tasks**

- [x] Select all program encounter of encounter type - "QRT PW" and "QRT Child"
- [x] Filter where encounter_date_time is null and cancel_date_time is null and is_voided = false
- [x] Filter where max_visit_date_time is before'2024-06-30'
- [x] set cancel date time, cancel reason as "Other" and "Other reason for cancelling the visit" 
- [x] Get the script reviewed by Product team
- [x] Get the script reviewed by Teach lead
- [x] Run it on pre release APF Odisha org
- [x] Move to QA

**Comment by vedfordev** [comment]
[Ticket](https://avni.freshdesk.com/a/tickets/4198)
[Script](https://github.com/avniproject/data-fixes/blob/main/apfodisha/cancel_qrt_visits_before_30june_2024.sql)

**Comment by vedfordev** [comment]
@nupoorkhandelwal 
Code review is done. 
Please move card forward.

**Comment by nupoorkhandelwal** [comment]
@vedfordev please run this script on pre release.
