### ISSUE TITLE
[APF Orissa- Phase 2]: UAT Feedback: Child Enrolment

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#265]
- [ ] Changes in the form are to be made in the APF UAT environment
- [ ] Changes in the form are highlighted in Yellow
- [ ] Just need to add limit for Birth Weight
- [ ] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=23097314)

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati what do we have to do if the column is highlighted in red?

**Comment by AnjaliBhagabati** [comment]
@dinesh nothing, you can ignore the red highlighted question. It was from before. No changes to be made
