### ISSUE TITLE
Poshan user able to complete visit of QRT User

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/apfodishanutrition#267]
When a Poshan Sathi complets the ANC visit they are able to save the ANC form and proceed to QRT PW visit and complete the QRT PW form. We should be restricted this. Poshan Sathi should not be able to fill  QRT PW form as it is scheduled for QRT.

Had a conservation with Maha and she told that we have the work update rule by updating which it we can fix this.

env: prod, pre-release
org: apfodishauat
user: dineshg@apfodishauat

Steps to reproduce :
1. Login to the user
2. Register the individual
3. Enroll in the pregnancy program
4. complete the ANC which will schedule the QRT PW visit (only done by QRT user)
5. Click on the Save and proceed to QRT PW

Expected result: Poshan Sathi user should not be allowed to complete the QRT visit.
Actual result: Poshan Sath the user is able to complete the visit

Refer video : 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6984297cb6fa3bdb12d4b3487c823d3ffb7acebe/Screen%20Recording%202024-05-15%20at%205.25.42%E2%80%AFPM.mov

**Comment by AnjaliBhagabati** [comment]
@nupoorkhandelwal can you review this card

**Comment by nupoorkhandelwal** [comment]
Shared context to @mahalakshme , she will create a corresponding bug card on product board with required details.

**Comment by mahalakshme** [comment]
product bug: https://github.com/avniproject/avni-client/issues/1404
