### ISSUE TITLE
[APF Orissa- Phase 2]: UAT Feedback: Offline Dashboard: Dashboard

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#268]
- [ ] Changes needs to be done in APF UAT environment
 - [x] **Under Dashboard: Pregnancy:** High Risk Pregnancy card not showing the count. It shows 0 even if there are High Risk Pregnancy cases are there. Show the High Risk Count based on "Yes" selected for the question "To be monitored by QRT" in the ANC form
 - [x] **Under Dashboard: Child: Total Child enrolled in CMAM Program:** 

- Currently same child is showing multiple times under the CMAM Program, based on the Growth Monitoring form filled. eg for a child if in two Growth Monitoring for the question "Is the child enrolled in the CMAM program?" is answered "Yes" under the Total Child enrolled in CMAM Program card, the same child name and details showing two times. Screenshot attached
- We need to show if only one time and keep showing till 4month 
- Changes to be made [in the form for this are highlighted in Yellow](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=960251287&range=19:21)

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50f5741f4a80327d8f93bd563a438a9720fa8d8c/media_20240516_151558_5699315498247724088.jpg" alt="media_20240516_151558_5699315498247724088.jpg" />

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcc59f4633c57d633fe2174d1139959890dbfb31/media_20240516_151558_2128179783474192277.jpg" alt="media_20240516_151558_2128179783474192277.jpg" />

**Comment by AnjaliBhagabati** [comment]
@sachsk I checked with Jagadisha, for this High Risk card also, we have to show the High Risk Count based on "Yes" selected for the question "To be monitored by QRT" in the ANC form

**Comment by Dinesh2019** [comment]
@sachsk the logic for CMAM in the client app does not behave as expected 

Video Reference :

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0wwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8965238fb0f69d7cc1e1a13ed17bff914f999479/My%20Movie.mp4

Pregnancy in video reference:


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEgwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f86d7fc4cc002990f9ac4c6984e0919c05ab3d56/My%20Movie.mp4

**Comment by Dinesh2019** [comment]
- [ ] High-risk pregnancy count shows different counts in the dashboard and QRT dashboards.
- [ ] CMAM program question is displayed only when the status is shown as SAM or MAM and the option is selected as Treatment at home. But actually, it is displayed even though the treatment is at home.
