### ISSUE TITLE
[APF] UAT Feedback 3.0

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#27]
- [x] **NRC from** - "Date of admission in NRC" should be on or after "Date of referral" in "QRT SAM Child"

- [x] **Village Profile** Add validation - Current population of the village < 9999

- [x] **Village Profile** Add validation - Total number of households in the village < 999

- [x] **Village Profile** Add validation - All question having (in minutes) < 999

- [x] **QRT PW form** - Add validation - How many times in a day, are you having meal? < 10

**Comment by AchalaBelokar** [comment]
- [ ] validation text is missing

**Comment by nupoorkhandelwal** [comment]
[Uploading... 1667311644203.JPEG]

**Comment by nupoorkhandelwal** [comment]
![1667311644203.JPEG](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/01892aec-d333-4280-b25d-998a5b89343c)
