### ISSUE TITLE
[APF Orissa- Phase 2]: New UAT Feedback: QRT Child

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#272]
- [ ] Changes to be made in APF UAT environment
- [ ] There are two questions in which logic needs to be updated
- [ ] Changes in the form is highlighted in Yellow
- [ ] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=142552483)

**Comment by sachsk** [comment]
unable to implement logic for referral date  so we are not doing this
