### ISSUE TITLE
APF Phase 2| Offline Dashboard: 'QRT PW' & 'QRT Child' cards to be moved to 'QRT Dashboard'

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#274]
- [x] Changes to be done in APF UAT 
- [x] In the QRT Dashboard we need to show the below cards. These same cards we have used in QRT pregnancy due and overdue visit and QRT child due and overdue visits dashboard card

Below Pregnancy

1. QRT PW : 

- Due Visits for QRT PW 
- Overdue for QRT PW

2.  QRT PW Follow Up: 

- Due Visits for PW Home Visit
- Overdue for PW Home Visit

Below Child

1. QRT Child Follow Up

- Due Visit for QRT Child Follow Up
- Overdue for QRT Child Follow Up

2. QRT SAM Child
- Due for QRT Child SAM
- Overdue for QRT Child SAM

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati @vedfordev I hope we have changed the name of QRT Child Follow Up to Growth monitoring do we need to remove and add Growth monitoring regarding to overdue and due

**Comment by AnjaliBhagabati** [comment]
@vedfordev @Dinesh2019 

- [ ] remove the below card from QRT Dashboard  and QRT Child due and overdue Dashboard 
QRT Child Follow Up
Due Visit for QRT Child Follow Up
Overdue for QRT Child Follow Up
