### ISSUE TITLE
APF Phase 2| Offline Dashboard for QRT : Medical Facilitation 

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#276]
- [x] This needs to be done in UAT first
- [x] This needs to be created for QRT. In QRT Dashboard need to show:

1. QRT Intervention Required? 
**Logic:** In the[ Medical Facilitation Form for Poshan Sathi,](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/306) if in the question  "Is QRT Intervention Required?" is answered as 
"Yes" for any child, that count should be shown in this "QRT Intervention Required?" offline dashboard card till a corresponding QRT form (Medical Facilitation - for QRT) is not filled

2. [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=186279590#gid=186279590&range=25:25)

**Tech notes**

- [x] Count the number of encounter where "Is QRT Intervention Required?" is 'Yes' less than the number of encounter where "Medical Facilitation - for QRT" filled then show it. (Try this)

**Comment by Dinesh2019** [comment]
@vedfordev We have to handle if the QRT Medical Facilitation Form is completed. Do we have to remove the count from QRT Intervention Required?

**Comment by vedfordev** [comment]
backup:
```js
// Documentation - https://docs.mongodb.com/realm-legacy/docs/javascript/latest/index.html#queries
'use strict';
({params, imports}) => {
    let indList = params.db.objects('ProgramEnrolment')
    .filtered(`voided = false AND programExitDateTime = null AND program.name = 'Child'`);
    indList =  indList.filter(enrolment=>{
        let temp = false;
        let x = enrolment.findLatestObservationInEntireEnrolment("Is QRT Intervention Required?");

        temp = (x)?x.getReadableValue() == 'Yes':false;
        return temp;
    }).map(enrolment=>enrolment.individual);



    
    return indList;     
};
```

**Comment by AnjaliBhagabati** [comment]
@vedfordev as confirmed by the client, can you add in the decision rule that if "Is QRT Intervention Required?" is answered as Yes in the Medical Facilitation by Poshan Sathi form,  consider "To be monitored by QRT "as Yes irrespective of the QRT scheduling in the Growth Monitoring 

cc @nupoorkhandelwal @Dinesh2019

**Comment by Dinesh2019** [comment]
@vedfordev @AnjaliBhagabati only if the To be monitored by QRT is yes, then only the individual displays it for the QRT users and also we are taking the latest encounter to the count.
