### ISSUE TITLE
APF Phase 2| App: New Form : NRC 

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#277]
- [x] This form first needs to be created in UAT under Child program
- [x] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=287957931#gid=287957931)

**Comment by Dinesh2019** [comment]
@vedfordev @AnjaliBhagabati, and @nupoorkhandelwal Only QRT users were granted access to this form

**Comment by Dinesh2019** [comment]
@vedfordev @AnjaliBhagabati 

- [ ] Nutritional status at the time of discharge  is not calculated for cured and discharge 
- [ ] Date of discharge from NRC can be able to select the date less than the date of admission
- [ ] Criteria of exit if we select the other medical complication, do we need to show the option like admission? 


Attached video for references : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemllQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef9813ef27d737c7593113623eab061b9f06c914/Screen%20Recording%202024-06-28%20at%206.33.29%E2%80%AFPM.mov

**Comment by AnjaliBhagabati** [comment]
@Dinesh2019 @vedfordev Criteria of exit if we select the other medical complication, do we need to show the option like admission?
we can add it as non mandate question.

@vedfordev I have added it in the form sheet. Can you get this added
