### ISSUE TITLE
APF Phase 2| App: UAT Feedback: Need to move question Pregnancy induced morbidity condition, from Pregnancy Enrolment form to ANC form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#281]
[Pregnancy Enrolment Form](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=893561151)

- [x] Remove the question "Pregancy induced morbidity conditions"
- [x] No impact on Geographically High Risk Condition. 
- [x] Clinically High Risk: Now on enrolment a women will not be considered "Clinically High Risk" becauser of "Pregancy induced morbidity conditions" as we are removing this question from this form. 
However, if any other [clinically high risk condition exits ](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=934737801#gid=934737801)in the women, from the Clinically High Risk Condition list shared, the women will be considered Clinically High Risk and we will show it in the summary.

[ANC Form](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=836611880)

- [x] Need to add "Pregancy induced morbidity conditions" from Enrolment to ANC form and ask in every ANC
- [x] No impact on Geographically High Risk Condition
- [x] Clinically High Risk: If in any ANC the women has any of the "morbidity conditions"  or have any of the conditions mentioned in the Clinically High Risk Condition list, the pregnancy will be considered as Clinically High Risk
- [x] No change in visit schedule logic.

**Tech Notes**

- [x] Question - "12d99265-c769-4236-aff5-fcba73976396" ie. Pregnancy induced morbidity conditions is being moved from Enrolment to ANC, hence decision rule to update the High risk conditions needs to be updated in both the forms.
- [ ] Thorough testing of all the High risk condition needs to be done. (Dev & QA both)

**Comment by Dinesh2019** [comment]
High risk  is not calculated when we select any option based on any history of pregnancy complications. But as per the requirement, if any option is selected other than No history of pregnancy complications, 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88b99ad7cec8d54156d5bf47d50ffdc5444f2c25/Screen%20Recording%202024-06-15%20at%207.44.24%E2%80%AFPM.mov
