### ISSUE TITLE
APF Phase 2| App: UAT Feedback:  Growth Monitoring form: Need to calculate the DOB as on Schedule Date not as on Encounter/Visit Date and few other data logic changes

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#282]
- [x] Changes to be made in the uat environment
- [x] Only make this change in the Growth Monitoring Form
- [x] **Calculate the DOB as on Schedule Date not as on Encounter/Visit Date** for the below 6 questions
- [x] Do not need to do the change for Nutritional Grade question

6 Questions:

1. Is the child going to PPK?
2. Is the child going to Creche?
3. Is the child being currently exclusively breastfed? 
4. Is the child being currently breastfed? 
5. Number of day attended AWC (last month)
6. Is the mother receiving THR from AWC in last month?

- [x] The question "Is the child receiving THR from AWC in the last month?" should not appear for children older than 3 years
- [x] The question "Is the child receiving egg from AWC in last month?" should not appear for children older than 3 years
- [x] Changes in the form are highlighted in Yellow

- [x] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=960251287#gid=960251287)

**Tech notes**
Currently, the age in the app is calculated based on the encounter date. But we need to update the logic to calculate age from the earliest date.

**Comment by vedfordev** [comment]
@sachsk as discussed in stand up, please review this card

**Comment by sachsk** [comment]
@vedfordev Can you ask BA if we need to calculate the age for rows 14 and 15 based on the earliest date?

**Comment by vedfordev** [comment]
@AnjaliBhagabati can you check above comment ??

**Comment by AnjaliBhagabati** [comment]
@vedfordev @sachsk  please add the "Calculate the DOB as on Schedule Date not as on Encounter/Visit Date" logic in row 14 and 15
