### ISSUE TITLE
[APF Odisha Phase-2] App Changes to Production Org

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#288]
**Tech tasks**

- [x] Download bundle without locations from APF Odisha UAT
- [x] Upload the same to Production org
- [x] Test all the app changes thoroughly done under following Epics - 
- [x] [Epic 1 ](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/122)
- [x] [Epic 2](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/123)

**Comment by Dinesh2019** [comment]
- [ ] Location filter is not added in the production env.

**Comment by sachsk** [comment]
@Dinesh2019 test this issues against the location Nuasahi (block Dangriguda (GP))
