### ISSUE TITLE
[APF Odisha Phase-2] QA of Sync attributes & strategies

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#291]
- [x] Check if all the users under Poshan Sathi group has corresponding sync attributes assigned
- [x] Check if all the users under QRT users group has corresponding sync attributes assigned
- [x] Check if all the access/permissions of the form are correct for the respective groups
- [ ] **Delete in case any fast sync is setup from the AWS**

**Comment by Dinesh2019** [comment]
For QA references (query used to test the sync attributes ) : 

select users.name, groups.name
from public.users
         join user_group ug on users.id = ug.user_id
         join groups on ug.group_id = groups.id
where groups.name = 'QRT users'
  and ug.is_voided is false
  and not (
        ((users.sync_settings ->> 'subjectTypeSyncSettings')::jsonb -> 0 ->> 'syncConcept1' = 'be0ab05f-b0f3-43ec-b598-fdde0679104a'
            AND ((users.sync_settings ->> 'subjectTypeSyncSettings')::jsonb -> 0 -> 'syncConcept1Values')::jsonb ?&
                array ['8ebbf088-f292-483e-9084-7de919ce67b7'])
        OR ((users.sync_settings ->> 'subjectTypeSyncSettings')::jsonb -> 0 ->> 'syncConcept2' = 'be0ab05f-b0f3-43ec-b598-fdde0679104a'
        AND ((users.sync_settings ->> 'subjectTypeSyncSettings')::jsonb -> 0 -> 'syncConcept2Values')::jsonb ?&
            array ['8ebbf088-f292-483e-9084-7de919ce67b7'])
    );
