### ISSUE TITLE
APF Phase 2| App: Training Feedback: Visit is not getting scheduled immediately upon enrolment

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#299]
- [ ] This issue was encountered by the APF team while doing training
- [ ] Said this happens sometimes
- [ ] Sometimes visits doesn't get scheduled immediately upon enrolment, attached is the screenshot.
It get schedule if you edit the enrolment form, which shouldn't be the case.

Case Details:
Individual Name: Hardik Kumar Nayak
Male, 4 years, Haladia
Child Program 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejFyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f4793606abeb0471d1f1e5ac2c94eccfe598ed2/VID-20240605-WA0011.mp4)

**Comment by nupoorkhandelwal** [comment]
@AnjaliBhagabati this is not reproducible. In case u find any other case where it is reproducible then please share

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati unable to reproduce the issue.
