### ISSUE TITLE
[APF] ANC Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#3]
- [x] Create a program encounter under Pregnancy Program - ANC

- [x] ANC Form From Requirement document- 
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=836611880

- [x] ANC Cancel Form -
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=69066955

**Comment by utkarshavni** [comment]
Updated:
Spell correct - Abdomincal to Abdominal
HB (value) made mandatory as condition based field.

**Comment by Gojo-Taqi** [comment]
Added Decision rules
