### ISSUE TITLE
[APF] Post Go LIVE changes - Update visit scheduling for Child Followup 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#30]
- [x] Update Child followup visit scheduling as per below logic -
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1422128164&range=B5

- [x] Check for users not being created issue- 
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=2054344435&range=102:102

**Comment by nupoorkhandelwal** [comment]
@utkarshavni please test ANC and PNC cancel scenarios

**Comment by AchalaBelokar** [comment]
Can you look at the Tana Tani Individual  the birth date was ,1 sep 2022 
then visit  was scheduled  1 jan 2023 . after that I cancel the visit  at 2 jan 2023 then visit should  be schedule  after the  1 feb 2023 but currently  it is scheduling  1 jan 2023

**Comment by AchalaBelokar** [comment]
Can you look at the Tana Tani Individual  the birth date was ,1 sep 2022 
then visit  was scheduled  1 jan 2023 . after that I cancel the visit  at 2 jan 2023 then visit should  be schedule  after the  1 feb 2023 but currently  it is scheduling  1 jan 2023

**Comment by AchalaBelokar** [comment]
After canceling the QRT child visit it is showing  1st visit after 15 days but after that it is scheduling 30 days nRC

**Comment by AchalaBelokar** [comment]
Tannu Mannu there is 2 record You need to check child onw
1st visit is 10 jan which is completed.after thar 25 jan is scheduling  which is 15 days 
but after that it is scheduling 9 feb .it should  be after 45 days

**Comment by sachsk** [comment]
@AchalaBelokar  as per our discussion  I have  added cancel form in QRT followup and it will schedule the next visit as per schedule.
