### ISSUE TITLE
APF Phase 2| App: Training Feedback: Auto fetch data sometimes shows error

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#300]
- [x]  This issue was encountered by the APF team while doing training
- [x]  Said this happens sometimes
- [ ]  Sometimes auto fetch data show error as shown in the attached image. Here weight was entered in the Growth Monitoring form and should have been auto captured in the Child Home Visit form.

Individual Details:

Name: MM
Female, 1 Week, Haladia

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d337bb498ff8106b0db3140a1a565d2c90612f81/GM.jpg" alt="GM.jpg" />

<img width="359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca42013691290edf85f2fd244e1ab78791e6f456/1718624577814.JPEG" alt="1718624577814.JPEG" />

**Comment by nupoorkhandelwal** [comment]
Fixed.
