### ISSUE TITLE
{APF Dashboard Report} : Access Permission

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#302]
- [ ] Please give view permission in Superset of the reports in draft and pre-release to the below users

- Jagadisha Behura : jagadisha.behura@azimpremjifoundation.org
- Shobana Sivaraman : shobana.sivaraman@azimpremjifoundation.org
- Ramesh Sahu : ramesh.sahu@azimpremjifoundation.org

**Comment by AnjaliBhagabati** [comment]
@sachsk HERE IS THE REPORT LIST:

Reports In Pre-release

1. [APFODISHA Prerelease] Pregnant Women Linelist (AWC): 
2. [APFODISHA Prerelease] Pregnancy Women Info (AWC)
3.  [APFODISHA Prerelease] Child linelist (AWC) (updated)
4. [APFODISHA Prerelease] Growth Monitoring
5. [APFODISHA Prerelease] QRT Child Visit
6. [[APF Odisha Prerelease] [APF Odisha] EDD Vs Actual Delivery
7. [APFODISHA PRERELEASE] PW QRT Visit
8. [APFODISHA Prerelease] GF2 Child Referral
9. [[APFODISHA Prerelease] MAM Child Referral
10. [APFODISHA Prerelease] SAM Child Referral
11. [APFODISHA Prerelease] Household Entitlements
12. [APFODISHA Prerelease] Trimester Wise PW Registration
13. [APFODISHA] PW Home Visit Details
14. [APF Dashboard Report] : Delivery Location
15. [APFODISHA]Sector-wise Distribution of Women Availed Benefits Under Mamta
16. {APF Dashboard Report} : PNC Visit Details
17. [APF Dashboard Report | Child Entitlement

**Comment by Dinesh2019** [comment]
@sachsk As discussed, we are closing this card since it does not need QA.
