### ISSUE TITLE
APF Phase 2| Offline Dashboard for QRT : NRC

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#305]
- [x] This needs to be created in UAT first
- [x] Show the count Due and Overdue visits for QRT. Take the count if child, for whom in the NRC for in question "Advice" the answer is "Referred to NRC"
- [x] [Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=186279590#gid=186279590&range=24:24)

**Tech analysis**

- [x] Count all the ind where there is only a planned NRC. It will give the correct count.

**Comment by Dinesh2019** [comment]
@adamsanadi6 @AnjaliBhagabati since the NRC is currently an unplanned visit. we cant test this card on holding it for now
