### ISSUE TITLE
APF Phase 2| App: Training Feedback: ANC Form: Program Summary

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#308]
- [ ] Bug to be first fixed in UAT 

**Bug 1:**

- [x] In the program summary of the ANC form, evenif the pregnancy is geographically high risk and QRT visit is getting scheduled, in the program summary "To be monitored by QRT" shows as No.
- [x] We recently made this changes in the ANC for related to Geographically High Risk. You can refer to this card if required to see if they bug is related to [this card ](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/304)or not
- [ ] Attached is the screenshot 

**Reference Case:**
Pregnancy Program
Sita Sharma
Female, 25 year, Sulerpadar

**Bug 2**

- [x] In the ANC form, even if no Clinically High Risk conditions are selected, the pregnancy is showing as clinically high risk in the Program Sumarry

**Reference Case:**
Pregnancy Program
Kira O
Female, 25 year, Sulerpadar

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--428ed85bc536a4d4a97c2864c8ad9b8229852ed7/The%20system%20recommendations%20are%20incorrect%20for%20a%20PW.%20%27Clinically%20high%20risk%27%20is%20showing%20as%20%27yes%27%20despite%20having%20no%20medical%20complications.%20This%20issue%20is%20encountered%20in%20geographically%20high-risk%20cases..jpg" alt="The system recommendations are incorrect for a PW. 'Clinically high risk' is showing as 'yes' despite having no medical complications. This issue is encountered in geographically high-risk cases..jpg" />

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGVMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02980d9084f5469e7805ae37bb6c11031177ba6c/The%20system%20recommendations%20are%20incorrect%20for%20a%20PW.%20A%20QRT%20visit%20is%20scheduled%20because%20the%20woman%20is%20in%20a%20geographically%20high-risk%20area%2C%20but%20the%20system%20marks%20%27To%20be%20monitored%20by%20QRT%27%20as%20%27NO%27.jpg" alt="The system recommendations are incorrect for a PW. A QRT visit is scheduled because the woman is in a geographically high-risk area, but the system marks 'To be monitored by QRT' as 'NO'.jpg" />

**Comment by sachsk** [comment]
**Bug 1:**  "To be monitored by QRT"  will show  Yes only if QRT is scheduled or in ANC value of "To be monitored by QRT"  is yes

**Comment by Dinesh2019** [comment]
QA refrences (No action needed for dev and BA)


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2VSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbf13e6ad4257d5bd692aa0935dd830846797973/Screen%20Recording%202024-06-26%20at%2011.43.50%E2%80%AFAM.mov

**Comment by Dinesh2019** [comment]
@sachsk we have to move the changes to prod
