### ISSUE TITLE
[APF] Post field visit feedbacks

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#31]
- [x] **Dashboard cards are slow**. Remove the isPrimary check for custom dashboard from all the user groups

- [x] **Create a new custom offline dashboard** Visit details -
Having due and overdue for each encounter type
(Due/overdue  visits should be due by a week)

- [x] **Remove the due and overdue cards from offline dashboard**

- [x] **QRT PW form** it is showing validation error "Date of referral cannot be before LMP" even though date of referral is 05-12-2022 and LMP is 02-06-2022. This is for Lakshmi Kishan in Budhikutuni. Looks like the logic is wrong there.

- [x] Configure location search filters for all subjects, AWC and villages should be available.

- [x] Add check on fields where value is not defined then validation error should  not show up - Date of admission, Date of discharge.

- [x] **Pregnancy program eligibility check** - Change age limit on program eligibility to 12

**Comment by AchalaBelokar** [comment]
- [ ] Performance is very slow of dashboard.

- [ ] In Pregnancy  due and overdue dashboard when I am clicking on QRT PW it takes a lot of time like 5,6 min still it is not coming.

**Comment by Gojo-Taqi** [comment]
Performance of the reports look decent to me, none of them took lot of time. Including QRT PW.
AWC and villages were already available in the search filters.
