### ISSUE TITLE
APF Phase 2| UAT Feedback: NRC Form Visit Scheduling

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#315]
- [x] Visit Schedule: 

1. NRC will get scheduled if in the QRT Child form. question "Advice" the answer is "Referred to NRC" 

Schedule it immediate for QRT
Overdue : 60 day

2. Once NRC is completed, Child Home Visit needs to be scheduled for Poshan Sathi

Schedule this form at an interval of 15 days from the  date of discharge for 4 times
Overdue: 7 days from Due Date

[Vist Schedule Link
](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=2036643668#gid=2036643668&range=17:18)

**Tech notes**
1. Child Home visits post NRC should not override any existing Child Home visit scheduled from Growth Monitoring or QRT.
2. Visits post NRC can be named as " Child Home visit - Post NRC'
3. And if 'return scheduleBuilder.getAll();' is giving only one Child Home Visit at a time then try using this 'scheduleBuilder.getAllUnique()' in the return

**Comment by nupoorkhandelwal** [comment]
The scheduling logic of Child Home Visit post NRC is completed. But it is not working as expected. Child Home visit (if any scheduled ) post QRT is being overridden by the Child Home visits post NRC and vice versa. This means that only one Child Home Visit can be scheduled at a time. 

I have created a product bug card for the same- https://github.com/avniproject/avni-client/issues/1446

**Comment by nupoorkhandelwal** [comment]
https://avni.readme.io/docs/writing-rules#example-2 using visitCreationStartegy solved this issue!

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal The Child Home Visit - Post NRC should be scheduled four times in accordance with the above requirement, but it is not being scheduled as expected.


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1vQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52aa984293b73d5961d0ba06becb5397bca6993b/Screen%20Recording%202024-07-02%20at%206.15.35%E2%80%AFPM.mov

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 I'll check this and get back to you

**Comment by nupoorkhandelwal** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1d1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61f4105dcf0f780bf522e21a513706009c22b72f/media_20240703_171326_2329083400376020900.mp4)
