### ISSUE TITLE
APF Odisha Phase 2|TIMS: TIMS Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#316]
**Context:**
Training Information Management System (TIMS), is a new module that will be used by the APF Odisha team to capture the training needs of POSHAN Saathi. The training needs will be reported as a sheet in the superset, which can be seen by the MIS and Programme Manager. The Programme Manager will fill in the status of training conducted and planned for every month. A new subject type called User Subject Type to be created for this. 
A separate custom dashboard for this will be created through which all the forms related to this User Subject Type can be accessed

Requirements

- [x] This needs to be done in UAT first

**Subject Name:** TIMS for Poshan Sathi
**Subject Type:** 	User Subject Type
**Form Name:**	Training

- [x] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=1364496765#gid=1364496765)
- [ ] [Visit Scheduling](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=2036643668#gid=2036643668&range=19:19) **Not to do right now**

### Tech notes

- [x] As soon as as subject type is created, subjects for all the users will be created automatically
- [x] Only Poshan Sathi User group will have access to this subject type
- [ ] Add encounter eligibility check to hide the unplanned visit when there is at least one completed visit in the profile. **Not to do right now**

**Comment by Dinesh2019** [comment]
Since we have the bug card for disabled users: https://github.com/avniproject/avni-webapp/issues/1158

we have not tested the card under disabled users and I think this will be a blocker since I believe they will not use disabled users.
