### ISSUE TITLE
APF rule failure

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#320]

**Comment by Dinesh2019** [comment]
@sachsk still we have 17 rule failure

**Comment by sachsk** [comment]
@Dinesh2019 close that rule failure and test

**Comment by Dinesh2019** [comment]
QA refrences : 

<img width="1397" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem5RQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9bb9fe71faddb6e39c98ddd30280d1062ac75f9/Screenshot%202024-07-11%20at%204.45.26%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 4.45.26 PM.png" />
