### ISSUE TITLE
APF Phase 2| Removal of unplanned visits.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#324]
Remove the below listed unplanned visits from the following:
COPY RULE FROM DEV TO UAT

1. Pregnant Women
- [x] Delivery
- [x] QRT PW
- [x] PW Home Visit

2. Child
- [x] Growth Monitoring
- [x] QRT Child
- [x] Child Home Visit
- [x] NRC

**Comment by Dinesh2019** [comment]
Tested in apfodisha_dev
