### ISSUE TITLE
[APF Odisha] TIMS - Add a new dynamic offline card on the main dashboard of the poshan Sathi

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#326]
### Context

The visit for Poshan Sathi user is supposed to be scheduled on the 1st of every month

### Tech task 

- [x] Create a card - "Monthly Training Done?" on the main/home dashboard for Poshan Sathi user group
- [x] This card should be in red colour when there is no visit filled for existing month
- [x] And Green in case it is done
- [x] It need not show any count but clicking on it will take to the user subject's profile
- [x] Sample is given over here - https://avni.readme.io/docs/offline-reports#nested-report-cards

**Comment by Dinesh2019** [comment]
QA Reference video 



[Uploading... Screen Recording 2024-07-13 at 11.16.01 AM.mov]
