### ISSUE TITLE
APF Odisha Phase 2|TIMS: Training Form and Training Completion Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#327]
**Training Form** 

- [x] Changes to be done in APF Odisha Dev organisation
- [x] Need to add a validation rule in this form that : **Allow filling this form only once a month. In the same month, this form shouldn't be allowed to fill twice**. eg In the month of July, if this form is filled once, poshan sathi should not be able to fill this form again in July

**Training Completion for {Previous Month} Form**
- [x] This is a new form ad needs to be developed in APF Odisha Dev organisation
- [x] This is a new form which will be filled by the Poshan Sathi on a monthly basis on submission of the Training Form
- [x] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=266444487#gid=266444487)
- [x] The form name should capture the previous month name in the form title. eg this form scheduled in August 1st, the name of the form should be **Training Completion - for July 2024**

- [x] For Visit Scheduling Logic, please refer to[ this link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=2036643668#gid=2036643668&range=21:21)
- [x] Schedule this form, only if in the Training form, response to question "Training Required" is answered as "Yes"

**Comment by adamsanadi6** [comment]
@Dinesh2019 As discussed I have handled the following cases. cc: @AnjaliBhagabati 

- [ ] If `Training Completion` is scheduled but not completed, then do not show the unplanned visit for `Training`.
- [ ] If `Training Completion` is Cancelled then show the Unplanned visit for `Training`.

**Comment by Dinesh2019** [comment]
Refer video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f789571e9c19120d701fce8cd3185120bfc5a34/My%20Movie.mp4
