### ISSUE TITLE
APF Prod Bug fixes - Batch 1 : High Risk Count Not Displaying In Poshan Sathi Offline Dashboard

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#329]
- [x] **Changes to be done in APF Odisha New UAT environment**
- [x] The count of high-risk pregnant mothers is showing as zero on the dashboard, despite having high-risk mothers registered in Avni

User Id :6370247811@apfodisha
Role : Poshan Sathi
Beneficiary name : Lata Naik

https://drive.google.com/open?id=1GDYJ1RopeGusP7BQ28Q2bjyL3uePB_K2
https://drive.google.com/open?id=1Nn0AhMMyj32cJqMFSnCXRd3n1Ib0BH0m 
https://drive.google.com/open?id=1pYBVvBujDts_j2yHMsa9w4xNHM2Lh7ti"

### Changes to be made

- [x] Delete this card - "High Risk Pregnancy (pregnancy program)"
- [x] This card is used in Poshan Sathi Dashboard, remove it and instead use the card "High risk pregnancies"

**Comment by Dinesh2019** [comment]
As discussed we need confirmation from cilent
