### ISSUE TITLE
[APF] Field visit feedback-2 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#33]
- [x] Add following as answers to coded concept "NRC center" 
Nabrangpur (Umerkote & Nabrangpur)
Rayagada (Rayagada & Gunpur)
Sundergarh (Bonai, Rourkela & Sundergarh)
Mayurbhanj (Karanjia, Betanoti, Kaptipada & Baripada)

- [x] Update High Risk condition "Age at marriage is less than 19 years" in ANC - 
Add a check if Gravida > 1 then do not add this high risk condition.

**Comment by AchalaBelokar** [comment]
Update High Risk condition "Age at marriage is less than 19 years" in ANC -
Add a check if Gravida > 1 then do not add this high risk condition.
