### ISSUE TITLE
APF Prod Bug fixes - Batch 1 : Unable to fill out the PNC form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#330]
- [ ] **Changes to be done in APF Odisha New UAT environment**
- [ ] The below users are unable to fill out the PNC form during the grace period, which is two days after the scheduled date. However, she has canceled the PNC follow-up-1 to continue with the next visit.

User Ids :9348608356@apfodisha , 9438145474@apfodisha , 7894731019@apfodisha
Role : Poshan Sathi
Beneficiary names : Balma Munda, Sukanti Oram, Lipa Giri

https://drive.google.com/file/d/1RK1ogG3sfkkHB3OJ3arCnMW5dMH1eItr/view?usp=sharing
https://drive.google.com/file/d/1085hOVo9Pv7WUXyjulH4IZTafyX_jYS2/view
https://drive.google.com/open?id=1JMSAAVHdatc8yQGL7OLTmeFtrJt3r1cb"

**Comment by nupoorkhandelwal** [comment]
Similarly, @AnjaliBhagabati Overdue period is 2 days, if user is not filling it before this duration, it won't allow to complete and proceed further.

**Comment by AnjaliBhagabati** [comment]
closing this card as it is not a bug
