### ISSUE TITLE
APF Prod Bug fixes - Batch 1 : The ANC visit is showing as a backlog even though it is scheduled for July 1st

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#331]
- [x] **Changes to be done in APF Odisha New UAT environment**

- [x] The ANC was initially scheduled for July 2nd, but it was already completed on June 7th. However, the visit is still showing as scheduled for July 2nd and as a backlog.

User Id : 9337672625@apfodisha
Role : Poshan Sathi
Beneficiary name : Kumadini Keskerika

https://drive.google.com/file/d/17qlIM_PWRGulIR7IzNkDTlaDguOPXO7J/view?usp=sharing

- [ ] The ANC visit is showing as a backlog even though it is scheduled for July 1st.

User Id : 7012959563@apfodisha
Role : Poshan Sathi
Beneficiary name : Gouri Kushulia

https://drive.google.com/open?id=1bJj-PjSUgpRQg--hdE1Xx8M8XM_6VZmN"

### Tech Tasks to fix the above issue:

- [x] Need to change the overdue days from 7 days to last day of the month. The vist should get Overdue on last day of the month
- [x] [ Visit Scheduling](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=2036643668#gid=2036643668&range=3:3)

**Comment by nupoorkhandelwal** [comment]
As discussed with @AnjaliBhagabati currently, overdue for ANC is 7 days. Hence, visits for 1st & 2nd July are showing up as Overdue/Backlog post 7th July.

**Comment by AnjaliBhagabati** [comment]
Updated the card, need to:

 

- [ ] Need to change the overdue days from 7 days to last day of the month. The vist should get Overdue on last day of the month

**Comment by Dinesh2019** [comment]
QA refrences video :


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--355ab4347c87b21c1f2bdc240be218b314e16f82/Screen%20Recording%202024-07-15%20at%2011.11.58%E2%80%AFAM.mov
