### ISSUE TITLE
Open APF Prod Bug fixes - Batch 1 : Delivery form is not showing

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#332]
- [ ] **Changes to be done in APF Odisha New UAT environment**

- [ ] The delivery form is not showing for the beneficiaries listed below.

User Id :  7012959563@apfodisha , 7397625981@apfodisha (The user has filled delivery form from unplanned visit)
Role : Poshan Sathi
Beneficiary name : Gouri Kushulia, Labanya Dei Sunani

https://drive.google.com/file/d/1mc2z41HQRXQvZqpbuwd7iYSMluF7RE5Y/view?usp=sharing
https://drive.google.com/open?id=1PmkzkT0OnYLnAo-19dPGTp5It_HHp5ip
https://drive.google.com/open?id=1ssE10rjmfVfyKsI2B92ERmKEndhJoemE"

**Comment by nupoorkhandelwal** [comment]
As discussed with @AnjaliBhagabati , the Enrolments shared are done before Phase 2 changes, so its an old issue which is not happening right now, To fix it user can edit the Enrolment , this should schedule the Delivery form.

**Comment by AnjaliBhagabati** [comment]
closing this card as it is not a bug
