### ISSUE TITLE
APF Odisha: Testing APF Odisha NEW UAT org setup

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#334]
- [ ] Need to test the new org setup of APF Odisha New UAT
- [ ] Currently no individuals are added, so need to add individuals and test

**Comment by Dinesh2019** [comment]
@sachsk @AnjaliBhagabati as discussed we are creating the separate card for testing the entire visit scheduled

**Comment by Dinesh2019** [comment]
@sachsk @AnjaliBhagabati as discussed we are creating the separate card for testing the entire visit scheduled
