### ISSUE TITLE
APF Prod Bug fixes - Batch 1 : Move APF Prod Bug fixes done in batch 1 to production

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#337]
- [x] Changes to be moved from APF Odisha New UAT environment to APF Production environment for the below two cards
- [x] Need to move the changes made in the below cards
- [x] [Card 1](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/331)
- [x] [Card 2](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/329)
- [x] Changes to be moved from APF Odisha Dev environment to APF Production environment for the below two cards
- [x] [Card 3](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/324)

**Comment by nupoorkhandelwal** [comment]
Changes done via bundle upload

**Comment by Dinesh2019** [comment]
QA Refrences video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbbd195d4ddfe35b681cc9b0df07ab2d41092d14/My%20Movie.mp4
