### ISSUE TITLE
[APF Support] Script to move UAT data to Prod for a user

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#34]
https://avni.freshdesk.com/a/tickets/2307

The UAT user - 9692117413@apfodishauat has entered data on UAT and needs to be moved on APF prod org -
**9692117413@apfodisha**. the script should update the org and audit details for all this data.

**Comment by utkarshavni** [comment]
@nupoorkhandelwal  @arjunk  what are we supposed to do for this card - i have not heard anything from Jagadisha also on this.
