### ISSUE TITLE
APF Prod Bug fixes : Growth Faltering Status Showing Incorrectly

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#340]
- [ ] Changes to be done in APF Odisha New UAT environment
 - [ ] If the weight remains the same in two consecutive Growth Monitoring visits, then the nutritional status should be considered as GF1. However, in Avni, It is shown as Normal

User ID : 8260522158@apfodisha, 7326862292@apfodisha
Role : Poshan Sathi 
Beneficiary Name : Prabhu prasad Naik, Arpita Behera

https://drive.google.com/open?id=11mv5Hvp2JcziAaVOLc-kjM9zNytJHwEI
https://drive.google.com/open?id=1_7hWSDYzwI4JYB0OY-UoYWo-odvIQGxT
https://drive.google.com/open?id=1q38tSeVJM858PoHIHqs4Bmy8GYUi7gjW 
https://drive.google.com/open?id=1WLDl5bz-ytmbvFx2eCZ35bjDDSMYqP-A

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati keeping the card on hold since it is client dependent
