### ISSUE TITLE
APF Phase 2| UAT Feedback: Change in NRC Discharge Form and its Visit Scheduling

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#349]
- [x] Changes to be done in APD Odisha Dev
- [x] Need to **remove this logic** from the visit scheduling of NRC Discharge form "Schedule NRC Discharge form if the Admission Status in the NRC Admission form the status is "Cured and Discharged"

This NRC discharge form should get scheduled irrespective of the Admission Status in the NRC Admission form. 

- [x] Please refer to this link for the[ Visit Scheduling Logic ](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=2036643668#gid=2036643668&range=18:19)
- [x] Changes in the form are highlighted in yellow
- [x] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=1029511348#gid=1029511348)

**Comment by Dinesh2019** [comment]
- [ ] Height is not captured in QRT  form

Refer to the screenshot :

<img width="366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGtVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6bc618672e66e1a1c46dc2ce02fc53549b9badf/Screenshot%202024-07-27%20at%201.41.07%E2%80%AFPM.png" alt="Screenshot 2024-07-27 at 1.41.07 PM.png" />

- [ ] And the Child's Home Visit is not scheduled as expected

**Comment by adamsanadi6** [comment]
- For **Height is not captured in QRT form**: The syntax of js was incorrect; the declaration of the variable `obs` was incorrect.
- The visit schedule logic was not updated according to the new requirement.

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here for video](https://drive.google.com/file/d/1VHe4x96797fqMJ29KYPjxQWAmOKTdzYw/view?usp=drive_link)
