### ISSUE TITLE
[APF] Minor changes through support ticket

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#35]
Make the following changes on APF Odisha UAT -

- [x] Is the child registered under poshan tracker? 
Answers - Yes/No
Mandatory - False

Add the above question in Pregnancy and Child enrolment forms
https://avni.freshdesk.com/a/tickets/2342

- [x] Make this field as optional/non-mandatory - Date of discharge from NRC

Check there is no such error coming even if no value is selected - Date of discharge from NRC cannot be after today's date 

- [x] Check there is no error coming even if the user has not entered any value on "Date of Discharge" in "QRT SAM Child" form.

https://avni.freshdesk.com/a/tickets/2341

**Comment by AchalaBelokar** [comment]
- [ ]  validation is required for this field.
