### ISSUE TITLE
APF Phase 2| UAT Feedback: Change in NRC Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#350]
- [x] Changes to be done in APF Odissa Dev Organisation
- [x] NRC form will be now two separate form which change in the visit scheduling logic. The questions are same but we are separating it into two forms. A few changes are suggested which are highlighted in Yellow in the form

1. [NRC Admission Form](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=287957931#gid=287957931)
2. [NRC Discharge Form](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=1029511348#gid=1029511348)
3. Visit Scheduling for NRC will be now as mention in [this link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=2036643668#gid=2036643668&range=17:19)

### Tech notes-

- [x] There is already an NRC form on Dev env, use it as NRC Discharge, since the visit scheduling implemented is same as the given requirement.
- [x] Also, hide both the forms from unplanned visits

**Comment by AnjaliBhagabati** [comment]
@manish-sd have updated the scheduling logic

**Comment by Dinesh2019** [comment]
@manish-sd @AnjaliBhagabati as discussed only tested the form we have the separate card for visit scheduling

**Comment by AnjaliBhagabati** [comment]
@Dinesh2019 @manish-sd have created this card for Visit Scheduling and change in the NRC DIscharge form 
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/349
