### ISSUE TITLE
APF Prod Bug fixes - Batch 2: Disable Overdue logic (On Overdue, don't allow user to enter data) in ANC and Growth Monitoring Form until client confirms

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#351]
- [x] Changes to be done in APF Odisha New UAT environment
- [x] Since currently a lot of old ANC and Growth Monitoring visit are still showing due with the old visit scheduling logic, APF team is finding it difficult to fill the form. After discussing with the APF team, they have asked to disable the Overdue logic of "don't allow user to enter data." for sometime now until their program stabilised on the field
- [x] **Disable the logic : "On Overschedule, don't allow user to enter data" in both ANC and Growth Monitoring Form**

### Tech tasks

- [x] Comment the rule for now.

**Comment by Dinesh2019** [comment]
Refrences video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEQ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccadcce032bd9e0bfc297fa5d82bbceada9a1296/My%20Movie.mp4
