### ISSUE TITLE
APF Prod Bug fixes - Batch 2: Move the bug fixes in the card to APD Odisha Dev

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#364]
- [x] Changes to be moved to APF Odisha Dev organisation
 - [x] Please move the changes made in the below two cards

- [x] [Card # 351: ](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/351)APF Prod Bug fixes - Batch 2: Disable Overdue logic (On Overdue, don't allow user to enter data) in ANC and Growth Monitoring Form until client confirms

 

- [x] Card #343: APF Prod Bug fixes - Batch 2: QRT Child Should Get Scheduled Immediately on Completion of Growth Monitoring

**Comment by Dinesh2019** [comment]
ANC logic is missing in the dev till the overdue is shows for 7 days instead of 30 days.

**Comment by Dinesh2019** [comment]
Refer video : 


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzRRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--507ba9aaf3a478eebe10df5290e61b50fd7071d0/My%20Movie.mp4
