### ISSUE TITLE
[APF] Changes for QRT users

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#37]
# Initial rules configured for Adding decision "High Risk"
- [x]  Adding decision "High Risk" as yes/no via decision rule in following forms on respective conditions-

1. Registration form - Add registration decision as High risk - "No" 
2. Pregnancy enrolment - If no other High risk condition is true then add High risk as "No" else "Yes"
    Child enrolment - default high risk as "No"
3. ANC followup - If no other High risk condition is true then add High risk as "No" else "Yes"
4. Child followup - Weight for Height Status is SAM / Weight for age Status is Severely Underweight

- [x] Write a script to - 

1. Add High risk - "No"  in registration decision for all individual subject type( Exclude other subject types)
2. Add registration decision "High Risk" - "Yes/No" via script for all the individual subjects based on the conditions mentioned in the first point

- [x] Remove access to sync/view other subject types ie. HH, AWC and Village  for QRT users group and remove individual registration permission

- [x] Script to update individual subject_type table to have High Risk concept as the sync concept 1.

- [x] Script to update sync settings for all the users except in user group - Poshan  to have sync settings - High risk -Yes and No both

- [x] Script to update sync settings for all the users in user group - QRT  to have sync settings - High risk -Yes 

# Details of data change to be done to handle new requirement
### Presupposition for making the data change:
1. for pregnancy High Risk Conditions (coded concept) is already available (This was not known to us earlier)
2. for child Weight for age Status and Weight for Height Status is already available 

### Logical steps to make the required data change
1. Program encounters - If there is a non-empty array on encounter type 'ANC' for concept "High Risk Conditions", then add an observation "High Risk" = "yes". If not, add "High Risk" = no.
                        for child Weight for Height Status == "SAM" or  Weight for age Status == "Severely Underweight"

2. Program enrolment - Populate the latest (by encounter date time) value of "High Risk" in program encounters of type ANC to the program enrolment
                       for child take child Followup

3. Program enrolment - If High risk not available then set as High risk no

4. Individual - Populate the latest (by enrolment date time) value of High Risk from program enrolment into observations of registration

5. Individual - If High risk not available then set as High risk no

6. Sync attributes - Populate sync attributes of all individual, program_enrolment and program_encounter tables with the "High Risk" observation on individual. Here, do not limit to specific programs or encounter types or voided

### For user and sync setting
1. update subject_type table and sync_registration_concept_1 as high risk (uuid) and sync_registration_concept_1_usable as true for Individual.
2. update user sync setting add high risk as yes for qrt and for poshan sathi as yes and no

### Changes to rules
1. Add "High Risk" to encounter and enrolment decisions as well
for pregnancy
    add "High Risk" in decisions rule in  pregnancy_enrollment and ANC encounter
for child
    add "High Risk" in decisions rule in chilld_enrollment and Child Followup encounter 

## Implementation tasks:

- [x] 1. take dump of prerelease sql dumps //Skipped, use prereleasedb instead
- [x] 2. apply dump to local db //Skipped, use prereleasedb instead
- [x] 3. write psudo code  [link](https://github.com/avniproject/apfodishanutrition/blob/main/migrations/highrisk_sudo.txt)
- [x] 4. get psudo code review 
- [x] 5. test case for validation
- [x] 6. get test case review
- [x] 7. write code/query as per pusdo code [link](https://github.com/avniproject/apfodishanutrition/blob/main/migrations/highrisk_query.sql)
- [x] 8. write test code/query as per test case
- [x] 9. Execute sync query. [link](https://github.com/avniproject/apfodishanutrition/blob/main/migrations/sync_for_qrt_and_poshan.sql)
- [x] 10. execute code query.  (prerelease : [link](https://github.com/avniproject/apfodishanutrition/blob/main/migrations/highrisk_prerelease.sql) ) 
- [ ] 11. ensure test succeed 
- [ ] 12. send it for qa on prerelease
- [ ] 13. deployed to prod 
- [ ] 14. test on prod

**Comment by arjunk** [comment]
This card is currently blocked due to  this platform dependency https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/509

**Comment by utkarshavni** [comment]
@nupoorkhandelwal  Moving this to Ready now as the release has happened.

**Comment by mahalakshme** [comment]
Regarding this task: "Script to update individual subject_type table to have High Risk concept as the sync concept 1 " - need to do for encounter, program_enrolment, program_encounter, entity_approval_status tables as well - only then it will sync correctly for the existing catchment.

**Comment by vedfordev** [comment]
need more clarification how to set sync_concept_1_value like based on latest_encounter or any other condition

**Comment by mahalakshme** [comment]
latest value of high_risk condition of the individual need to be taken(need to consider all cases of wherever it is configured to get updated - registeration, enrolment, encounter) and need to update that value in sync_concept_1 column  in the above mentioned tables.

**Comment by vedfordev** [comment]
Added steps and script for update statement.
https://github.com/avniproject/apfodishanutrition/blob/main/migrations/apfodishamigration.sql

**Comment by Dinesh2019** [comment]
1.Registration form - always by default the high risk - No
2.Pregnancy enrolment - only if the Red flag as per MCP card - yes then consider as High 
3.Other than yes it is considered as normal or non - high-risk indvidual
3.ANC follow up - if the weight is less 37 or height is less than 148(which is taken form the pregnancy enrolment) or if red flag as per MCP card is yes (which is taken form the pregnancy enrolment)
0r Gravida is greater than 4 or age is greater than 35 (which is taken from the individual) ot if HB is less than 7 g/dL or Pregnancy geographically high risk is yes is consider as high risk
4.Child followup ----> if the child weight is comsider as SAM and severly underweight then we consider as high risk
---------------------------------------
QRT user - only able to search or see the individual details
proshan --- user have the all the accesss
