### ISSUE TITLE
APF Prod Bug fixes - Batch 4: CMAM-related question is not being asked to a SAM child who has opted for 'treatment at home' in the Growth Monitoring form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#376]
- [x] Changes to be done in APF Odisha New UAT environment

For Beneficiary, Rosan Mahanta, **Issues**:
1. Growth Monitoring should have been scheduled on 1st August as per current scheduling logic
2. Since this is the 1st Growth Monitoring, the question "Is the child enrolled in the CMAM program?" show basis the condition given in the solution analysis sheet

- [x] For the logic of this question, please refer to [this sheet](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=960251287#gid=960251287&range=21:22)

**Steps to reproduce:**
1. User ID : 9668786491@apfodisha
2. Child Program
3. Search Beneficiary Name: Rosan Mahanta
4. Action:

- Complete all old Child Follow Up Visits, scheduled till July 20th, 2024 basis old scheduling logic
- On completion of July 20th, 2024 visit, Growth Monitoring got scheduled on July 31st

Reference: 
https://drive.google.com/file/d/13mtMDt--8oWasZff85zaLfRLad0pGIPM/view?usp=drive_link

### Tech notes
It seems the rule is failing for 1st Growth Monitoring, this field - **"Is the child enrolled in the CMAM program?**" should be displayed in the first encounter

**Comment by adamsanadi6** [comment]
After debugging the issue, I discovered it was not a bug and closed the card.

**Comment by adamsanadi6** [comment]
**Old Logic:**
```
'use strict';
({params, imports}) => {
    const programEncounter = params.entity;
    const moment = imports.moment;
    const formElement = params.formElement;
    const _ = imports.lodash;
    let visibility = true;
    let value = null;
    let answersToSkip = [];
    let validationErrors = [];

    const condition11 = new imports.rulesConfig.RuleCondition({programEncounter, formElement}).when.valueInEncounter("2f136d99-f500-4710-89fe-d8007c977843").containsAnswerConceptName("397f526d-9247-4b3b-bb09-27c4e21fd062").matches();
    let totalEnc=programEncounter.programEnrolment.getEncountersOfType('Growth Monitoring');
    let completedEnc= _.filter(totalEnc,enc=> enc.encounterDateTime != null)

  visibility = condition11 && (completedEnc.length % 4 == 0);
  


    return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, value, answersToSkip, validationErrors);
};
```
