### ISSUE TITLE
[APF Support] Improve offline dashboard reports card performance

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#38]
Make the suggested changes by Vinay in the offline report cards

**Comment by Gojo-Taqi** [comment]
[https://app.zenhub.com/files/530146328/af9de97b-881e-4c31-b4e7-98323a61c88a/download](https://app.zenhub.com/files/530146328/af9de97b-881e-4c31-b4e7-98323a61c88a/download)
