### ISSUE TITLE
APF Prod Bug fixes - Batch 3: Child enrolment count is not showing in the offline dashboard

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#381]
- [ ] Changes to be made in APF UAT environment
- [ ] Child enrolment count is not showing in the offline dashboard for Poshan Sathi. This is happening for all users
- [ ] Attached is the error<img width="1230" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUlsQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9998e007dababfe614a7e2ff08c358b5110c3e4a/Screenshot%202024-08-01%20at%2013.51.56.png" alt="Screenshot 2024-08-01 at 13.51.56.png" />

**Comment by sachsk** [comment]
its fixed, 
issue: developer by mistaken updated some code in the form
