### ISSUE TITLE
APF | Post go-live changes: Batch 2: Offline dashboard card optimisation (Pregnancy due and overdue visits) dashboard 

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#383]
do this on Pre-release

- [x] Current Pregnant Women     
- [x] Due visits for ANC         
- [x] Due visits for Delivery    
- [x] Due visits for PNC         
- [x] Lactating Mother           
- [x] Overdue visits for ANC     
- [x] Overdue visits for delviery
- [x] Overdue visits for PNC

**Comment by vedfordev** [comment]
@sachsk please do code review

**Comment by sachsk** [comment]
in all report add--> Filter in realm
for lactating mother take only mother with normal delivery 
for taking only unique individual check this realm query instead using the SET but test it ` .filtered('TRUEPREDICATE sort(programEnrolment.individual.uuid asc , encounterDateTime desc) Distinct(programEnrolment.individual.uuid)')`

**Comment by vedfordev** [comment]
@sachsk / @Dinesh2019 / @AnjaliBhagabati 

1. In below situation I am unable to test. So please add it in appropriate env and test.
   1. currently in prerelease anc is not available.
   2. address filter value given but dashboard doesn't have the filter
   
2. Also as per @sachsk I changed logic of **Lactating Mother** from **!= 'Still birth'** to **= 'Normal delivery'**

**Comment by vedfordev** [comment]
@Dinesh2019  To resolve issue 1-i  from my previous message @sachsk suggested to do changes in prod **apfodisha_dev** . I checked anc showing correctly. So, please test other in same.
