### ISSUE TITLE
APF Prod Bug fixes - Batch 4: ANC visit scheduled twice in the same month for this beneficiary

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#385]
- [ ] Changes to be done in APF Odisha New UAT environment

| Expected Behaviour                     | Current Behaviour                                     |
| -------------------------------------- | ----------------------------------------------------- |
| Schedule only one time on 1st of month | Getting schedule two times, on last date of the month |

**Steps To Reproduce**
Assign Catchment: Sanjukta Barik
Goto Beneficiary: Rujali Naik
Enrolled on July 18th, 2024

**Issue:**
ANC visit got scheduled twice on 31 July, 2024

User ID: 8260522158@apfodisha
Role: Poshan Sathi
Beneficiary name : Rujali Naik

https://drive.google.com/open?id=1EYVB2KHe1vwSpXVh-kz-T06ICj3qKJU-

**Comment by sachsk** [comment]
I am unable to reproduce this issue. I suspect it may be related to a timezone problem in the visit scheduling. I have resolved the visit scheduling for ANC and growth monitoring.
Also setup an alter to monitor this duplication of ANC :https://reporting.avniproject.org/question/3656-individual-with-more-than-1-anc-visit-in-a-month

**Comment by sachsk** [comment]
Made the following changes:
1. Added the 6 hours in the earliest visit in :ANC, ANC cancel,Growth monitoring, Growth Monitoring cancel, pregnancy enrolment, Child enrolment.
2. Changed the return from getAll to getAllUnique('name'); in ANC scheduling
