### ISSUE TITLE
APF | Post go-live changes: Batch 4: Fix address bug in the offline dashboard cards

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#387]
**Issue** 
 In the current implementation, all subjects are registered at the village level, but the 'AWC Profile' is registered at the **AWC** level. As a result, when users select 'AWC' in the offline dashboard filters, all reports except the AWC profile break. Conversely, if the village is selected, the AWC profile breaks.

Fix this on pre-release 

**To fix above issue we have to do some changes in the report queries refer below code:**
1. make  addressValue as array  with empty initialisation.
2. check array length in if condition while assigning values;

`'use strict';
({params, imports}) => {

    let addressValue =[];

    if (params.ruleInput) {
        let addressFilter = params.ruleInput.filter(rule => rule.type === "Address");

        if (addressFilter.length > 0 && addressFilter[0].filterValue) {
            addressValue = addressFilter[0].filterValue.filter((add) => add.type == "AWC").map(add => add.name);
        }
    }

    const addFilter = addressValue.length > 0?addressValue.map(name =>   `lowestAddressLevel.name = '${name}'`).join(' OR '):'voided=false';

    let lst = params.db.objects('Individual')
            .filtered(`voided = false AND subjectType.name = 'AWC Profile'`)
            .filtered(`${addFilter}`);

     return lst;
};`

**Comment by vedfordev** [comment]
## Developer Note :

#### Presupposition :
1. have to work on report card which have filter.


#### Task Done:
1. First Tested **Total AWC Profiles Registered** . It was not working as expected after applying filter then find that sample query has spelling mistake on **lenght** . So corrected it and tested worked fine for both kind of address.
2. Based on task 1 and presupposition apply same logic in other report card.


@sachsk please find above.
