### ISSUE TITLE
[APF Odisha] High risk check missing in the phase 2 dashboard reports - 2024

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#390]
- [ ] Ideally we should have used jinja template for High risk conditions to be filtered in the superset reports since High risk conditions come as string concatenated value.
- [ ] It has been done properly in this report - https://reporting-superset.avniproject.org/superset/explore/?form_data_key=iB__G1fhzQhK_bIAie-c_1v10yo085jtoMfmeFrxKlO7A3sYuwHVpuvHZJbWwCza&slice_id=269
- [ ] Add the same check in the other pregnancy reports wherever High risk conditions are filtered. Add the list of the reports updated in this card --
------------------------

- [ ] 1. [[Phase 2][APF Odisha Prerelease] Clinically High Risk Pregnant Women [Do Not Use]](https://reporting-superset.avniproject.org/superset/dashboard/131)
- [ ] 2. [[Phase 2][APFODISHA PRERELEASE] PW QRT Visit[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/105)
- [ ] 3. [[Phase 2][APF ODISHA][PRE RELEASE] PNC VISITS [New][Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/112)
- [ ] 4. [[Phase 2][APFODISHA PRE RELEASE] PW Home Visit Details[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/109)
- [ ] 5. [[Phase 2][APF Odisha Prerelease ] ANC done for PW women[Do not Use]](https://reporting-superset.avniproject.org/superset/dashboard/116)
- [ ] 6. [[Phase 2][ APF Odisha Prerelease ] EDD Timegap [Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/130)
- [ ] 7. [[Phase 2][APFODISHA Prerelease] Trimester Wise PW Registration[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/101)
- [ ] 8. [[Phase 2][APFODISHA Prerelease] Delivery Details[Do not Use]](https://reporting-superset.avniproject.org/superset/dashboard/120)
- [ ] 9. [[Phase 2][APFODISHA][NEW] Delivery Location[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/122)
- [ ] 10. [[Phase 2][APFODISHA][NEW] ANC DETAILS[Do not Use]](https://reporting-superset.avniproject.org/superset/dashboard/119)
- [ ] 11. [[Phase 2][APFODISHA]Sector-wise Distribution of Women Availed Benefits Under Mamta[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/92)
- [ ] 12. [[Phase 2][APF Odisha Prerelease] [APF Odisha] EDD Vs Actual Delivery[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/121)

**Comment by adamsanadi6** [comment]
The high-risk filter is already included in the following reports, so I did not make any changes to them: 

1. [[Phase 2][APF Odisha Prerelease] Clinically High Risk Pregnant Women [Do Not Use]](https://reporting-superset.avniproject.org/superset/dashboard/131)
2. [[Phase 2][APFODISHA PRERELEASE] PW QRT Visit[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/105)
3. [[Phase 2][APF ODISHA][PRE RELEASE] PNC VISITS [New][Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/112)
4. [[Phase 2][APFODISHA PRE RELEASE] PW Home Visit Details[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/109)
5. [[Phase 2][APF Odisha Prerelease ] ANC done for PW women[Do not Use]](https://reporting-superset.avniproject.org/superset/dashboard/116)
6. [[Phase 2][ APF Odisha Prerelease ] EDD Timegap [Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/130)
7. [[Phase 2][APFODISHA Prerelease] Delivery Details[Do not Use]](https://reporting-superset.avniproject.org/superset/dashboard/120)
8. [[Phase 2][APFODISHA][NEW] Delivery Location[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/122)
9. [[Phase 2][APFODISHA][NEW] ANC DETAILS[Do not Use]](https://reporting-superset.avniproject.org/superset/dashboard/119)
10. [[Phase 2][APFODISHA]Sector-wise Distribution of Women Availed Benefits Under Mamta[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/92)
11. [[Phase 2][APF Odisha Prerelease] [APF Odisha] EDD Vs Actual Delivery[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/121)

**Comment by adamsanadi6** [comment]
Jinja Template was missing in the following reports.
1. [[Phase 2][APF Odisha Prerelease ] ANC done for PW women[Do not Use]](https://reporting-superset.avniproject.org/superset/dashboard/116)
2. [[Phase 2][APF Odisha Prerelease] [APF Odisha] EDD Vs Actual Delivery[Do not use]](https://reporting-superset.avniproject.org/superset/dashboard/121)

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1nwQJvM3h1JYTtbuBxE8mpYXWU3Wz-uT3/view?usp=drive_link)

[Click here to watch video](https://drive.google.com/file/d/1GjUxCgop8UWd0gvmGfhvEr2H60c8eiK5/view?usp=drive_link)

[Click here to watch video](https://drive.google.com/file/d/1ZTEZ56MCY3kKmTBwvxFLUV2FW8kTlIMf/view?usp=drive_link)
