### ISSUE TITLE
[APF Orissa: Phase 2] New Reports UAT Feedback: GF2 Child Referral

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#392]
- [x] Changes to be made in [GF2 Child Referral ](https://reporting-superset.avniproject.org/superset/dashboard/111/?native_filters_key=q_JZMfxUpVujWH5nl-SWONqX-9xLxu0HNu60qiu204WKnu4S0X6y2oxMpv2W8v8S)
- [x] 1. Remove Linelist only Filter (Nutritional Status)
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit?gid=565502635#gid=565502635)

**Comment by adamsanadi6** [comment]
Removed the Nutritional Status filter
