### ISSUE TITLE
[APF Orissa: Phase 2] New Reports UAT Feedback: PW Home Visit Details

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#394]
- [x] Changes to be made in[ PW Home Visit Details ](https://reporting-superset.avniproject.org/superset/dashboard/109/?native_filters_key=ormsjklgbLSMcpRFp7yW_cujrHIO1rcjr0iz9IyCnchhBtqTvC1jXhh8hH_bQ49L). 
 - [x] 1. The GPS locations for PW home visits should be captured in the linelist of this report.
 - [x] Changes to be made are highlighted in Green this Report [analysis sheet](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit?gid=2132065293#gid=2132065293)

**Comment by nupoorkhandelwal** [comment]
encounter_location

**Comment by Dinesh2019** [comment]
@kameshbhariya @nupoorkhandelwal can we add the filter for GPS location which shows the individual which doesn't have the GPS location. Is this possible.

**Comment by adamsanadi6** [comment]
@Dinesh2019 We are not creating the filter for GPS location(Yes/No).
