### ISSUE TITLE
[APF Orissa: Phase 2] New Reports UAT Feedback: PNC VISITS

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#395]
- [x] Changes to be made in [PNC Visits](https://reporting-superset.avniproject.org/superset/dashboard/112/?native_filters_key=wy2tIaHIYLpuHlajK1zrs_TMn805KEPVo_yTPfqe2UHcMEWSgIMJ_0qNRf5NgsEs).  
- [x] 1. Add “PNC Visit 6 Done” in graph. 
- [x] 2. Add “PNC Visit 6 Done” in aggregate report. 
- [x] 3. Add “PNC Visit 6 Done” in linelist report
- [x] 4. Add “PNC Visit 6 Done” in filters.
- [x] 5. Add “Child Birth Weight” filter with options Normal, Low (2.5-3 kg), Very Low (<2.5kg) and add the same in linelist as well. 
- [x] Changes to be made are highlighted in Green this Report analysis [sheet](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit?gid=399235472#gid=399235472).

**Comment by Dinesh2019** [comment]
QA References : 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJ1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a18865ca9f165fa6c0c6249bfcb183a6354db662/Screenshot%202024-08-20%20at%202.27.04%E2%80%AFPM.png" alt="Screenshot 2024-08-20 at 2.27.04 PM.png" />
