### ISSUE TITLE
[APF Orissa: Phase 2] New Reports UAT Feedback: MAM Child Referral

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#397]
- [x] Changes are to be done in Pre-Release
- [x] APF Odisha Reports are in Superset
- [x] Removed Linelist Filter- Nutritional Status from [this report](https://reporting-superset.avniproject.org/superset/dashboard/114/?native_filters_key=nx7UVrsFWsNqkmDKABOPHw-K-8PBEa0u-PtXCKXlcFNgJdygYmyunMSNhx2hobtc)
- [x] [Analysis Link](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit?gid=1267571414#gid=1267571414)

**Comment by adamsanadi6** [comment]
Removed the Nutritional Status filter
