### ISSUE TITLE
[APF Orissa: Phase 2] New Reports UAT Feedback: Delivery Locations

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#398]
- [x]  Changes to be made in [delivery locations](https://reporting-superset.avniproject.org/superset/dashboard/122/?native_filters_key=OR2bA9hB1sqgEsX0EnxDlUIBqwQtq6FZaQmJgBHaBmtmxg6nWfQMSoLEVvumvvGj).
- [x] 1. Remove Number of "Pregnancy enrolled in AVNI" from both graph and aggregate report.
- [x] 2. Remove "No of deliveries" from both graph and aggregate report.
- [x] 3. Add the total number on top of the bar graph. Graphs should be in percentage.
- [x]  Changes to be made are highlighted in Red this Report analysis [sheet](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit?gid=228731731#gid=228731731)

**Comment by adamsanadi6** [comment]
@manish-sd Make the following changes:
- [x] Handle division by zero
