### ISSUE TITLE
[APF Orissa: Phase 2] New Reports UAT Feedback: ANC Details

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#399]
- [x] Changes to be made in [ANC Details.](https://reporting-superset.avniproject.org/superset/dashboard/119/?native_filters_key=UDYrRa-mDs8H103g5H8-SsnUjfWjRhv5N463Dp9_KXIPP4-2LofrHUOSW1GewUUJ)  
- [x] 1. Update the abdominal observation to  "Ultrasound taken" from both the graph and aggregate report.
- [x] 2. The stacked bar graph should be in percentage. 
- [x] Changes to be made are highlighted in Red in this report analysis [sheet](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit?gid=160445132#gid=160445132).

**Comment by adamsanadi6** [comment]
@manish-sd Please make the following changes:

- [x] The percentage value is exceeding 100.

**Comment by manish-sd** [comment]
@kameshbhariya Reverting the stacked bar to display count as percentage is not feasible.

**Comment by Dinesh2019** [comment]
- [ ] getting this error 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXF5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58e25dc081eb937afde300d5d17f77d5b21d1051/Screenshot%202024-09-05%20at%206.56.13%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 6.56.13 PM.png" />
