### ISSUE TITLE
[APF] Pregnant Women Report - Village wise

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#40]
**Report requirements:**
https://docs.google.com/spreadsheets/d/1xs13aAsS5pvVbhS53pQNbGGwZDQC0xaF/edit#gid=1393828856

**Acceptance criteria:**
Along with mentioned requirements in the sheet, there should be a Linelist when user clicks on the count.

**Comment by Dinesh2019** [comment]
When we register the individual as female and doesn't enrolled in any pregnancy program but in database under ANC count is showing as 1.
Step to reproduce
1.Login to account.
2.register the individual.

Excepted result : ANC value should be Zero
Acutal result  : ANC value shows 1
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/854c2652-2cfd-4152-80cd-5edf40583bb7)
Data base report : 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/63f99cb8-b04b-4ee5-8695-7eb76019df0e)

**Comment by Gojo-Taqi** [comment]
Fixed the No anc done count

**Comment by Dinesh2019** [comment]
When we register the individual as female and enrolled in any pregnancy program after ANC if we marked the individual under  Geographical high risk count is not capture in the database
Step to reproduce
1.Login to account.
2.register the individual.
3.Do the ANC with Geographical high risk as Yes

Excepted result : Geographical high risk should shows 1
Acutal result : Geographical high risk doesn't shows 1
Screenshot of Webapp
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/ebc598ca-acae-4f64-8bc2-95b4481f3636)

Screenshot of dB.
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/3e93ee8a-5186-474c-92db-42b8bb00f8f5)

**Comment by Dinesh2019** [comment]
@utkarshavni As we discussed when we assign the individual to geographically risk automatically the count for clinically is also added.Can you confirm with the cilent and let us know

**Comment by utkarshavni** [comment]
@Dinesh2019  Moving this to Review as the feedback has been incorporated in another card which is in Analysis.
