### ISSUE TITLE
[APF Orissa: Phase 2] New Reports UAT Feedback: Household Entitlement

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#401]
- [x] Changes to be made in [Household Entitlements](https://reporting-superset.avniproject.org/superset/dashboard/103/?native_filters_key=16UrzJzuQ0OtWxReCV7QyeC7Z1uL414K5RGc_Tfcb5yEYL3ZyzNFE9AOvAM6fBUH). 
- [x] 1. Graph should be in percentage.
- [x] 2. Total houselhold column should be added in aggregate report. 
- [x] 3. Swap the graph - entitlements can be in the filter and sectors in the x axis
- [x] Changes to be made are highlighted in Green this Report analysis [sheet](https://docs.google.com/spreadsheets/d/1H-QOuLWE827PdY-tQ6hWB3ulFCXwMeid/edit?gid=68539179#gid=68539179).

**Comment by nupoorkhandelwal** [comment]
@manish-sd Please remove total household count from the bar chart. It was only required for aggregate report
