### ISSUE TITLE
APF Prod Bug fixes - Batch 5: Nutritional Status Showing Incorrect in Production

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#406]
- [ ] Changes to be done in APF Odisha New UAT environment
 - [ ] For the height and weight entered for the below Beneficiary (Height - 70.2 Cm, Weight - 6.6 kg) the Nutritional Status should be SAM but in production it is showing as MAM.  In UAT it is coming proper. Attached are the screenshots

Beneficiary name : Sania Munda 

<img width="791" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm1BQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d60ee5b9ff153dc9cc5de2e715c3bc8856d8a7b/Production.png" alt="Production.png" />
<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnFBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd884a58c032d0b8ce9f450cfedb3e49b2af6eed/UAT.jpg" alt="UAT.jpg" />

**Comment by vedfordev** [comment]
@sachsk Please answer below :

1. what is poshan tracker ??

**Comment by sachsk** [comment]
this is because of the age so when we are calculating "Nutritional status" for different age group it will give different status.
there are two individual with same name in system with diff age so user might get confused.
Also tested with UAT and working fine.

**Comment by Dinesh2019** [comment]
As discussed with anjali we are closing this card since we didn't made any changes.
