### ISSUE TITLE
[APF Odisha]: Provide and Revoke access to the following reports.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#408]
Give access to these reports

- [x] [Phase 2][APFODISHA] Full vs Complete Vaccination
- [x] [Phase 2][APF Odisha] All Vaccination Report
- [x] [Phase 2][APFODISHA] SAM & MAM Child Referral

Remove access for this report

- [ ] [Phase 2][APF Odisha] Child Timeline
- [x] [APFODISHA] QRT Child Visit

**Comment by vedfordev** [comment]
@kameshbhariya please find below.
**[Phase 2][APFODISHA] Full vs Complete Vaccination** added apf gamma role
**[Phase 2][APFODISHA] Full vs Complete Vaccination** added apf gamma role
**[Phase 2][APFODISHA] SAM & MAM Child Referral** added apf gamma role
**[Phase 2][APF Odisha] Child Timeline** no role found
**[APFODISHA] QRT Child Visit[Do not use][Cannot be done]** removed role.
