### ISSUE TITLE
APF | Post go-live changes: Batch 1: UAT Feedback (TIMS) : Training Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#409]
- [x] Changes to be done in APF Dev Environment
- [x] New question to be added is highlighted in **Green** and changes in the existing questions are highlighted in **Yellow**
- [x] [Form Link](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=1364496765#gid=1364496765)

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here to watch video](https://drive.google.com/file/d/1lNkoK8sjvVkz8RE-F9SM5pFG4KmWirQm/view?usp=drive_link)
