### ISSUE TITLE
APF Prod Bug fixes - Batch 5: A MAM child is appearing in the SAM child dashboard

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#411]
- [ ] Changes to be done in APF Odisha New UAT environment
- [ ] Beneficiary who is found MAN in Growth Monitoring is showing under the Child - SAM Child Dashboard. It should show under MAM Children 

**Steps to reproduce:**
1. Search Individual  Siba Munda
2. Complete one Growth Monitoring where heigh and weight is equivalent to MAN
3. Once completed this child should show under MAM Children Offline dashboard card

**Reference**

User ID: 7846919141@apfodisha
Role: Poshan Sathi
Beneficiary name : Siba Munda

https://drive.google.com/open?id=19Z3sbXaCDPEC_wdKu39nclONCZX_ZLqp
https://drive.google.com/open?id=1KCvRVs1zej8EZ7WkeNNXYlqdziTMFVAk

User ID : 9337754655@apfodisha
Role : Poshan Sathi

https://drive.google.com/open?id=1KLT3YakhvwXi1yi2PR-bn8z6T-EvCxk4
https://drive.google.com/open?id=1dpAQBtLAs81tWcUS1Vjb-IGq1FS75snB

**Comment by sachsk** [comment]
report is working fine as per the logic
If an individual's last visit was a "QRT child" visit, it will check their "Weight for Age Status." If they are classified as "Severely Underweight," they will be considered as having SAM . And if their most recent visit was for Growth Monitoring, it will check their "Weight for Height Status." If it indicates SAM, they will be considered a SAM child.

in given example child has latest visit QRT so report logic checking the "Weight for age Status" and its "Severely Underweight" so this child is in SAM

**Comment by sachsk** [comment]
@AnjaliBhagabati please convey this to client and close the card
@Dinesh2019 no need to do QA
