### ISSUE TITLE
{APF Report}: Issue with phase 1 report.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#413]
The users mentioned below are getting all block filter options in the Block section, however they are getting data for only their assigned block. Please ensure that only the assigned block appears in the filter options. Additionally, they are getting an extra sector, 'Khuntgaon,' in their reports, which is not part of their region.

User ID : minakhihealthnutrition@gmail.com , misnutritionmngd@gmail.com

Sample report link : https://reporting-superset.avniproject.org/superset/dashboard/114/?native_filters_key=NZWyfSXRLvxGiHvGG1RkTXXdZhriJ70qlqKLQnSZqi0u3zcjGgNX2qrpkR4UuigI

users : minakhihealthnutrition@gmail.com, 
Password: @muskan1508

**Comment by sachsk** [comment]
@AnjaliBhagabati  action item:
1. apfodisha.logistic awc this data set is not added in the RLS so need to add this data set.
2. RLS has the where clause ""Block" = 'Muniguda (Block)'" and query has column with name "Project/Block" so we have to modify the query to support RLS
3. We have to add this dataset into all RLS

**Comment by vedfordev** [comment]
## Developer Note:

#### Filter Issue:
I checked rls **"Project/Block" = 'Muniguda'** was missing. So I have added from same type of rls. I've checked 3-4 reports working fine.

#### Data Issue:
I checked that one individual [Link](https://app.avniproject.org/#/app/subject?uuid=d264fdb2-38a2-4dc0-8fa6-a0de38e36cf2) **Rihan Dharua**. Registered against **Muniguda (Block)** but when I checked his household [Link](https://app.avniproject.org/#/app/subject?uuid=23b2654c-5626-4966-9ac2-4a61f15501c5) **Sukadev Dharua** it is in **Lahunipara (Block)**. which causing issue. 


@sachsk @kameshbhariya please check above. moving card to code review ready.

**Comment by sachsk** [comment]
@Dinesh2019 test all report. check whether reports are loading or not no need to test the count or logic.

**Comment by Dinesh2019** [comment]
- [x] we have the some error in some report attached the screenshot of it 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--537435e288dd69bff944db7ac51c42b3d9fb70d6/Screenshot%202024-08-29%20at%205.58.27%E2%80%AFPM.png" alt="Screenshot 2024-08-29 at 5.58.27 PM.png" />

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0daQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3864434d7d0e4d10a1509c6a5c867c8a459a7efa/Screenshot%202024-08-29%20at%206.24.28%E2%80%AFPM.png" alt="Screenshot 2024-08-29 at 6.24.28 PM.png" />

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0taQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a98ef19411bcd7ba176328286540552747630bb/Screenshot%202024-08-29%20at%206.25.41%E2%80%AFPM.png" alt="Screenshot 2024-08-29 at 6.25.41 PM.png" />


<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1daQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--497341768a10ed746461d2bda0be09c93efa6d9a/Screenshot%202024-08-29%20at%206.26.07%E2%80%AFPM.png" alt="Screenshot 2024-08-29 at 6.26.07 PM.png" />

**Comment by vedfordev** [comment]
@Dinesh2019 As per this card, I resolved **unable to load** kind of error. In, **[APFODISHA] QRT SAM Children report** there issue related to **time out error**. which is performance issue. So create separate bug card for it.

check with achala's user in harichandrapur block
