### ISSUE TITLE
APF Prod Bug fixes - Batch 5: Household name is not showing in beneficiary profile

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#415]
- [ ] Changes needs to be done in APF Odisha New UAT environment
- [ ] For the below beneficiary, household name is registered but it is not showing in the beneficiary's profile. Other members who are added in the same household, in those members profile household name is showing
- [ ] **Household name:** Bishwanath Ashari
**Beneficiary name :** Tulasi Asari

https://drive.google.com/file/d/1cxMcePOCoYiNFoRDTgy7QNc2mAS3-f3b/view?usp=sharing
https://drive.google.com/file/d/1V_g8-ze2q47Cn69PzrPzgrJQ4Mni4tMl/view?usp=sharing
screen recording : https://drive.google.com/file/d/18tYBe4iMQECnt1g0o-L-zZryT-KmgGod/view?usp=sharing

**Comment by nupoorkhandelwal** [comment]
@AnjaliBhagabati  this is a product bug, ask shubhamita to raise a support ticket. It cannot be debugged and fixed at implementation level. Its all about how product feature is behaving
