### ISSUE TITLE
[APF Odisha] Metabase alert report - QRT visit scheduled for non QRT case

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#419]
### Context
Here, aim is to create a list of children who are not SAM/MAM ie. as per latest visit and still have a QRT visit scheduled

### Tech tasks

- [x] Create a metabase alert with link to DEA
- [x] Logic - Select all those children for whom QRT visit is scheduled and their latest enrolment decision is "To be monitored by QRT" is no, QRT visit's encounter date and cancel date are null
- [x] Other fields to be show can be used from other alert reports in APF Odisha collection

**Comment by manish-sd** [comment]
[Report Link](https://reporting.avniproject.org/question/3790-qrt-visit-scheduled-for-non-qrt-case)
