### ISSUE TITLE
APF | Post go-live changes: Batch 1: Training (TIMS) Forms to be moved to production

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#425]
- [ ] Training (TIMS) forms are on APF Odisha Dev environment
- [ ] The Training Form and Training Completion form needs to be moved to production from APF Odisha Dev environment

**Comment by dinesh2096** [comment]
QA Reference video : 

https://drive.google.com/file/d/1qes6UIAY3ABTCtNwykA4_N29pNvjaBVd/view?usp=drive_link
