### ISSUE TITLE
[APF Odisha] Bug fix -QRT is not getting scheduled for severe anemic cases, if 'ANM intervention is required' is selected as NO

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#427]
### Context
If 'ANM intervention is required' is selected as NO for a severe anemic case, then in this case iQRT is not getting scheduled

### Reference document 
https://docs.google.com/spreadsheets/d/1-b21Diro_7XdzoaP87F3iXOryd68yO2RmrXwCAT8Bpg/edit?gid=1268216104#gid=1268216104&range=3:3

**Comment by AnjaliBhagabati** [comment]
@nupoorkhandelwal Subhamita said this issue was fixed and is currently working fine. There is not beneficiary currently for whom this condition is not working as expected. 

Closing this card as it is working fine
