### ISSUE TITLE
[APF Odisha] Bug fix - Age is less than 18’ and ‘Age is greater than 36’ should be added to the high-risk indicator

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#428]
### Context
Age is less than 18’ and ‘Age is greater than 36’ should be added to the high-risk indicator, as they are not currently showing on the summary page for every ANC encounter.

[Screen recording](https://drive.google.com/file/d/1ncQKqbw_4iAcSaNnRhG4sMKev1bYVk64/view?usp=sharing)

### Reference document 
[Link](https://docs.google.com/spreadsheets/d/1-b21Diro_7XdzoaP87F3iXOryd68yO2RmrXwCAT8Bpg/edit?gid=1268216104#gid=1268216104&range=18:18)

### Tech notes 

- [ ] High risk conditions identified during Program enrolment should remain with each decision added during ANC
- [ ] Make these changes on APF Odisha New UAT

**Comment by adamsanadi6** [comment]
It looks like decision rule is behaving as expected.
[Reference Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5IQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e9c5cc25c4d2f75a76f952839ba18cab8e9c545/APF%20Odisha%20-%20ANC%20Sumary.mov)

**Comment by dinesh2096** [comment]
@nupoorkhandelwal @AnjaliBhagabati @adamsanadi6 it is working fine as expected.
