### ISSUE TITLE
[APF Odisha] Bug fix -  Height/Weight autopopulating in a QRT visit gets updated from the latest visit in Edit scenario as well

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#429]
### Context
Beneficiary name _Rinku Jakesika: [DEA link](https://app.avniproject.org/#/app/subject?uuid=da186e1a-217d-4e28-bfb6-bda6eed304ec)

The issue exactly here is that the Height/Weight autopopulating in a QRT visit gets updated from the latest visit in Edit scenario as well. It should be same when the QRT visit was first completed.

### Reference document 
https://docs.google.com/spreadsheets/d/1-b21Diro_7XdzoaP87F3iXOryd68yO2RmrXwCAT8Bpg/edit?gid=1268216104#gid=1268216104&range=20:20

### Tech notes 

- [ ] Do not update the values of Height/Weight in edit scenario
- [ ] Make these changes on APF Odisha New UAT

**Comment by adamsanadi6** [comment]
**Backup Code:**
*Height:*
```
'use strict';
({params, imports}) => {
  const programEncounter = params.entity;
  const moment = imports.moment;
  const formElement = params.formElement;
  const _ = imports.lodash;
  let visibility = true;
  let value = null;
  let answersToSkip = [];
  let validationErrors = [];

  let obs = programEncounter.programEnrolment.findLatestObservationFromEncounters('Height');
  
   if(obs)
  {
  value=obs.getReadableValue()
  }
    
    
  return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, value, answersToSkip, validationErrors);
};
```
*Weight:*
```
'use strict';
({params, imports}) => {
  const programEncounter = params.entity;
  const moment = imports.moment;
  const formElement = params.formElement;
  const _ = imports.lodash;
  let visibility = true;
  let value = null;
  let answersToSkip = [];
  let validationErrors = [];

  const weight = programEncounter.programEnrolment.findLatestObservationFromEncounters('8b187dda-a88e-487a-981a-0e4cb6142904');
  
  if(weight) value = weight.getReadableValue();
    
  return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, value, answersToSkip, validationErrors);
};
```

**Comment by dinesh2096** [comment]
Weight and height are not auto-populated 

QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1bxSsFAxc1cYXgycvzcruUWf4rq2ld4NH/view?usp=drive_link)

**Comment by dinesh2096** [comment]
- [ ] The QRT weight and height have not been updated per the latest growth monitoring. The value is taken from first growth monitoring encounter 


QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1uZVvVlDZM645CFVe_mUUhHcRk2J74GfG/view?usp=drive_link)

**Comment by dinesh2096** [comment]
QA refernce vidoe : 

[Click here to watch the video](https://drive.google.com/file/d/1wvDzUF9Fyz-15gE29GVcy0l9qfnFGx0-/view?usp=drive_link)
