### ISSUE TITLE
[APF Odisha] Bug fix - Growth monitoring that is scheduled post cancellation schedules a Growth Monitoring with 2 days overdue

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#430]
### Context
The issue - Growth monitoring that is scheduled post cancellation schedules a Growth Monitoring with 2 days overdue. This needs to be fixed as it is a bug. The overdue for the new visit should be same as it is in the completion workflow.

- [ ] Update the Growth Monitoring overdue as - moment(earliestDate).endOf('month').toDate() instead of adding 30 days, change at both the places, in completion and in cancellation flow.

### Reference document
https://docs.google.com/spreadsheets/d/1-b21Diro_7XdzoaP87F3iXOryd68yO2RmrXwCAT8Bpg/edit?gid=1268216104#gid=1268216104&range=24:24

### Tech notes 

- [x] Update the overdue in the cancel scenario to the right values as done in the completion workflow.
- [x] Make these changes on APF Odisha New UAT

**Comment by adamsanadi6** [comment]
**Backup Code:**
```
//SAMPLE RULE EXAMPLE
"use strict";
({ params, imports }) => {
  const programEncounter = params.entity;
  const scheduleBuilder = new imports.rulesConfig.VisitScheduleBuilder({
    programEncounter
  });
  
  const moment = imports.moment;
  const _ = imports.lodash;
  const cancelReason = programEncounter.findCancelEncounterObservationReadableValue("Cancel reason");
  
  const earliestDate = moment(programEncounter.earliestVisitDateTime).add(1, 'month').startOf('month').add('6','H').toDate();
  let isEditScenario = programEncounter.programEnrolment.encounters.some((enc) => 
            enc.encounterType.name === 'Growth Monitoring' && 
            enc.voided === false && 
            imports.moment(enc.earliestVisitDateTime).isSame(earliestDate, 'day')
          );
    
    if(programEncounter.programEnrolment.individual.getAgeInYears() <= 5 && cancelReason != 'Death' && cancelReason != 'Migrated to other geography' && !isEditScenario) {
        scheduleBuilder.add({
            name: 'Growth Monitoring',
            encounterType: 'Growth Monitoring',
            earliestDate: earliestDate,
            maxDate: moment(earliestDate).add(2, 'days').toDate()
        });
    }
  
  return scheduleBuilder.getAll();
};
```

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 Please update the Growth Monitoring overdue as - moment(earliestDate).endOf('month').toDate() instead of adding 30 days, change at both the places, in completion and in cancellation flow.

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch video](https://drive.google.com/file/d/1eefuZNlV2OViJMB-sMoVPBKE6TbxPzxu/view?usp=drive_link)
