### ISSUE TITLE
[APF Odisha Phase 2]: APF rule failure

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#432]
1. Check rule failure in PROD
2. Try to reproduce it on UAT
3. If its reproduced then fixed on UAT and maintain the change log.
4. If its not reproduced then check with tech lead

Note: While fixing the rule please make sure change should not affect app workflow. and fix this only on UAT

**Comment by adamsanadi6** [comment]
**Cannot reproduce the issue in UAT for Form element**
| form_name       | form_element_group_name | form_element_name                                |
|-----------------|-------------------------|--------------------------------------------------|
| Child Enrolment | Enrolment Details        | Is the child exclusively breastfed till 6 months? |
| Child Enrolment | Enrolment Details        | Is Annaprassan done for the child at 6 months?    |
| Child Enrolment | Enrolment Details        | Is the child Breast feed till 2 years?            |
| PNC Encounter   | Visit details            | JSY money received?                              |

**Comment by adamsanadi6** [comment]
**Report Card Rule Failure**

|id|name|error_message|error_count|
|--|----|-------------|-----------|
|2742|Child with age more than 5 years|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1032|
|2738|Current Pregnant Women|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|79|
|1392|Due for QRT SAM child|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|8|
|1382|Due visits for ANC|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|83|
|1394|Due visits for Delivery|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|81|
|1383|Due visits for PNC|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|81|
|1395|Due visits for PW Home Visit|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|87|
|1388|Due visits for QRT PW|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|87|
|2739|Growth Faltering-1|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1080|
|2739|Growth Faltering-1|Exception in HostFunction: No object with key '2805661933' in 'class_Observation'|8|
|2739|Growth Faltering-1|JSON Parse error: Unexpected character: a|10|
|2743|Growth Faltering-2|JSON Parse error: Unexpected character: a|10|
|2743|Growth Faltering-2|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1060|
|2743|Growth Faltering-2|Exception in HostFunction: No object with key '2805661933' in 'class_Observation'|8|
|824|High risk pregnancies|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1056|
|2740|Lactating Mother |Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|79|
|1743|MAM children|Cannot read property 'getValue' of null|14|
|1743|MAM children|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1048|
|1743|MAM children|Exception in HostFunction: No object with key '2805661933' in 'class_Observation'|8|
|1387|Overdue for PW Home Visit|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|87|
|1389|Overdue for QRT PW|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|87|
|1390|Overdue for QRT SAM child|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|8|
|1379|Overdue visits for ANC|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|81|
|1381|Overdue visits for delviery|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|80|
|1380|Overdue visits for PNC|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|79|
|823|SAM children|Exception in HostFunction: No object with key '2805661933' in 'class_Observation'|8|
|823|SAM children|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1074|
|823|SAM children|Cannot read property 'getValue' of null|13|
|817|Total AWC Profiles Registered|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1200|
|2744|Total children enrolled in CMAM program|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1026|
|822|Total enrolments in child program|Exception in HostFunction: Invalid predicate: 'voided = false AND subjectType.name = 'Individual' SUBQUERY(enrolments, $enrolment, $enrolment.programExitDateTime = null and $enrolment.program.name = 'Child' and $enrolment.voided = false).@count > 0': syntax error, unexpected subquery, expecting end of file|8|
|822|Total enrolments in child program|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1105|
|820|Total enrolments in pregnancy program|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1087|
|816|Total households registered|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1055|
|821|Total individuals registered|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1078|
|815|Total Village Profiles Registered|Exception in HostFunction: Invalid predicate: '': syntax error, unexpected end of file|1037|

**Comment by adamsanadi6** [comment]
Fixed the offline report card and form element related rule failures
![Image](https://github.com/user-attachments/assets/81b62b50-b3e8-4dce-9b3b-b1878d6b4aa3)

**Comment by dinesh2096** [comment]
@adamsanadi6  still i see rule failure in open status
