### ISSUE TITLE
[APF Odisha Phase 2]: Prod Bug fixes - Batch 6: Offline Dashboard: Wrong Cards showing in QRT Dashboard

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#434]
Doing changes on following environments -

- [x] APF Odisha Dev
- [x] APF Odisha New UAT
- [x] APF Odisha

- [x] Due Visit for QRT Child Follow Up and Overdue for QRT Child Follow Up which was removed from the QRT Dashboard (please refer to the comment in [this card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/274)) is now again reflecting in the QRT Dashboard. It was not displaying till yesterday 22.10.2024. 
- [x] QRT Intervention Required? [this card is related to Medical Facilitation](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/276) which is a part of NRC. This offline card should not have been moved to production from APF UAT environment when we moved the TIMS changes as NRC form development is still not completed as it's budget is still not approved. 
- [x] Need to void the these three offline dashboard card from QRT Dashboard.

Attached is the screenshots

<img width="274" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXBuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--110ba027725f472dedfef94f84696062543711c2/QRT%20Dashboard%2020.10.2024.jpg" alt="QRT Dashboard 20.10.2024.jpg" />

<img width="197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXRuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--831d9790cb86e9f3f4cea905f5ddb738ae35f63c/QRT%20Dashboard%2023.10.2024.jpg" alt="QRT Dashboard 23.10.2024.jpg" />

**Comment by dinesh2096** [comment]
QA Refrences : 

Prod : 

<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU50Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a04650eca9318fcca9827dd0a71471a0ebee239f/Screenshot%202024-10-24%20at%2012.16.17%E2%80%AFPM.png" alt="Screenshot 2024-10-24 at 12.16.17 PM.png" />
