### ISSUE TITLE
[APF Odisha Phase 2]: Post Go-Live Changes - Batch 3: Enable the Overdue logic (On Overdue, don't allow user to enter data) in ANC and Growth Monitoring Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#437]
- [ ] Changes to be done in APF Odisha New UAT environment
- [ ] Need to Enable the Overdue logic (On Overdue, don't allow user to enter data) in ANC and Growth Monitoring Form which we have currently disabled earlier. [Refer to this card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/351)

**Done in following forms on APF Odisha New UAT-** 

- [x] Growth Monitoring
- [x] ANC

Changes done in the below three environment

- [ ] APF Odisha New UAT
- [ ] APF Odisha Production
- [ ] APF Odisha Dev

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1a6QbtFyoQpibU9lCeEbxblglPS_qmI_o/view?usp=drive_link)

**Comment by AnjaliBhagabati** [comment]
@dinesh2096 Nupoor moved the changes to APF Production and APF Dev environment as well. Can you test it in both of them as well..Have updated the card as well

cc: @nupoorkhandelwal

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1059plNbawmOYASydM5EQ-JU-5y7aA8hl/view?usp=drive_link)
