### ISSUE TITLE
[APF Odisha Phase 2]: Prod Bug fixes - Batch 7: App Performance Fixes Deploy to Production [App changes]

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#439]
- [ ] Changes made in [this card](https://github.com/orgs/avniproject/projects/21/views/1?pane=issue&itemId=86141638&issue=avniproject%7Capfodishanutrition%7C435)

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1xljvAOlshuFnrBeZUM-hKTo7P-l46j5w/view?usp=drive_link)
