### ISSUE TITLE
[APF] Child Report - Village

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#44]
Report requirements:
https://docs.google.com/spreadsheets/d/1xs13aAsS5pvVbhS53pQNbGGwZDQC0xaF/edit#gid=2137851351

**Comment by Dinesh2019** [comment]
As discussed with Tqai data is not follows to the db

**Comment by Dinesh2019** [comment]
Getting is error while execution.

[Uploading... image.png]

**Comment by Dinesh2019** [comment]
now i unable to see the data in the db.
Test data : Individual name : Test DIN29,38 and location or address : Sukruli,Khiching,Khandiadar
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/e429bf97-01ea-45ca-b5a3-db52ac12703b)

db screenshot:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/52b5631a-0dab-4139-987b-16f13417f6ac)

**Comment by vedfordev** [comment]
@Dinesh2019 get updated query from superset and then test

**Comment by Dinesh2019** [comment]
we are figuring out how to execute and capture the #severely wasted to validate in the report. so  we are currently blocked for this card
