### ISSUE TITLE
APF Odisha Phase 2: Production Bug: Batch 6: Revert the overdue logic “ On Overschedule, don't allow users to enter data” in Growth Monitoring Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#442]
- [ ] Changes to be first done in APF UAT 
- [ ] Need to Revert the overdue logic “ On Overschedule, don't allow users to enter data” in Growth Monitoring Form as Poshan Sathi are unable to fill Growth monitoring forms that is scheduled for November 1st, 2024 as for some beneficiaries as it is showing as backlog. This is happening because October Growth Monitoring for these beneficiaries was cancelled prior to we implementing the [Bug Fix on Growth Monitoring Cancellation](https://github.com/avniproject/apfodishanutrition/issues/430)

Test Scenarios For QA

- [ ] On completion of November Growth Monitoring, next Growth Monitoring should be scheduled on December 1st and Overdue on December 31st
- [ ] On cancellation of November Growth Monitoring, next Growth Monitoring should be scheduled on December 1st and Overdue on December 31st
- [ ] On edit also the Schedule and overdue date should not change ( scheduled on December 1st and Overdue on December 31st)

**Comment by dinesh2096** [comment]
QA References : 

[Click here to watch the video](https://drive.google.com/file/d/1Cj_ah5s1OX95zrefCmBz7jSjDuJ-sQWL/view?usp=drive_link)
