### ISSUE TITLE
APF Odisha Phase 2: Production Bug Fixes Batch 7: Offline dashboard of the Poshan Sathi showing two High-Risk Pregnancies card in App version latest version 10.0.3

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#445]
- [ ] Changes to be first made in APF UAT
- [ ] Offline dashboard of the Poshan Sathi users who have updated the app to the latest version (10.0.3), two instances of the High-Risk Pregnancies card are appearing instead of one. This issue is affecting all PS users on the latest version. 

[Steps to Reproduce ](https://docs.google.com/spreadsheets/d/1IlQJZDRw4rnuEHvO9HGJvvIQ6wPrXuGH8PdksUHYbm0/edit?gid=0#gid=0&range=A62:A73)

[Screen recording  ](https://drive.google.com/file/d/1w6Opx3HU_RwqNruhv_Q2tibepOX4Ow4B/view?usp=sharing)

**Comment by nupoorkhandelwal** [comment]
Delete the one extra card and then move the changes to prod

**Comment by nupoorkhandelwal** [comment]
@dinesh2096 made change on Dev and Prod orgs.

**Comment by nupoorkhandelwal** [comment]
set role apfodisha;
update dashboard_section_card_mapping
set is_voided = true,
    last_modified_date_time = current_timestamp,
    last_modified_by_id = (select id from users where username = 'nupoork@apfodisha')
where uuid = '926a7839-8d92-4948-8a75-3f2e9be3bee8';

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1OKmIPp07P7nXfoF6-n5drriAyDilL-Ql/view?usp=drive_link)
