### ISSUE TITLE
APF Odisha Phase 2| Production Bug: The Growth Monitoring form is being scheduled for a child who has already exited the child program.

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#448]
- [x] Changes to be first made in APF UAT 
- [x] The Growth Monitoring form is being scheduled for a child who has already exited the child program. 

User ID : 9692933407@apfodisha
User role : Poshan Sathi
Beneficiary name : Priyansu Sahu (https://app.avniproject.org/#/app/subject?uuid=97415d55-4dea-41cf-9f02-de46780c8d3d)

[Steps to Reproduce the Bug:]( https://docs.google.com/spreadsheets/d/1IlQJZDRw4rnuEHvO9HGJvvIQ6wPrXuGH8PdksUHYbm0/edit?gid=0#gid=0&range=A74:A85)

**Changes to be made to fix the issue:**

- [x] On Program exit, need to add another check that "No future Visits should be scheduled if a Beneficiary exits the Child Program". Current for Child Program, future visits stops only when ind is more than 5 years
- [x] Ensure that on Program Exit, that child count should not come under the offline dashboard "Total enrolments in child program" 

#Test Scenarios:
1. On Program Exit not visits related to Child Program for Poshan Sathi or QRT should schedule
2. On Program Exit, in case any existing visit is already scheduled, on cancellation, future visits should not get scheduled
3. Offline Dashboard "Total enrolments in child program", should not show exited child count

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 add !isExited condition to Growth monitoring visit schedule, also update the same in cancel scenario.
Add the same check in all the remaining child program encounters.


@dinesh2096  Test the exited condition on all the encounters in both the programs.

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal @AnjaliBhagabati @dinesh2096 

**I have made the changes in the following forms:**

1. Delivery Encounter
2. PNC Encounter
3. PNC Encounter Cancellation
4. QRT PW
5. PW Home Visit
6. PW Home Visit Cancellation
7. Child Home Visit
8. Child Home Visit cancellation
9. Growth Monitoring
10. Growth Monitoring Encounter Cancellation
11. QRT Child

**Comment by dinesh2096** [comment]
QA Reference vidoe : 

[Click here to watch the video](https://drive.google.com/file/d/17T1C34639umsElQWYvNmRWpp3s0R_hHf/view?usp=drive_link)


Found the prod issue : 

[Click here to prod bug](https://github.com/avniproject/avni-client/issues/1546)
