### ISSUE TITLE
APF Odisha Phase 2| Production Bug Fixed Batch 7: Last month’s Growth Monitoring form is being saved even when only partially filled

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#449]
- [x] Changes to be first done in UAT

**Issue**

let age = moment(programEncounter.earliestVisitDateTime).diff(programEncounter.programEnrolment.individual.dateOfBirth,'years');

const condition11 = age > 3 ;

the above rule fails in scenario where child is 3 years and x months, age will still come as 3 only and the condition will be false, as a result THR and egg related field will keep on showing for 3 year kids till they turn 4 years old.

**Solution**

- [x] In Growth Monitoring Form, below two question, show for the age group <= 3yrs.  If child is 3.1 don't show. 

Calculate the DOB as on Schedule Date not as on Encounter/Visit Date

1. [Is the child receiving THR from AWC in last month?](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=960251287#gid=960251287&range=14:14)
2. [Is the child receiving egg from AWC in last month? ](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit?gid=960251287#gid=960251287&range=15:15)

**Comment by nupoorkhandelwal** [comment]
let age = moment(programEncounter.earliestVisitDateTime).diff(programEncounter.programEnrolment.individual.dateOfBirth,'years');
  const condition11 = age > 3 ;

the above rule fails in scenario where child is 3 years and x months, age will still come as 3 only and the condition will be false, as a result THR and egg related field will keep on showing for 3 year kids till they turn 4 years old.

**Comment by adamsanadi6** [comment]
**Backup Code:**
*1. Is the child receiving THR from AWC in last month?:*
```
'use strict';
({params, imports}) => {
  const programEncounter = params.entity;
  const moment = imports.moment;
  const formElement = params.formElement;
  const _ = imports.lodash;
  let visibility = true;
  let value = null;
  let answersToSkip = [];
  let validationErrors = [];
  
  let age = moment(programEncounter.earliestVisitDateTime).diff(programEncounter.programEnrolment.individual.dateOfBirth,'years');
  
  const condition11 = age > 3 ;
  
  visibility = !(condition11 );
  
  return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, value, answersToSkip, validationErrors);
};
```
-----------------------------------------------------------------------------
*2. Is the child receiving egg from AWC in last month?:*
```
'use strict';
({params, imports}) => {
  const programEncounter = params.entity;
  const moment = imports.moment;
  const formElement = params.formElement;
  const _ = imports.lodash;
  let visibility = true;
  let value = null;
  let answersToSkip = [];
  let validationErrors = [];
  
  let age = moment(programEncounter.earliestVisitDateTime).diff(programEncounter.programEnrolment.individual.dateOfBirth,'years');
  
  const condition11 = age > 3 ;
  
  visibility = !(condition11 );
  
  return new imports.rulesConfig.FormElementStatus(formElement.uuid, visibility, value, answersToSkip, validationErrors);
};
```

**Comment by dinesh2096** [comment]
QA Reference video : 

[Click here to watch the video](https://drive.google.com/file/d/1Bt8CGxxHQDcgpOO5MFRlC_mo6BLlo_In/view?usp=drive_link)

**Comment by dinesh2096** [comment]
@adamsanadi6 we can move the changes to dev and prod
