### ISSUE TITLE
[APF] Child FW Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#45]
Report requirements:
https://docs.google.com/spreadsheets/d/1xs13aAsS5pvVbhS53pQNbGGwZDQC0xaF/edit#gid=1774501132

Acceptance criteria:
The report should have all the details displayed correctly as given in the requirement sheet.

**Comment by Dinesh2019** [comment]
getting below error.

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/b1851d21-e12d-42fc-b296-80aeed8acb20)

**Comment by AchalaBelokar** [comment]
- [ ] I created a one individual  which is child and fill the child follow up still it is not reflecting. name minu minu

**Comment by Dinesh2019** [comment]
Getting the below error when execution of query
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/fc8de72a-3219-4663-801e-8cfa6da41ef6)

**Comment by Gojo-Taqi** [comment]
After changing schema of the query, do this
ctrl + a
ctrl + enter

**Comment by Gojo-Taqi** [comment]
After changing schema of the query, do this
ctrl + a
ctrl + enter

**Comment by Dinesh2019** [comment]
Tried tthe above scenario.still getting same error.
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/17a71d35-e574-4a23-a83d-2b8c8f99f9d0)
