### ISSUE TITLE
APF Odisha Phase 2: Production Bug: Batch 8: Enable Overdue logic “ On Over-schedule, don't allow users to enter data” in Growth Monitoring Form

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#454]
- [ ] Changes to be first made in UAT
- [ ] Enable Overdue logic “ On Overschedule, don't allow users to enter data” in Growth Monitoring Form which we disabled recently. [Reference card](https://github.com/avniproject/apfodishanutrition/issues/442)

**Comment by dinesh2096** [comment]
QA Reference (UAT and dev):

[Click here to watch the video](https://drive.google.com/file/d/1Yv5tM84u1OHt3ngN4hc7U4SlumttDFfK/view?usp=drive_link)

@nupoorkhandelwal looks good u can move the changes to prod

**Comment by dinesh2096** [comment]
@AnjaliBhagabati you can info cilent and close the card looks good in Prod
