### ISSUE TITLE
[APF Odisha Phase 2]: Production Bug fixes - Batch 9: Two Offline Dashboard Card Not Showing for PS Users

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#456]
- [ ] Changes to be done in APF UAT environment
- [ ] **The Scheduled Visits and Backlog Visits cards** Offline Dashboard Cards are not appearing on the offline dashboard of Poshan Sathi users. Earlier these were part of the dashboard before the app was updated to the latest version.
- [ ] [Bug Details](https://docs.google.com/spreadsheets/d/1IlQJZDRw4rnuEHvO9HGJvvIQ6wPrXuGH8PdksUHYbm0/edit?gid=0#gid=0)

**Comment by nupoorkhandelwal** [comment]
set role apfodisha_dev;
update report_card
set is_voided = false,
    name = 'Overdue visits',
    last_modified_date_time = current_timestamp,
    last_modified_by_id = (select id from users where username = 'nupoork@apfodisha_dev')
where uuid = '0244a027-e9ac-4dff-87c8-4298c3168804';

set role apfodisha_dev;
update report_card
set is_voided = false,
    name = 'Due visits',
    last_modified_date_time = current_timestamp,
    last_modified_by_id = (select id from users where username = 'nupoork@apfodisha_dev')
where uuid = '7bcb72d8-2db3-4a7f-8868-a86f5baa95d7';

select * from report_card where uuid = '0244a027-e9ac-4dff-87c8-4298c3168804';
select * from report_card where uuid = '7bcb72d8-2db3-4a7f-8868-a86f5baa95d7';
