### ISSUE TITLE
[APF] Pregnant Women report - AWC wise

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#47]
**Report requirements:**
https://docs.google.com/spreadsheets/d/1xs13aAsS5pvVbhS53pQNbGGwZDQC0xaF/edit#gid=717719195

**Acceptance criteria:**
Along with mentioned requirements in the sheet, there should be a Linelist when user clicks on the count.

**Comment by vedfordev** [comment]
@utkarshavni @Dinesh2019 , It has same clarification required which dinesh asked in village report

**Comment by utkarshavni** [comment]
Moving this to deploy ready as the clarification has been incorporated in another card which is in analysis.
