### ISSUE TITLE
[APF] Child Report - AWC

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#48]
Report requirements:
https://docs.google.com/spreadsheets/d/1xs13aAsS5pvVbhS53pQNbGGwZDQC0xaF/edit#gid=628171778

**Comment by Dinesh2019** [comment]
Getting below error while execution.
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/d70acd3c-880e-42b5-bded-1797b466cd5f)
