### ISSUE TITLE
Set up Superset on Avni environment

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/apfodishanutrition#49]
### Infra required
- Separate VM (t3.medium, ubuntu 22 LTS, gp3 volumes). See if this can be brought down to a t3.small after installation
- RDS (db.t3.micro)
- Set up on reporting VPC and subnets
- Application firewall
- Static IP if available
- SSL certificate (on the firewall)
- App availability at https://reporting-superset.avniproject.org

### Tech notes
- Non-docker 
- Try this Ansible role, see if it is easy enough. https://github.com/onaio/ansible-superset
- Superset documentation available here - https://superset.apache.org/docs/installation/installing-superset-from-scratch . Doesn't seem extremely complicated
- Need to confirm if Celery is required

**Comment by vedfordev** [comment]
completed
