### ISSUE TITLE
[APF] Fix individual address data where AWC stored as lowest address

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#51]
- [ ] Share a list of all individuals who have AWC as lowest address to APF team to get a correct Village address 

- [ ] Create a script to achieve above change

Updated individuals list with correct mapping:
https://docs.google.com/spreadsheets/d/10d3Rsfmy7RVxv9ebNcMuQVxRu0FBs6LM/edit?usp=drive_web&ouid=100265945917284170678&rtpof=true

**Comment by utkarshavni** [comment]
@utkarshavni  waiting for correct mapping data from client.

**Comment by utkarshavni** [comment]
@nupoorkhandelwal updated card with list shared of individuals with mapping against villages.

**Comment by sachsk** [comment]
@utkarshavni  these villages are not present in the DB 
'Bada Dahikhal',
'Raikela',
'Badjala',
'Dumuniguda-3',
'Takara',
'Kardakudar',
'Dhanurjaypur',
'Tumkela',
'Upperdiha',
'Talasahi',
'Adibasi sahi',
'Kumbhirda',
'Sukhapali',
'Dumuniguda-2'

**Comment by sachsk** [comment]
since Utkarsh is not available moving this card on hold

created scripts for this 
https://github.com/avniproject/APF-Odisha/blob/main/change_address_awc_to_village.sql
