### ISSUE TITLE
[APF] Creating Partner users for Reports (SuperSet)

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#54]
Following are the users to be created for Superset of APF dashboards:  Users should only have access to the block mentioned in block column.
https://docs.google.com/spreadsheets/d/1aTcSUHjgP2bZZ6iAc1sPQR-S6zD_fMNB/edit#gid=1300979644

Ignore the first 6, they are already created.

**Comment by vedfordev** [comment]
done
