### ISSUE TITLE
[APF] Updates in existing PNC Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#56]
- [x] Add the columns highlighted in green in existing PNC report.
https://docs.google.com/spreadsheets/d/1TDBZKeqmt6-4Tos8XVCk0g1Sfep7QCEk/edit#gid=2135038156
- [x] Add the filters given in the sheet above for the report.

**Comment by vedfordev** [comment]
"Birth weight of child" concept  is from delivery encounter. In report we used pnc encounter. So how can we join pnc with delivery encounter ?

**Comment by AchalaBelokar** [comment]
- [ ] PNC  Filter should be  one 2, according to the sheet

**Comment by AchalaBelokar** [comment]
- [ ] PNC  Filter should be  one 2, according to the sheet
