### ISSUE TITLE
[APF] Updates in existing Child Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#57]
Changes to be made into following reports:
- Child (Village)
- Child (AWC)

- [ ] Add the columns highlighted in green in the sheet - for the reports:
https://docs.google.com/spreadsheets/d/1TDBZKeqmt6-4Tos8XVCk0g1Sfep7QCEk/edit#gid=1476686951
- [x] Add the filters mentioned in the sheet above

**Comment by vedfordev** [comment]
Child (Village) and Child (AWC) are aggregate report. So we can't add column Measurement efficiency (%) and Nutrition status.

**Comment by vedfordev** [comment]
@utkarshavni what is concept for "No of Childen enrolled in CMAM" ?

**Comment by AchalaBelokar** [comment]
- [ ] As mention in the sheet one filter is missing that is Nutrition Status.

**Comment by vedfordev** [comment]
@AchalaBelokar Nutrition Status filter not required
