### ISSUE TITLE
[APF] QRT PW report for severely anemic

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#61]
[ ] Linelist Report requirements - QRT PW for Severely Anemic - Ignore the columns in yellow legend
https://docs.google.com/spreadsheets/d/1TDBZKeqmt6-4Tos8XVCk0g1Sfep7QCEk/edit#gid=569537256
- [x] Filters required - GP, AWC, Month and Year

**Comment by vedfordev** [comment]
query :

```
select
    concat(ind.first_name,' ',ind.last_name) as "Name",
    ind."Father/Husband's name",
    anc.encounter_date_time "Date identified",
    anc."HB",
    qrt."Exit type"
from apfodisha.individual ind
join apfodisha.individual_pregnancy_anc anc on anc.individual_id = ind.id and anc."HB" < 7
join apfodisha.individual_pregnancy_qrt_pw qrt on qrt.individual_id = ind.id
where ind.is_voided = false
and anc.is_voided = false and anc.encounter_date_time notnull
and qrt.is_voided = false and qrt.encounter_date_time notnull;
```

**Comment by vedfordev** [comment]
Only 3 records found. In which anc's HB < 7 and qrt followup completed:

```
select count(*)
from apfodisha.individual_pregnancy_qrt_pw
where is_voided = false
and encounter_date_time notnull
and individual_id in(
    select individual_id from apfodisha.individual_pregnancy_anc anc where anc."HB" < 7 and encounter_date_time is not null
    );
```

**Comment by Dinesh2019** [comment]
In the Date filter, we have the condition 
WHERE "Date identified" >= TO_TIMESTAMP('2023-02-13 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.US')
  AND "Date identified" < TO_TIMESTAMP('2023-02-13 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.US')
so we cannot find the data for single date period

**Comment by utkarshavni** [comment]
Can be moved to prod.
