### ISSUE TITLE
[APF] Child Linelist report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#64]
- [x] Report requirements:
https://docs.google.com/spreadsheets/d/1TDBZKeqmt6-4Tos8XVCk0g1Sfep7QCEk/edit#gid=8375509

- [x] Provide filters for Registration date and Enrollment date
- [x] On applying filters the data should be displayed correctly based on the filters

**Comment by BEULAHEVANJALIN** [comment]
@utkarshavni Lemme know on which dashboard i should add this chart.

**Comment by AchalaBelokar** [comment]
- [ ] Breast feed till 2 year is not showing the no value. it is showing the null value.
- [ ] Look at the Anil Sahoo which is contain breastfeed value No

**Comment by BEULAHEVANJALIN** [comment]
@AchalaBelokar Need clarification for the following:

- There is no such child named Anil Sahoo. But I could see an individual whose father's name is Anil Sahoo and also that individual doesn't seem to be enrolled in any child program.
```
select *
from program_enrolment
where individual_id = (select id from apfodisha.individual where "Father/Husband's name" = 'Anil sahoo'); 
```

 

- Not sure why so many items have null values even though the field "Is the child Breast feed til 2 years?" is the required one.
```
select distinct "Is the child Breast feed til 2 years", count(*)
from apfodisha.individual_child
group by "Is the child Breast feed til 2 years";
```
