### ISSUE TITLE
APF Misc App and Report changes

### ISSUE THREAD

**Issue by arjunk** [avniproject/apfodishanutrition#66]
# App Changes
- [x] In the Child Dashboard, another card for MAM, similar to the SAM
- [x] Create a new Dashboard called 'Exit Due'. Purpose of this dashboard is to help the Poshan Sathi identify the individuals who are supposed to be exited from the program but have not been. Following two cards need to be created for two programs 
- [x] Child : Program enrolment Active and crossed 5 years in age
- [x] Pregnancy : 6 months from Delivery Encounter, date of delivery 
- [x] Add Age filter on Search Page

**Comment by BEULAHEVANJALIN** [comment]
Test query for point number 4:
```
select distinct (individual.id), concat(individual.first_name, ' ', individual.last_name), gender, age(date_of_birth)
from apfodisha.individual
         join apfodisha.individual_pregnancy on individual.id = individual_pregnancy.individual_id
         join apfodisha.individual_pregnancy_delivery on individual.id = individual_pregnancy_delivery.individual_id
where individual.is_voided = false
  and individual_pregnancy.is_voided = false
  and individual_pregnancy.program_exit_date_time is null
  and individual_pregnancy_delivery."Date of delivery" < current_date - INTERVAL '6 months'
  and individual.address_id in (select id
                                from apfodisha.address
                                where id in (select addresslevel_id
                                             from catchment_address_mapping
                                             where catchment_id = (select catchment_id
                                                                   from users
                                                                   where username = 'beulah@apfodisha')));
```

**Comment by BEULAHEVANJALIN** [comment]
All changes have been moved from prelease to UAT. But unable to test due to faulty data and getting SyncError.

**Comment by BEULAHEVANJALIN** [comment]
Add Age filter on Search Page is not working as expected. Tried in pre-release, as well in production (UAT) environment.

**Comment by Dinesh2019** [comment]
Getting this error while logging in
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/d55c905b-d494-49b5-872c-21f17b2a46b9)
