### ISSUE TITLE
[APF] App changes - Addition of new fields

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#68]
- [x] Visit Date field should allow past date in QRT SAM child visit, as the user could record data after the visit has been done. It should not allow a date before child enrollment date.
- [x] Place of Referral field in QRT SAM visit - Add "Home" option.
- [x] Add following fields in the QRT SAM visit - Refer the ones highlighted in green in the sheet.
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=142552483
- [x] Calculate Nutritional status at Discharge (Weight for height status) - by using Height at Discharge and Weight at Discharge values.
- [x] Since Height and Weight at Discharge fields are non-mandatory, the status should not be updated if the fields are not updated.
- [x] Add following questions in QRT PW form - Refer the ones highlighted in the green in sheet.
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1255247919

**Comment by utkarshavni** [comment]
Estimated time as mentioned @vedfordev  - 3 hours.

**Comment by vedfordev** [comment]
@utkarshavni In encounter user unable to select visit date before enrolment date

**Comment by utkarshavni** [comment]
@vedfordev  @dinesh2096   Change the validation message shown in the screenshot to "Date of referral cannot be after Visit date" since we are allowing past date to be selected in Visit date, showing "Today's date" in validation is misleading.
Move the changes to prod after making the validation change, everything else is fine.![WhatsApp Image 2023-07-02 at 18.57.05.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/efed60aa-95f7-45d5-a3df-25efe9d49dca)

**Comment by Dinesh2019** [comment]
Changes are made as per suggestion
