### ISSUE TITLE
[APF] Decision rules are absent in QRT SAM Child encounter

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#69]
Decision rules to calculate Nutritional status of child are not present in QRT SAM child form.  Refer to the Child Follow-up to see the decision rules.

- [x] Decision rules should be present in QRT SAM child to update Nutritional status according to Height and Weight captured.

**Comment by Gojo-Taqi** [comment]
ETC :- 15 mins
Time taken :- 33 mins
