### ISSUE TITLE
[APF] Configure custom dashboard filter and change dashboard cards  logic

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#71]
Org - APF Odisha UAT

Currently, the count on dashboard cards is not updated if location filter is configured and when user applies a filter. 

- [x] In the offline dashboard, Configure a filter for location. (Address)
- [x] Modify logic in cards to include the filter that is applied by user. 
- [x] On applying the location filter, count should be displayed based on the location - refer the sheet for example:
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=459175543

**Comment by Dinesh2019** [comment]
Created the bug card which will not block the user :
https://github.com/avniproject/avni-client/issues/1034
