### ISSUE TITLE
[APF] QRT migration 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#72]
**Pre** requisites 
 
Create a dashboard having following reports in it -

- [x] Create a report to show all the users who haven't synced only on Thursday ie. 22nd June before 3 pm.

 Details in report - 
1. Username
2. Phone number
3. email
4. User group
5. Last sync date time

- [x]  Total number/count of users in APF
- [x]  Total number of users who have synced atleast once till now

- [x] Share the above report with Jagadisha

- [x]  After getting confirmation from APF about the sync complete, follow below steps -
 https://docs.google.com/spreadsheets/d/1f0A6ngJ-ETgsdXlnLEey1w15wWB0jVqQAEeg2TDM_d0/edit#gid=0

**Comment by vedfordev** [comment]
Details :

```
with sync_ele as(
    select
        row_number() over (partition by user_id order by sync_start_time desc ) rank,
        user_id,
        sync_status,
        sync_end_time
    from sync_telemetry st
    where sync_end_time > date('2023-06-21') + '08:30'::time and sync_end_time < date('2023-06-23') + '08:30'::time
)
SELECT
       u.name,
       u.username,
       u.phone_number,
       u.email,
       se.sync_end_time,
       g.name
from users u
join user_group ug on u.id = ug.user_id
join public.groups g on ug.group_id = g.id
join sync_ele se on se.user_id = u.id and se.rank = 1
where
    u.is_voided = false
  and u.is_org_admin = false
  and g.name != 'Everyone'
order by 1;

```

**Comment by vedfordev** [comment]
total users

```
select count(*)
from users u where u.is_voided = false and u.is_org_admin = false;
```

**Comment by Dinesh2019** [comment]
- [ ] Location is not update to odisha
- [ ] Separated in the registration form is  not updated
- [ ] High risk in the summary is not updated
- [ ] Is the child registered under poshan tracker? in the summary and also in child register
- [ ] for child register summary Is the beneficiary registered in the AWC?
- [ ] In Dashboard MAM children is not translated 
- [ ] Pregnacy dashboard is not updated 
- [ ] child due dashboard is not trnalsated 
- [ ] Exit due dashboard is not translated
