### ISSUE TITLE
[APF] Configure location concept filter for custom dashboard

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#73]
**Use case**
Households are associated with specific AWCs by location field in the Registration where specific AWC is selected against the household to map.  Supervisor will need to see data on specific households and household members based on the AWC selected in Filter.

- [ ] Configure a filter for Location concept - user should be able to select specific AWC(s).
- [ ] Once the user selects a specific AWC and applies, the count on dashboard card should get  updated.
Requirements logic:
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=459175543
Refer from row 16.

**Comment by arjunk** [comment]
@utkarshavni which release was this dependent on ?

**Comment by nupoorkhandelwal** [comment]
Marking this card as closed, since we already have an address level filter added on the Dashboard
