### ISSUE TITLE
[APF] Add new columns in Reports.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#74]
Reference card for fields which are newly added:
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/68

- [x] Add new columns in QRT SAM Child - Refer to the columns in Yellow.
https://docs.google.com/spreadsheets/d/1TDBZKeqmt6-4Tos8XVCk0g1Sfep7QCEk/edit#gid=518317684

- [x] Add new columns in QRT PW report for Severely Anemic - Refer to the columns in yellow.
https://docs.google.com/spreadsheets/d/1TDBZKeqmt6-4Tos8XVCk0g1Sfep7QCEk/edit#gid=569537256

**Comment by vedfordev** [comment]
@utkarshavni estimate: 1 hrs

**Comment by vedfordev** [comment]
@utkarshavni Changing query to uat. At deploy time we have to change to prod.

**Comment by vedfordev** [comment]
time taken : 2 hrs

**Comment by utkarshavni** [comment]
Can be moved to prod.
