### ISSUE TITLE
[APF] Relapse report - Aggregate

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#75]
**Use case**
Relapse report as needed to monitor the progress of nutrition status of children and see the volume of children who are moving out of SAM and who are again falling back into the category of SAM.

- [x] Create Relapse report AWC wise
- [x] Create Relapse report Village wise

**Report requirements:**
https://docs.google.com/spreadsheets/d/1xs13aAsS5pvVbhS53pQNbGGwZDQC0xaF/edit#gid=651543572

**Tech Notes**
- Create month and year filters by using the custom dataset.
- For month and year take the filter params(using jinja template) in the query and implement logic
  - Sample chart for jinja template https://reporting-superset.avniproject.org/superset/dashboard/58/?native_filters_key=7pyoBSJ_mntyBWbjSccoJWEvYj41eyWGTCX6fHGmSimXnvk1c0wBfR2abhqBZ37E
  - Jinja template tutorial https://www.youtube.com/watch?v=dE1QlhunWMs

**Comment by vedfordev** [comment]
estimate 4 hours

**Comment by utkarshavni** [comment]
@sachsk @vedfordev @salilsamanvay 
Moved this story on hold as we need to check whether this will be possible on Superset. Sachin will look into this tomorrow.

**Comment by sachsk** [comment]
@utkarshavni its possible on the superset.
@utkarshavni the requirement sheet is not clear yet add the data point (from which fields and form data should taken)

**Comment by vedfordev** [comment]
@sachsk @utkarshavni 
tried with
1.  EXTRACT(MONTH FROM this_followup.encounter_date_time) = EXTRACT(MONTH FROM  '{{ date_filter}}' )
2. EXTRACT(MONTH FROM this_followup.encounter_date_time) = EXTRACT(MONTH FROM  {{  filter_values(date_filter) }} )
checkout dashboard : [ Jinja Avni ]

**Comment by vedfordev** [comment]
## Developer's Note:
---

### For village :

**Dataset :** apfodisha relapse aggregate village
**Dashboard :** [APFODISHA] Relapse Report(Village) - Aggregate

---

### For AWC:

**Dataset :** apfodisha relapse aggregate awc
**Dashboard :**  [APFODISHA] Relapse Report(AWC) - Aggregate

---

### For Filter:

#### Year:

**Dataset :** apfodisha Year

#### Month:

**Dataset :** Months


---

Currently all are set for apfodishauat

**Comment by Dinesh2019** [comment]
For AWC The data is not reflecting in the superset
