### ISSUE TITLE
[ APF] Relapse report - Linelist

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#76]
**Use case**
See all the children who are identified as SAM again in the ongoing month.

Report requirements:
https://docs.google.com/spreadsheets/d/1xs13aAsS5pvVbhS53pQNbGGwZDQC0xaF/edit#gid=536202430

- [x] Show the list of children who have been identified as SAM in the current month and were last identified as SAM before two months or more.
i.e. If a child has been identified as SAM in this month (June) again and was last identified as SAM April or before that but had recovered to be normal in between - then show those children.

**Comment by vedfordev** [comment]
@sachsk  
Please review script : [Script](https://gist.github.com/vedfordev/1528909873998d68cc34ac643488b7d9)

**Comment by vedfordev** [comment]
@sachsk @utkarshavni As we have discussed regarding month gap count

**Query for Consideration :**
```
select id,encounter_date_time,earliest_visit_date_time,"Weight for Height Status"
from apfodisha.individual_child_child_followup where individual_id = 1113700 and is_voided = false and encounter_date_time notnull  order by  encounter_date_time desc ;
```

### Presupposition :

If I have selected month as june and year as 2023

**Dataset :**
| id | encounter_date_time | earliest_visit_date_time | Weight for Height Status |
| --- | --- | --- | --- |
| 1803912 | 2023-06-11 05:31:38.000000 +00:00 | 2023-04-16 00:00:00.000000 +00:00 | SAM |
| 1752516 | 2023-03-21 11:49:50.000000 +00:00 | 2023-03-16 00:00:00.000000 +00:00 | Normal |
| 1705435 | 2023-03-06 05:50:04.000000 +00:00 | 2023-03-16 00:00:00.000000 +00:00 | MAM |
| 1656960 | 2023-02-16 04:15:53.000000 +00:00 | 2023-02-16 00:00:00.000000 +00:00 | SAM |

### Conclusion :

In gap count we have to consider gap between latest sam and it's previous sam. In above example latest sam (1803912) and it's previous sam (1656960). So gap between them are (03,04,05). So count will be 3.

**Comment by vedfordev** [comment]
**Dashboard :** :[ APFODISHA ] Relapse Report - LineList

**Comment by Dinesh2019** [comment]
The data in not captured in superset. We able to see the data in the ETL report also.

Client app :

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHM4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6bfa3b1dded71551c801d3da155af40a961a9092/Screenshot%202023-08-25%20at%206.31.43%20PM.png

DB screenshot;
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHc4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--86b98b4a12e18bd89c8af2c9dd5d42932ad3f74f/Screenshot%202023-08-25%20at%206.32.01%20PM.png

**Comment by vedfordev** [comment]
@Dinesh2019 we are only showing relapse. So you require min 2 encounter as Sam for relapse. I can see only one encounter check below query :


```
set role apfodishauat;

select *
from apfodishauat.individual_child_child_followup where individual_id = 1390372 and "Weight for Height Status" = 'SAM';

```
