### ISSUE TITLE
[APF Reports] Moving changes to Prod

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/apfodishanutrition#77]
- [x] Moving following cards to prod:

- [x] https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/67
- [x] https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/58
- [x] https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/74
- [x] https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/61
- [x] https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/68

**Comment by vedfordev** [comment]
Estimates : 2 hrs

**Comment by vedfordev** [comment]
time taken : 3 : 30 hrs
