### ISSUE TITLE
[APF] Village Information

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#8]
- [x] Create an individual subject type - "Village area inputs"
Subject registration location will be - "Village/Hamlet" and registration form will be blank

- [x] Create general encounter under this subject - "Village inputs"
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=310935299

- [x] Encounter eligibility check - To be shown only once.

**Comment by utkarshavni** [comment]
Jagadisha updated question in B21, moving this to Ready.
