### ISSUE TITLE
[APF Support] Change in decision rule

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#85]
Support ticket - https://avni.freshdesk.com/a/tickets/2958

- [x] Currently in APF, once the Delivery is done, there is no High Risk conditions that needs to be present in that profile, hence update the decision to have High Risk as "No" in Delivery and PNC forms under Pregnancy program.
- [x] Also, check that once Delivery form is completed, such individuals should not come in the High risk offline cards.

**Comment by sachsk** [comment]
We did this changes on UAT

**Comment by Dinesh2019** [comment]
@sachsk 

If we completed the delivery and after that, if I try to edit the enrolment to high risk the status got updated to high risk as yes 

Before editing the enrolment after completing the delivery

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDBLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb9d2d83558f6889cde57beffba78182d1e0bff4/device-2023-08-16-165316.webm)

**Comment by sachsk** [comment]
fixed rule in enrolment and anc visit

**Comment by Dinesh2019** [comment]
Test Scenario:

1.Create the individual and enrol in the pregrancy program as high risk
2.Do the ANC and still with the high risk
3.Complete the delivery high risk status updated as NO
4.Edit the enrol again with high risk and validate the high risk status NO is not get updated to yes 
5.repeat the step 4 again for ANC
6.Dashboard card should be updated as per the status

**Comment by Dinesh2019** [comment]
Test Scenario:

1.Create the individual and enrol in the pregrancy program as high risk
2.Do the ANC and still with the high risk
3.Complete the delivery high risk status updated as NO
4.Edit the enrol again with high risk and validate the high risk status NO is not get updated to yes 
5.repeat the step 4 again for ANC
6.Dashboard card should be updated as per the status

**Comment by sachsk** [comment]
@Dinesh2019 please test this card once again.
