### ISSUE TITLE
[APF Support] Fix Child followup report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#88]
Currently, Child followup report gives different number in a given time period. It should give fixed count in any point of time for a particular duration.

https://avni.freshdesk.com/a/tickets/3017

**Comment by nupoorkhandelwal** [comment]
The date filter needs to be applied on the CTE and not at the end of the query.

**Comment by sachsk** [comment]
Fixed this report : https://reporting-superset.avniproject.org/superset/dashboard/72/?edit=true&native_filters_key=3840uvBM6O9HyHMU8mEEM93m3pBIppk0VeobTR5C7zCh4Avq-IFzVq5MIV2JuYHV

**Comment by sachsk** [comment]
These individuals have the duplicate relationships 
-- 2096198
-- 2330059
-- 2331980
-- 2333687
