### ISSUE TITLE
[APF Support Prod] Update - Child followup report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#90]
## Subject: Child followup - Superset

Description:

- [x] Add AWC and Sector column
- [x] Add filters on AWC and Sector as well
- [x] Add date of measurement column - _this is already done_

**Comment by nupoorkhandelwal** [comment]
Some more changes -

1.  Add address level filters in all the reports
2.  Show ID of the individual in the Child Followup

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting-superset.avniproject.org/superset/dashboard/72/)

**Comment by Dinesh2019** [comment]
- [ ] Getting time out error 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemtaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dab587558d44f170d838c1080c8a40d64cfd7a49/Screenshot%202024-03-28%20at%206.52.25%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 6.52.25 AM.png" />

**Comment by adamsanadi6** [comment]
@Dinesh2019  After receiving confirmation from Sachin, it became clear that the person who wrote the query used the wrong method to join the tables, leading to timeout errors in certain cases. After discussing with Sachin, I rewrote the dataset query.
