### ISSUE TITLE
[APF Support] Create a metabase alert report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#94]
- [x] In APF, there are Individuals who are not registered on Village and instead have AWC as their lowest address level. We need to monitor any such new cases.
- [ ] Also, we need to share these individual details with the APF team and ask them to fix the address accordingly.

**Comment by Gojo-Taqi** [comment]
Link to the report :- https://reporting.avniproject.org/question/2641-apf-individuals-who-are-registered-in-awc-heirarchy
