### ISSUE TITLE
[APF Support] Fix visit scheduling issue

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#96]
As per the discussion in the call, it seems if a visit say Child Followup is scheduled for 23rd of September and got completed before 23rd then it again gets scheduled for 23rd of September.

- [ ] To reproduce and fix the above issues for all visits
- [ ] QA and move it to prod.

**Comment by mahalakshme** [comment]
this issue was there in sewa rural PNC visit as well and I fixed it. When finding next visit we would be getting from the schedule instead of following time interval. - not sure if this is what is expected here though.
