### ISSUE TITLE
[APF Odisha] Update missing genders in the database

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#97]
Support ticket - https://avni.freshdesk.com/a/tickets/3020

Some individuals have missing gender id in the individual table, we need to fix this data to avoid any issue on client/DEA or reports. Client has share the list for the same.

- [x] Write an update script to add the missing gender ids
- [x] Check if there are no more individual subject types with missing gender

Query used for looking such inds -

```
set role apfodisha;
select * from individual
left join address_level al on individual.address_id = al.id
where individual.is_voided = false
and subject_type_id = 672
and gender_id is null
order by individual.created_date_time desc;

```

https://docs.google.com/spreadsheets/d/1NG6vX5ufcIO81bmNwYYEGxzZT6lRU-ef3WzZIN_uvgA/edit#gid=495080036

**Comment by Dinesh2019** [comment]
@sachsk need to get the dev box
