### ISSUE TITLE
Remove vaccination permissions for QRT users

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#99]
Remove vaccination permissions for the QRT group.

Issue : Sync taking too much time for QRT users

Solution: As we know checklists (vaccination ) take significant time in the sync and for QRT users they don't need vaccination so we are removing the vaccination permissions for all QRT users to improve the sync time.

- [ ] Do this first on UAT if sync working fine then do this on Prod
- [x] Test the before and after sync time for some users

- [x] Need to test sync for some QRT users.

**Comment by BEULAHEVANJALIN** [comment]
syncing entities before changes in permissions: 14:17 to 14:35
sync 14:40 to 14:54

**Comment by BEULAHEVANJALIN** [comment]
Association error while syncing checklist

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a381a2d364b627e0af7749300efa932f8dede767/image.png)

**Comment by Dinesh2019** [comment]
maha_nayak@apfodisha 
Fresh sync -  11m 09s 62ms
Normal sun - 15s
Clear data and fresh sync - 15m 26s 56ms

8327789523@apfodisha
Fresh sync - 10m
Normal sync - 1m 
Clear data and fresh sync - 13m 

Beulah@apfodisha
Fresh sync - 15m 23s
Normal sync - 34s

7847977769@apfodisha 
Fresh Sync - 10m 11s
Normal sync -  8s


6371024901@apfodisha

Fresh Sync - 13m 16s
Normal sync -  15s 

7077280370@apfodisha
Fresh sync - 5m 25s 79ms
Normal sync - 10s

**Comment by Dinesh2019** [comment]
7846951001@apfodisha 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1pQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff44ff8c10e4e5a9ee9a4a8bfdc9623307cca53a/Screenshot%202023-10-10%20at%202.50.56%E2%80%AFPM.png

**Comment by Dinesh2019** [comment]
After data fix :
maha_nayak@apfodisha
Fresh sync - 12m 59s 77ms

**Comment by BEULAHEVANJALIN** [comment]
To be tested once the data fix scripts are run to prod
